DROP VIEW IF EXISTS V_PA_SESSIONS;

CREATE OR REPLACE SQL SECURITY INVOKER VIEW V_PA_SESSIONS AS
SELECT
  ID,
  SESSION_UUID,
  SITE_ID,
  DISTINCT_ID,
  BROWSER,
  OS,
  DEVICE,
  SCREEN,
  LANGUAGE,
  COUNTRY,
  SUBDIVISION1,
  CITY,
  CREATED_AT,
  UPDATED_AT
FROM PRODUCT_ANALYTICS_SESSION;
