(ns metabase-enterprise.metabot.tools.custom-viz-test
  (:require
   [clojure.string :as str]
   [clojure.test :refer :all]
   [metabase-enterprise.custom-viz-plugin.settings :as custom-viz.settings]
   [metabase-enterprise.metabot.tools.custom-viz]
   [metabase.metabot.agent.streaming :as streaming]
   [metabase.metabot.tools :as agent-tools]
   [metabase.metabot.tools.shared :as shared]
   [metabase.premium-features.test-util :as premium-features.tu]
   [metabase.test :as mt]
   [metabase.test.fixtures :as fixtures]
   [metabase.util :as u]
   [metabase.util.json :as json]
   [toucan2.core :as t2])
  (:import
   (java.nio.file Files LinkOption Path)))

(set! *warn-on-reflection* true)

(use-fixtures :once (fixtures/initialize :db :test-users))

(def ^:private factory-js
  "function () {
    return {
      id: 'metabot-generated-test',
      getName: function () { return 'Metabot Generated Test'; },
      checkRenderable: function () {},
      mount: function (container, initialProps) {
        var props = initialProps;
        function render() {
          container.innerHTML = '<div data-testid=\"generated-custom-viz\">' +
            String((props && props.settings && props.settings.label) || 'ready') +
            '</div>';
        }
        render();
        return {
          update: function (nextProps) {
            props = nextProps;
            render();
          },
          unmount: function () {
            container.innerHTML = '';
          }
        };
      }
    };
  }")

(defn- query []
  {:database (mt/id)
   :type     :query
   :query    {:source-table (mt/id :orders)}})

(defn- decode-question-url
  [url]
  (-> url
      (subs (count "/question#"))
      u/decode-base64
      (json/decode+kw)))

(defn- create-custom-viz!
  [identifier & [{:keys [display-name visualization-settings]
                  :or   {visualization-settings {:label "monthly stars"
                                                 :min 0
                                                 :max 15000}}}]]
  (let [memory (atom {:state {:queries {"orders-by-month" (query)}}})]
    (binding [shared/*memory-atom* memory]
      (agent-tools/create-custom-visualization-tool
       {:query_id "orders-by-month"
        :display_name (or display-name "Generated Star Rating")
        :identifier identifier
        :description "Generated by a Metabot unit test."
        :factory_js factory-js
        :visualization_settings visualization-settings}))))

(deftest create-custom-visualization-tool-test
  (premium-features.tu/with-premium-features #{:custom-viz}
    (mt/with-temporary-setting-values [custom-viz-enabled false]
      (let [identifier (str "metabot-generated-test-" (random-uuid))]
        (try
          (mt/as-admin
            (let [result          (create-custom-viz! identifier)
                  structured      (:structured-output result)
                  plugin          (t2/select-one :model/CustomVizPlugin :identifier identifier)
                  repository-path (:repository-path structured)
                  question-url    (get-in result [:data-parts 0 :data])
                  decoded         (decode-question-url question-url)]
              (testing "stores and enables a generated custom visualization plugin"
                (is (true? (custom-viz.settings/custom-viz-enabled)))
                (is (some? (:id plugin)))
                (is (= "Generated Star Rating" (:display_name plugin)))
                (is (= :active (:status plugin)))
                (is (true? (:enabled plugin)))
                (is (bytes? (t2/select-one-fn :bundle :model/CustomVizPlugin :id (:id plugin))))
                (is (string? (:bundle_hash plugin))))
              (testing "writes a source repository that can be inspected or built later"
                (is (str/starts-with? repository-path (System/getProperty "java.io.tmpdir")))
                (is (true? (Files/exists (Path/of repository-path (into-array String ["package.json"]))
                                         (into-array LinkOption []))))
                (is (true? (Files/exists (Path/of repository-path (into-array String ["src/index.js"]))
                                         (into-array LinkOption []))))
                (is (true? (Files/exists (Path/of repository-path (into-array String ["dist/index.js"]))
                                         (into-array LinkOption [])))))
              (testing "returns an embedded custom visualization link for the query"
                (is (= :custom-visualization (:result-type structured)))
                (is (= identifier (:identifier structured)))
                (is (= (str "custom:" identifier) (:chart-type structured)))
                (is (str/includes? (:output result) (str "custom:" identifier)))
                (is (= streaming/navigate-to-type (get-in result [:data-parts 0 :data-type])))
                (is (str/starts-with? question-url "/question#"))
                (is (= "question" (:type decoded)))
                (is (= (assoc (query) :type "query") (:dataset_query decoded)))
                (is (= (str "custom:" identifier) (:display decoded)))
                (is (true? (:displayIsLocked decoded)))
                (is (= {:label "monthly stars" :min 0 :max 15000}
                       (select-keys (:visualization_settings decoded) [:label :min :max])))
                (is (= {:id (:id plugin)
                        :identifier identifier
                        :display_name "Generated Star Rating"
                        :bundle_url (str "/api/ee/custom-viz-plugin/" (:id plugin) "/bundle?v=" (:bundle_hash plugin))
                        :bundle_hash (:bundle_hash plugin)}
                       (select-keys (get-in decoded [:visualization_settings :custom_viz.plugin])
                                    [:id :identifier :display_name :bundle_url :bundle_hash]))))))
          (finally
            (t2/delete! :model/CustomVizPlugin :identifier identifier)))))))

(deftest create-custom-visualization-tool-updates-existing-plugin-test
  (premium-features.tu/with-premium-features #{:custom-viz}
    (mt/with-temporary-setting-values [custom-viz-enabled false]
      (let [identifier (str "metabot-generated-test-" (random-uuid))]
        (try
          (mt/as-admin
            (create-custom-viz! identifier {:display-name "First Name"})
            (create-custom-viz! identifier {:display-name "Updated Name"})
            (is (= 1 (t2/count :model/CustomVizPlugin :identifier identifier)))
            (is (= "Updated Name"
                   (t2/select-one-fn :display_name :model/CustomVizPlugin :identifier identifier))))
          (finally
            (t2/delete! :model/CustomVizPlugin :identifier identifier)))))))
