import type { PayloadAction } from "@reduxjs/toolkit";
import { createSlice } from "@reduxjs/toolkit";

import type { GenerativeQuestion, GenerativeQuestionAuthor, GenerativeQuestionsState } from "metabase-types/store/generativeQuestions";

// Helper function to create metadata with current user and agent
export const createQuestionMetadata = (
  currentUser: { id: number; first_name: string | null; last_name: string | null } | null,
  agentType: string,
): GenerativeQuestion["metadata"] => {
  const authors: GenerativeQuestionAuthor[] = [];

  // Add current user as author
  if (currentUser) {
    const firstName = currentUser.first_name || "";
    const lastName = currentUser.last_name || "";
    const fullName = `${firstName} ${lastName}`.trim() || "Unknown User";

    authors.push({
      id: currentUser.id.toString(),
      name: fullName,
      type: "user",
      role: "Question Creator",
    });
  }

  // Add agent as author
  authors.push({
    id: "agent",
    name: agentType,
    type: "agent",
    role: "AI Assistant",
  });

  return {
    authors,
    tags: [],
    category: "analysis",
    difficulty: "medium",
    estimatedTime: 5,
  };
};

// Helper function to generate sample content based on prompt
export const generateSampleContent = (_prompt: string): string => {
  // For now, return a generic analysis content
  // In a real implementation, this would be generated by an AI service
  return `

## Executive Summary
Based on your data, Q4 2023 showed a **15% increase** in total sales compared to Q3, with the strongest performance coming from the Technology sector.

## Key Findings

### Revenue Growth
- Total revenue: $2.4M (up from $2.1M in Q3)
- Average order value: $1,200 (12% increase)
- Customer acquisition: 450 new customers

### Product Distribution
Here's how our products are distributed across categories:

{{viz:7:Product Category Breakdown:Distribution of products by category and title}}

### Product Category Breakdown Table
Below is a detailed breakdown of our product categories with revenue and growth metrics:

{{table:Product Categories:Category breakdown with revenue data}}

### Top Performing Products
1. **Cloud Storage Solutions** - $450K revenue
2. **Data Analytics Platform** - $380K revenue
3. **Security Suite** - $320K revenue

### Regional Performance
- North America: 45% of total sales
- Europe: 32% of total sales
- Asia Pacific: 23% of total sales

## Recommendations

1. **Focus on Technology Sector**: Continue investing in cloud and analytics products
2. **Expand European Market**: Consider localized marketing campaigns
3. **Customer Retention**: Implement loyalty programs for existing customers

## Next Steps

- Schedule follow-up analysis for Q1 2024
- Review pricing strategy for top-performing products
- Plan expansion into emerging markets
`;
};

const initialState: GenerativeQuestionsState = {
  questions: {},
  loading: false,
  error: null,
};

const generativeQuestionsSlice = createSlice({
  name: "generativeQuestions",
  initialState,
  reducers: {
    addGenerativeQuestion: (state, action: PayloadAction<GenerativeQuestion>) => {
      state.questions[action.payload.id] = action.payload;
    },
    updateGenerativeQuestion: (state, action: PayloadAction<Partial<GenerativeQuestion> & { id: string }>) => {
      const { id, ...updates } = action.payload;
      if (state.questions[id]) {
        state.questions[id] = {
          ...state.questions[id],
          ...updates,
          updatedAt: Date.now(),
        };
      }
    },
    removeGenerativeQuestion: (state, action: PayloadAction<string>) => {
      delete state.questions[action.payload];
    },
    setLoading: (state, action: PayloadAction<boolean>) => {
      state.loading = action.payload;
    },
    setError: (state, action: PayloadAction<string | null>) => {
      state.error = action.payload;
    },
  },
});

export const {
  addGenerativeQuestion,
  updateGenerativeQuestion,
  removeGenerativeQuestion,
  setLoading,
  setError,
} = generativeQuestionsSlice.actions;

export const generativeQuestionsReducer = generativeQuestionsSlice.reducer;
