import type { PayloadAction } from "@reduxjs/toolkit";
import { createSlice } from "@reduxjs/toolkit";

import type { ChatMessage, GenerativeQuestion, GenerativeQuestionAuthor, GenerativeQuestionReviewer, GenerativeQuestionsState, ReviewStatus } from "metabase-types/store/generativeQuestions";

// Helper function to create metadata with current user and agent
export const createQuestionMetadata = (
  currentUser: { id: number; first_name: string | null; last_name: string | null } | null,
  agentType: string,
): GenerativeQuestion["metadata"] => {
  const authors: GenerativeQuestionAuthor[] = [];

  // Add current user as author
  if (currentUser) {
    const firstName = currentUser.first_name || "";
    const lastName = currentUser.last_name || "";
    const fullName = `${firstName} ${lastName}`.trim() || "Unknown User";

    authors.push({
      id: currentUser.id.toString(),
      name: fullName,
      type: "user",
      role: "Question Creator",
    });
  }

  // Add agent as author
  authors.push({
    id: "agent",
    name: agentType,
    type: "agent",
    role: "AI Assistant",
  });

  return {
    authors,
    reviewers: [],
    tags: [],
    category: "analysis",
    difficulty: "medium",
    estimatedTime: 5,
  };
};

// Helper function to generate sample content based on prompt
export const generateSampleContent = (_prompt: string): string => {
  // For now, return a generic analysis content
  // In a real implementation, this would be generated by an AI service
  return `

## Executive Summary
Based on your data, Q4 2023 showed a **15% increase** in total sales compared to Q3, with the strongest performance coming from the Technology sector.

## Key Findings

### Revenue Growth
- Total revenue: $2.4M (up from $2.1M in Q3)
- Average order value: $1,200 (12% increase)
- Customer acquisition: 450 new customers

### Product Distribution
Here's how our products are distributed across categories:

{{viz:7:Product Category Breakdown:Distribution of products by category and title}}

### Product Category Breakdown Table
Below is a detailed breakdown of our product categories with revenue and growth metrics:

{{table:Product Categories:Category breakdown with revenue data}}

### Top Performing Products
1. **Cloud Storage Solutions** - $450K revenue
2. **Data Analytics Platform** - $380K revenue
3. **Security Suite** - $320K revenue

### Regional Performance
- North America: 45% of total sales
- Europe: 32% of total sales
- Asia Pacific: 23% of total sales

## Recommendations

1. **Focus on Technology Sector**: Continue investing in cloud and analytics products
2. **Expand European Market**: Consider localized marketing campaigns
3. **Customer Retention**: Implement loyalty programs for existing customers

## Next Steps

- Schedule follow-up analysis for Q1 2024
- Review pricing strategy for top-performing products
- Plan expansion into emerging markets
`;
};

// Sample questions with realistic data and review statuses
const sampleQuestions: Record<string, GenerativeQuestion> = {
  "q1": {
    id: "q1",
    prompt: "Analyze our Q4 2023 sales performance and identify key growth drivers",
    title: "Q4 2023 Sales Performance Analysis",
    content: `
## Executive Summary
Q4 2023 showed strong performance with **$2.4M in total revenue**, representing a 15% increase over Q3. The Technology sector led growth, contributing 45% of total sales.

## Key Findings

### Revenue Breakdown
- Total Revenue: $2.4M (↑15% vs Q3)
- Average Order Value: $1,200 (↑12%)
- New Customer Acquisition: 450 customers

### Product Performance
Our cloud storage solutions continue to dominate:

{{viz:7:Product Category Distribution:Revenue breakdown by product category}}

### Regional Insights
{{table:Regional Performance:Quarterly performance by region}}

### Top Growth Drivers
1. **Enterprise Cloud Solutions** - 35% growth
2. **Data Analytics Platform** - 28% growth
3. **Security Suite** - 22% growth

## Recommendations
- Continue investing in cloud infrastructure
- Expand European market presence
- Implement customer retention programs

## Next Steps
- Schedule Q1 2024 planning session
- Review pricing strategy for top performers
- Plan expansion into APAC markets
`,
    agentType: "Metabot: Your general purpose analyst",
    metadata: {
      authors: [
        { id: "1", name: "John Smith", type: "user", role: "Question Creator" },
        { id: "agent", name: "Metabot: Your general purpose analyst", type: "agent", role: "AI Assistant" }
      ],
      reviewers: [
        { id: "user2", name: "Sarah Johnson", email: "sarah.johnson@company.com", status: "verified", requestedAt: 1703000000000, reviewedAt: 1703086400000, comment: "Excellent analysis of Q4 trends. The cloud storage focus aligns with our strategy." },
        { id: "user3", name: "Mike Chen", email: "mike.chen@company.com", status: "commented", requestedAt: 1703000000000, reviewedAt: 1703072800000, comment: "Good insights, but we should include more data on customer churn rates." },
        { id: "user4", name: "Lisa Wong", email: "lisa.wong@company.com", status: "requested", requestedAt: 1703000000000 },
        { id: "user11", name: "Maria Garcia", email: "maria.garcia@company.com", status: "requested", requestedAt: 1703000000000, nodeId: "text-node-q4-2023-showed-strong-performance-with--0" },
        { id: "user12", name: "Chris Lee", email: "chris.lee@company.com", status: "requested", requestedAt: 1703000000000, nodeId: "text-node-our-cloud-storage-solutions-continue-to-dominate-0" }
      ],
      tags: ["sales", "Q4", "performance", "cloud"],
      category: "business-intelligence",
      difficulty: "medium",
      estimatedTime: 8
    },
    chatHistory: [
      {
        id: "msg1",
        role: "user",
        content: "Analyze our Q4 2023 sales performance and identify key growth drivers",
        timestamp: 1703000000000,
      },
      {
        id: "msg2",
        role: "assistant",
        content: "I'll analyze your Q4 2023 sales data to identify key growth drivers and provide actionable insights.",
        timestamp: 1703000060000,
      },
      {
        id: "msg3",
        role: "user",
        content: "Can you break down the regional performance in more detail?",
        timestamp: 1703000120000,
      },
      {
        id: "msg4",
        role: "assistant",
        content: "Here's a detailed regional breakdown:\n\n**North America (45% of sales):**\n- Strong enterprise adoption of cloud solutions\n- 28% growth in security products\n- Average deal size: $15K\n\n**Europe (32% of sales):**\n- Growing SMB market\n- 15% increase in analytics platform usage\n- Average deal size: $8K\n\n**Asia Pacific (23% of sales):**\n- Emerging market expansion\n- 40% growth in mobile solutions\n- Average deal size: $5K",
        timestamp: 1703000180000,
      },
      {
        id: "msg5",
        role: "user",
        content: "What about customer acquisition costs?",
        timestamp: 1703000240000,
      },
      {
        id: "msg6",
        role: "assistant",
        content: "Customer acquisition costs by region:\n\n- **North America:** $2,400 (down 8% from Q3)\n- **Europe:** $1,800 (down 12% from Q3)\n- **Asia Pacific:** $1,200 (down 15% from Q3)\n\nOverall CAC decreased by 11% due to improved marketing efficiency and word-of-mouth referrals from satisfied enterprise customers.",
        timestamp: 1703000300000,
      }
    ],
    createdAt: 1703000000000,
    updatedAt: 1703086400000,
    loading: false
  },
  "q2": {
    id: "q2",
    prompt: "What are our customer retention patterns and which segments are most at risk?",
    title: "Customer Retention Analysis & Risk Assessment",
    content: `
## Customer Retention Overview
Our overall retention rate stands at **87%**, with significant variations across customer segments.

## Retention by Segment

### Enterprise Customers
- Retention Rate: 94% (↑2% vs last year)
- Average Lifetime Value: $45K
- Risk Level: Low

{{viz:8:Enterprise Retention Trends:Monthly retention rates for enterprise customers}}

### SMB Customers
- Retention Rate: 82% (↓3% vs last year)
- Average Lifetime Value: $8K
- Risk Level: Medium

### Risk Assessment Table
{{table:Customer Risk Matrix:Segmentation by retention risk and value}}

## Key Risk Factors
1. **Feature Adoption Gap** - 40% of churned customers used <3 features
2. **Support Response Time** - 15% longer for at-risk segments
3. **Pricing Sensitivity** - 25% of churned customers cited cost concerns

## Recommendations
- Implement proactive outreach for SMB segment
- Develop feature adoption campaigns
- Optimize support response times

## Action Items
- Create customer success playbook for at-risk segments
- Launch feature discovery workshops
- Review pricing strategy for SMB market
`,
    agentType: "Data Analyst",
    metadata: {
      authors: [
        { id: "1", name: "John Smith", type: "user", role: "Question Creator" },
        { id: "agent", name: "Data Analyst", type: "agent", role: "AI Assistant" }
      ],
      reviewers: [
        { id: "user5", name: "David Brown", email: "david.brown@company.com", status: "problematic", requestedAt: 1702500000000, reviewedAt: 1702586400000, comment: "The analysis misses key demographic factors. Need to include age and industry breakdowns." },
        { id: "user2", name: "Sarah Johnson", email: "sarah.johnson@company.com", status: "verified", requestedAt: 1702500000000, reviewedAt: 1702572800000, comment: "Solid analysis with actionable insights for customer success team." },
        { id: "user13", name: "Jennifer Kim", email: "jennifer.kim@company.com", status: "requested", requestedAt: 1702500000000, nodeId: "text-node-our-overall-retention-rate-stands-at-87-0" },
        { id: "user14", name: "Robert Taylor", email: "robert.taylor@company.com", status: "commented", requestedAt: 1702500000000, reviewedAt: 1702572800000, comment: "The enterprise segment analysis needs more detail.", nodeId: "text-node-enterprise-customers-0" }
      ],
      tags: ["retention", "customers", "risk", "churn"],
      category: "customer-analytics",
      difficulty: "hard",
      estimatedTime: 12
    },
    chatHistory: [
      {
        id: "msg1",
        role: "user",
        content: "What are our customer retention patterns and which segments are most at risk?",
        timestamp: 1702500000000,
      },
      {
        id: "msg2",
        role: "assistant",
        content: "I'll analyze your customer retention data to identify patterns and risk factors across different segments.",
        timestamp: 1702500060000,
      },
      {
        id: "msg3",
        role: "user",
        content: "Can you focus on the SMB segment? I'm concerned about the 3% decline.",
        timestamp: 1702500120000,
      },
      {
        id: "msg4",
        role: "assistant",
        content: "Here's a detailed SMB analysis:\n\n**SMB Segment Deep Dive:**\n- Current retention: 82% (down from 85% last year)\n- Average customer lifetime: 18 months\n- Top churn reasons:\n  - Pricing concerns (35%)\n  - Feature complexity (28%)\n  - Support response time (22%)\n\n**Risk Factors:**\n- 60% of SMB customers use <5 features\n- Support tickets take 4.2 hours average response\n- 40% haven't completed onboarding\n\n**Immediate Actions Needed:**\n- Implement SMB-specific onboarding\n- Create simplified feature bundles\n- Reduce support response time to <2 hours",
        timestamp: 1702500180000,
      },
      {
        id: "msg5",
        role: "user",
        content: "What's the cost to implement these improvements?",
        timestamp: 1702500240000,
      },
      {
        id: "msg6",
        role: "assistant",
        content: "Estimated implementation costs:\n\n**Onboarding Improvements:**\n- Dedicated SMB success manager: $85K/year\n- Automated onboarding flows: $25K development\n- Training materials: $15K\n\n**Support Optimization:**\n- Additional support staff: $120K/year\n- Knowledge base development: $30K\n- Response time monitoring: $10K\n\n**Total Investment:** $285K\n\n**Expected ROI:**\n- 5% retention improvement = $400K additional revenue\n- Payback period: 8.5 months\n- 3-year ROI: 320%",
        timestamp: 1702500300000,
      }
    ],
    createdAt: 1702500000000,
    updatedAt: 1702586400000,
    loading: false
  },
  "q3": {
    id: "q3",
    prompt: "Compare our marketing campaign performance across different channels",
    title: "Multi-Channel Marketing Campaign Analysis",
    content: `
## Campaign Performance Summary
Our Q4 marketing campaigns generated **$850K in attributed revenue** across 5 channels.

## Channel Performance

### Top Performing Channels
1. **LinkedIn** - $320K (38% of total)
2. **Google Ads** - $280K (33% of total)
3. **Email Marketing** - $150K (18% of total)

{{viz:12:Channel Performance:Revenue and conversion rates by marketing channel}}

### Campaign ROI Analysis
{{table:Marketing ROI:Return on investment by campaign and channel}}

## Key Insights
- **LinkedIn** shows highest conversion rate (3.2%)
- **Email** has lowest cost per acquisition ($45)
- **Social Media** needs optimization (1.1% conversion)

## Recommendations
- Increase LinkedIn ad spend by 25%
- Optimize email segmentation strategy
- Redesign social media creative assets

## Budget Allocation
- LinkedIn: 40% of budget
- Google Ads: 35% of budget
- Email: 15% of budget
- Social: 10% of budget
`,
    agentType: "Business Intelligence",
    metadata: {
      authors: [
        { id: "1", name: "John Smith", type: "user", role: "Question Creator" },
        { id: "agent", name: "Business Intelligence", type: "agent", role: "AI Assistant" }
      ],
      reviewers: [
        { id: "user3", name: "Mike Chen", email: "mike.chen@company.com", status: "commented", requestedAt: 1702000000000, reviewedAt: 1702086400000, comment: "Good analysis, but we should include attribution modeling details." },
        { id: "user4", name: "Lisa Wong", email: "lisa.wong@company.com", status: "requested", requestedAt: 1702000000000 },
        { id: "user5", name: "David Brown", email: "david.brown@company.com", status: "requested", requestedAt: 1702000000000 },
        { id: "user6", name: "Alex Thompson", email: "alex.thompson@company.com", status: "requested", requestedAt: 1702000000000, nodeId: "text-node-our-q4-marketing-campaigns-generated-850k-0" },
        { id: "user7", name: "Emma Davis", email: "emma.davis@company.com", status: "requested", requestedAt: 1702000000000, nodeId: "text-node-linkedin-shows-highest-conversion-rate-32-0" },
        { id: "user8", name: "James Wilson", email: "james.wilson@company.com", status: "commented", requestedAt: 1702000000000, reviewedAt: 1702086400000, comment: "The ROI analysis looks solid.", nodeId: "text-node-linkedin-320k-38-of-total-0" }
      ],
      tags: ["marketing", "campaigns", "ROI", "channels"],
      category: "marketing-analytics",
      difficulty: "medium",
      estimatedTime: 6
    },
    chatHistory: [
      {
        id: "msg1",
        role: "user",
        content: "Compare our marketing campaign performance across different channels",
        timestamp: 1702000000000,
      },
      {
        id: "msg2",
        role: "assistant",
        content: "I'll analyze your marketing campaign performance across all channels to identify the most effective strategies.",
        timestamp: 1702000060000,
      },
      {
        id: "msg3",
        role: "user",
        content: "Which channel has the best ROI?",
        timestamp: 1702000120000,
      },
      {
        id: "msg4",
        role: "assistant",
        content: "Here's the ROI breakdown by channel:\n\n**Email Marketing:** 450% ROI (highest)\n- Cost: $33K\n- Revenue: $150K\n- Conversion rate: 2.8%\n\n**LinkedIn:** 320% ROI\n- Cost: $100K\n- Revenue: $320K\n- Conversion rate: 3.2%\n\n**Google Ads:** 280% ROI\n- Cost: $100K\n- Revenue: $280K\n- Conversion rate: 2.1%\n\n**Social Media:** 180% ROI (lowest)\n- Cost: $50K\n- Revenue: $90K\n- Conversion rate: 1.1%\n\nEmail marketing shows the best ROI due to lower costs and highly targeted audience.",
        timestamp: 1702000180000,
      },
      {
        id: "msg5",
        role: "user",
        content: "Should we increase email marketing budget?",
        timestamp: 1702000240000,
      },
      {
        id: "msg6",
        role: "assistant",
        content: "Yes, but with caution. Here's why:\n\n**Pros of increasing email budget:**\n- Highest ROI among all channels\n- Lower customer acquisition cost ($45 vs $312 for LinkedIn)\n- Better targeting capabilities\n- Scalable with automation\n\n**Considerations:**\n- Email list quality is crucial\n- Risk of diminishing returns\n- Need to maintain engagement rates\n- Compliance with email regulations\n\n**Recommendation:**\n- Increase email budget by 30% ($43K total)\n- Focus on segmentation and personalization\n- A/B test subject lines and content\n- Monitor deliverability and engagement metrics\n\nExpected outcome: $195K revenue (30% increase) with 450% ROI maintained.",
        timestamp: 1702000300000,
      }
    ],
    createdAt: 1702000000000,
    updatedAt: 1702086400000,
    loading: false
  },
  "q4": {
    id: "q4",
    prompt: "What are the seasonal patterns in our product usage and how do they affect capacity planning?",
    title: "Seasonal Usage Patterns & Capacity Planning",
    content: `
## Seasonal Usage Analysis
Our platform shows clear seasonal patterns with **peak usage during Q4** (holiday season) and **lowest usage in Q2**.

## Usage Patterns by Quarter

### Q4 (Peak Season)
- Average Daily Users: 45K
- Peak Concurrent Users: 12K
- Storage Usage: 2.8TB

{{viz:7:Seasonal Usage Trends:Monthly active users and system load}}

### Capacity Planning Insights
{{table:Capacity Requirements:Infrastructure needs by season and growth projections}}

## Key Findings
- **Q4 usage** is 40% higher than Q2
- **Storage growth** averages 15% quarter-over-quarter
- **Peak hours** are 2-4 PM EST during weekdays

## Infrastructure Recommendations
- Scale up capacity by 50% for Q4
- Implement auto-scaling for storage
- Add CDN nodes for peak traffic

## Cost Implications
- Q4 infrastructure costs: $85K/month
- Q2 infrastructure costs: $55K/month
- Annual savings potential: $120K with optimization
`,
    agentType: "Data Scientist",
    metadata: {
      authors: [
        { id: "1", name: "John Smith", type: "user", role: "Question Creator" },
        { id: "agent", name: "Data Scientist", type: "agent", role: "AI Assistant" }
      ],
      reviewers: [
        { id: "user2", name: "Sarah Johnson", email: "sarah.johnson@company.com", status: "verified", requestedAt: 1701500000000, reviewedAt: 1701586400000, comment: "Excellent analysis for infrastructure planning. The seasonal patterns are clearly identified." },
        { id: "user3", name: "Mike Chen", email: "mike.chen@company.com", status: "verified", requestedAt: 1701500000000, reviewedAt: 1701572800000, comment: "Great insights for capacity planning. The cost implications are particularly valuable." },
        { id: "user9", name: "Rachel Green", email: "rachel.green@company.com", status: "requested", requestedAt: 1701500000000, nodeId: "text-node-our-platform-shows-clear-seasonal-patterns-0" },
        { id: "user10", name: "Tom Anderson", email: "tom.anderson@company.com", status: "commented", requestedAt: 1701500000000, reviewedAt: 1701572800000, comment: "The Q4 usage spike analysis needs more detail.", nodeId: "text-node-q4-peak-season-0" }
      ],
      tags: ["seasonal", "capacity", "infrastructure", "usage"],
      category: "technical-analytics",
      difficulty: "hard",
      estimatedTime: 10
    },
    chatHistory: [
      {
        id: "msg1",
        role: "user",
        content: "What are the seasonal patterns in our product usage and how do they affect capacity planning?",
        timestamp: 1701500000000,
      },
      {
        id: "msg2",
        role: "assistant",
        content: "I'll analyze your product usage patterns to identify seasonal trends and their impact on capacity planning.",
        timestamp: 1701500060000,
      },
      {
        id: "msg3",
        role: "user",
        content: "How much should we scale up for Q4?",
        timestamp: 1701500120000,
      },
      {
        id: "msg4",
        role: "assistant",
        content: "Based on historical data, here's the recommended Q4 scaling:\n\n**Infrastructure Scaling:**\n- Compute capacity: +50% (from 45K to 67K daily users)\n- Storage: +60% (from 2.8TB to 4.5TB)\n- Bandwidth: +75% (peak concurrent users: 12K to 21K)\n\n**Cost Breakdown:**\n- Current monthly cost: $55K\n- Q4 monthly cost: $85K\n- Additional investment: $30K/month\n\n**Risk Mitigation:**\n- Auto-scaling policies for 20% buffer\n- CDN expansion for global traffic\n- Database read replicas for query load\n\n**ROI Justification:**\n- Q4 revenue typically 40% higher\n- Infrastructure cost increase: 55%\n- Net margin improvement: 25%",
        timestamp: 1701500180000,
      },
      {
        id: "msg5",
        role: "user",
        content: "What about the cost savings in Q2?",
        timestamp: 1701500240000,
      },
      {
        id: "msg6",
        role: "assistant",
        content: "Great question! Here's the Q2 optimization strategy:\n\n**Q2 Cost Reduction Opportunities:**\n- Scale down compute by 30% (saves $16K/month)\n- Reduce storage instances by 25% (saves $8K/month)\n- Optimize CDN usage (saves $6K/month)\n\n**Total Q2 Savings:** $30K/month\n\n**Annual Impact:**\n- Q4 additional cost: $90K (3 months)\n- Q2 savings: $30K (3 months)\n- Q1/Q3 neutral: $0\n- **Net annual cost increase:** $60K\n\n**Alternative Strategy:**\n- Implement spot instances for non-critical workloads\n- Use reserved instances for baseline capacity\n- **Potential additional savings:** $20K/year\n\nThis brings the net annual cost increase down to $40K, which is 0.8% of typical Q4 revenue.",
        timestamp: 1701500300000,
      }
    ],
    createdAt: 1701500000000,
    updatedAt: 1701586400000,
    loading: false
  }
};

const initialState: GenerativeQuestionsState = {
  questions: sampleQuestions,
  loading: false,
  error: null,
};

const generativeQuestionsSlice = createSlice({
  name: "generativeQuestions",
  initialState,
  reducers: {
    addGenerativeQuestion: (state, action: PayloadAction<GenerativeQuestion>) => {
      const question = action.payload;
      // Initialize chat history with the initial prompt if not provided
      if (!question.chatHistory || question.chatHistory.length === 0) {
        question.chatHistory = [
          {
            id: `msg-${Date.now()}`,
            role: "user",
            content: question.prompt,
            timestamp: question.createdAt,
          },
        ];
      }
      state.questions[question.id] = question;
    },
    updateGenerativeQuestion: (state, action: PayloadAction<Partial<GenerativeQuestion> & { id: string }>) => {
      const { id, ...updates } = action.payload;
      if (state.questions[id]) {
        state.questions[id] = {
          ...state.questions[id],
          ...updates,
          updatedAt: Date.now(),
        };
      }
    },
    addReviewer: (state, action: PayloadAction<{ questionId: string; reviewer: GenerativeQuestionReviewer }>) => {
      const { questionId, reviewer } = action.payload;
      if (state.questions[questionId]) {
        state.questions[questionId].metadata.reviewers.push(reviewer);
        state.questions[questionId].updatedAt = Date.now();
      }
    },
    addNodeReviewer: (state, action: PayloadAction<{ questionId: string; nodeId: string; reviewer: GenerativeQuestionReviewer }>) => {
      const { questionId, nodeId, reviewer } = action.payload;
      if (state.questions[questionId]) {
        const nodeReviewer = {
          ...reviewer,
          nodeId,
          status: "requested" as ReviewStatus,
          requestedAt: Date.now(),
        };
        state.questions[questionId].metadata.reviewers.push(nodeReviewer);
        state.questions[questionId].updatedAt = Date.now();
      }
    },
    updateReviewerStatus: (state, action: PayloadAction<{ questionId: string; reviewerId: string; status: ReviewStatus; comment?: string }>) => {
      const { questionId, reviewerId, status, comment } = action.payload;
      if (state.questions[questionId]) {
        const reviewer = state.questions[questionId].metadata.reviewers.find(r => r.id === reviewerId);
        if (reviewer) {
          reviewer.status = status;
          reviewer.reviewedAt = Date.now();
          if (comment) {
            reviewer.comment = comment;
          }
          state.questions[questionId].updatedAt = Date.now();
        }
      }
    },
    removeGenerativeQuestion: (state, action: PayloadAction<string>) => {
      delete state.questions[action.payload];
    },
    setLoading: (state, action: PayloadAction<boolean>) => {
      state.loading = action.payload;
    },
    setError: (state, action: PayloadAction<string | null>) => {
      state.error = action.payload;
    },
    addChatMessage: (state, action: PayloadAction<{ questionId: string; message: ChatMessage }>) => {
      const { questionId, message } = action.payload;
      if (state.questions[questionId]) {
        state.questions[questionId].chatHistory.push(message);
        state.questions[questionId].updatedAt = Date.now();
      }
    },
    updateChatMessage: (state, action: PayloadAction<{ questionId: string; messageId: string; updates: Partial<ChatMessage> }>) => {
      const { questionId, messageId, updates } = action.payload;
      if (state.questions[questionId]) {
        const messageIndex = state.questions[questionId].chatHistory.findIndex(m => m.id === messageId);
        if (messageIndex !== -1) {
          state.questions[questionId].chatHistory[messageIndex] = {
            ...state.questions[questionId].chatHistory[messageIndex],
            ...updates,
          };
          state.questions[questionId].updatedAt = Date.now();
        }
      }
    },
  },
});

export const {
  addGenerativeQuestion,
  updateGenerativeQuestion,
  addReviewer,
  addNodeReviewer,
  updateReviewerStatus,
  removeGenerativeQuestion,
  setLoading,
  setError,
  addChatMessage,
  updateChatMessage,
} = generativeQuestionsSlice.actions;

// Sample reviewers data - in a real app this would come from an API
export const getAvailableReviewers = (): Array<{ id: string; name: string; email: string; avatar?: string }> => [
  { id: "user1", name: "John Smith", email: "john.smith@company.com", avatar: "https://i.pravatar.cc/150?img=1" },
  { id: "user2", name: "Sarah Johnson", email: "sarah.johnson@company.com", avatar: "https://i.pravatar.cc/150?img=2" },
  { id: "user3", name: "Mike Chen", email: "mike.chen@company.com", avatar: "https://i.pravatar.cc/150?img=3" },
  { id: "user4", name: "Lisa Wong", email: "lisa.wong@company.com", avatar: "https://i.pravatar.cc/150?img=4" },
  { id: "user5", name: "David Brown", email: "david.brown@company.com", avatar: "https://i.pravatar.cc/150?img=5" },
  { id: "user6", name: "Alex Thompson", email: "alex.thompson@company.com", avatar: "https://i.pravatar.cc/150?img=6" },
  { id: "user7", name: "Emma Davis", email: "emma.davis@company.com", avatar: "https://i.pravatar.cc/150?img=7" },
  { id: "user8", name: "James Wilson", email: "james.wilson@company.com", avatar: "https://i.pravatar.cc/150?img=8" },
  { id: "user9", name: "Rachel Green", email: "rachel.green@company.com", avatar: "https://i.pravatar.cc/150?img=9" },
  { id: "user10", name: "Tom Anderson", email: "tom.anderson@company.com", avatar: "https://i.pravatar.cc/150?img=10" },
  { id: "user11", name: "Maria Garcia", email: "maria.garcia@company.com", avatar: "https://i.pravatar.cc/150?img=11" },
  { id: "user12", name: "Chris Lee", email: "chris.lee@company.com", avatar: "https://i.pravatar.cc/150?img=12" },
  { id: "user13", name: "Jennifer Kim", email: "jennifer.kim@company.com", avatar: "https://i.pravatar.cc/150?img=13" },
  { id: "user14", name: "Robert Taylor", email: "robert.taylor@company.com", avatar: "https://i.pravatar.cc/150?img=14" },
];

export const generativeQuestionsReducer = generativeQuestionsSlice.reducer;
