(ns metabase.metabot.capabilities
  "Capability normalization shared by profiles and skills.

  Capabilities arrive from the API as strings (e.g. \"frontend:navigate_user_v1\") while tool/skill
  metadata uses keywords (e.g. :frontend-navigate-user-v1).
  Some capabilities are inferred from backend state rather than sent by the frontend."
  (:require
   [clojure.string :as str]
   [metabase.premium-features.core :as premium-features]))

(set! *warn-on-reflection* true)

(def ^:private api-string->capability-keyword
  "Map from API capability strings (as sent by the frontend) to the keywords used in tool/skill
  `:capabilities` metadata."
  {"frontend:navigate_user_v1"    :frontend-navigate-user-v1
   "permission:save_questions"    :permission-save-questions
   "permission:write_sql_queries" :permission-write-sql-queries
   "permission:write_transforms"  :permission-write-transforms})

(defn- capability->keyword
  "Normalize a capability value to a keyword.
  Strings are looked up in the api-string->capability-keyword map; keywords are returned as-is."
  [cap]
  (if (keyword? cap)
    cap
    (or (api-string->capability-keyword cap)
        ;; Fallback: keywordize unknown strings so new capabilities degrade
        ;; gracefully without requiring a map update.
        (keyword (-> (str cap) (str/replace ":" "-") (str/replace "_" "-"))))))

(defn- feature-capabilities
  "Return the set of capabilities inferred from BE state rather than sent from the FE.
  Generated by function to avoid staleness."
  []
  (into #{}
        (remove nil?)
        [(when (or (not (premium-features/is-hosted?))
                   (premium-features/has-feature? :transforms-basic))
           :feature-transforms)
         (when (premium-features/has-feature? :transforms-python)
           :feature-transforms-python)
         (when (premium-features/has-feature? :semantic-search)
           :feature-semantic-search)]))

(defn capability-set
  "Build the full set of capability keywords for a request: the backend-inferred feature capabilities
  unioned with the (normalized) capabilities from the API."
  [capabilities]
  (into (feature-capabilities)
        (map capability->keyword)
        capabilities))
