(ns metabase.metabot.tools
  "Tool registry for the agent loop.
  Provides tool vars and state-aware wrapping.

  Each tool is a var whose metadata contains `:tool-name`, `:schema`, and optionally
  `:capabilities`, `:prompt`, `:decode`, and `:system-instructions`. The var itself
  is a function that takes the tool arguments and returns a result map."
  (:require
   [metabase.api-scope.core :as api-scope]
   [metabase.metabot.scope :as scope]
   [metabase.metabot.tools.analyze-chart :as tools.analyze-chart]
   [metabase.metabot.tools.autogen-dashboard :as tools.autogen-dashboard]
   [metabase.metabot.tools.charts :as tools.charts]
   [metabase.metabot.tools.clarification :as tools.clarification]
   [metabase.metabot.tools.construct :as tools.construct]
   [metabase.metabot.tools.create-alert :as tools.create-alert]
   [metabase.metabot.tools.create-dashboard-subscription :as tools.create-dashboard-subscription]
   [metabase.metabot.tools.document :as tools.document]
   [metabase.metabot.tools.metadata :as tools.metadata]
   [metabase.metabot.tools.navigation :as tools.navigation]
   [metabase.metabot.tools.resources :as tools.resources]
   [metabase.metabot.tools.search :as tools.search]
   [metabase.metabot.tools.shared :as shared]
   [metabase.metabot.tools.slackbot-query :as tools.slackbot-query]
   [metabase.metabot.tools.snippets :as tools.snippets]
   [metabase.metabot.tools.sql :as tools.sql]
   [metabase.metabot.tools.static-viz :as tools.static-viz]
   [metabase.metabot.tools.subscriptions :as tools.subscriptions]
   [metabase.metabot.tools.todo :as tools.todo]
   [metabase.metabot.tools.transforms :as tools.transforms]
   [metabase.util.log :as log]
   [potemkin :as p]))

(set! *warn-on-reflection* true)

(p/import-vars
 [tools.analyze-chart
  analyze-chart-tool]
 [tools.search search-tool
  sql-search-tool
  nlq-search-tool
  transform-search-tool]
 [tools.construct
  construct-notebook-query-tool]
 [tools.document
  document-schema-collect-tool
  document-construct-sql-chart-tool
  document-construct-model-chart-tool]
 [tools.metadata
  list-available-data-sources-tool
  list-available-fields-tool
  get-field-values-tool]
 [tools.transforms
  get-transform-details-tool
  get-transform-python-library-details-tool
  write-transform-sql-tool
  write-transform-python-tool]
 [tools.sql
  create-sql-query-tool
  create-sql-query-code-edit-tool
  edit-sql-query-tool
  replace-sql-query-tool]
 [tools.charts
  create-chart-tool
  edit-chart-tool]
 [tools.resources
  read-resource-tool]
 [tools.todo
  todo-write-tool
  todo-read-tool]
 [tools.navigation
  navigate-user-tool]
 [tools.snippets
  list-snippets-tool
  get-snippet-details-tool]
 [tools.clarification
  ask-for-sql-clarification-tool]
 [tools.autogen-dashboard
  create-autogenerated-dashboard-tool]
 [tools.subscriptions
  create-dashboard-subscription-tool]
 [tools.slackbot-query
  slackbot-construct-notebook-query-tool]
 [tools.static-viz
  static-viz-tool]
 [tools.create-alert
  create-alert-tool]
 [tools.create-dashboard-subscription
  slackbot-create-dashboard-subscription-tool])

(def ^:private state-dependent-tools
  "Set of tool names that require access to agent state."
  #{"analyze_chart"
    "create_chart" "edit_chart" "todo_write" "todo_read" "navigate_user"
    "write_transform_sql" "write_transform_python" "create_autogenerated_dashboard"
    "create_sql_query" "edit_sql_query" "replace_sql_query"
    "document_schema_collect" "document_construct_sql_chart" "document_construct_model_chart"
    "create_alert" "create_dashboard_subscription" "static_viz"})

(defn- wrap-with-scope-check
  "Wrap a tool function with a scope check. Returns a function that checks
  `*current-user-scope*` against `required-scope` before calling `f`.
  Returns a denial message if the scope is not satisfied."
  [f tool-name required-scope]
  (fn [args]
    (if (api-scope/scope-matches? scope/*current-user-scope* required-scope)
      (f args)
      (do (log/warnf "Scope check failed for tool %s — required: %s, granted: %s"
                     tool-name required-scope scope/*current-user-scope*)
          {:output "You do not have permission to use this tool."}))))

(defn wrap-tools-with-state
  "Wrap state-dependent tools with access to the memory atom.
  Tools in `state-dependent-tools` will have access to the memory atom
  via the dynamic `shared/*memory-atom*` binding.

  Takes a tools map where values are tool vars. Returns a tools map where
  values are tool definition maps (with :doc, :schema, :prompt, :fn, and
  optionally :decode keys).

  Tool-specific instructions are loaded from `resources/metabot/prompts/tools/`
  by `extract-tool-instructions` in `prompts.clj`, keyed by `:prompt` or
  `<tool-name>.md` by default."
  [tools memory-atom metabot-id]
  (reduce-kv
   (fn [acc tool-name tool-var]
     (let [m          (meta tool-var)
           base-fn    (if (contains? state-dependent-tools tool-name)
                        (fn [args]
                          (binding [shared/*memory-atom* memory-atom
                                    shared/*metabot-id*  metabot-id]
                            (tool-var args)))
                        (fn [args]
                          (binding [shared/*metabot-id* metabot-id]
                            (tool-var args))))
           tool-scope (:scope m)
           tool-fn    (if tool-scope
                        (wrap-with-scope-check base-fn tool-name tool-scope)
                        base-fn)
           tool-def   {:tool-name            (:tool-name m)
                       :doc                  (:doc m)
                       :schema               (:schema m)
                       :prompt               (:prompt m)
                       :decode               (:decode m)
                       :system-instructions  (:system-instructions m)
                       :capabilities         (:capabilities m)
                       :scope                (:scope m)
                       :fn                   tool-fn}]
       (assoc acc tool-name tool-def)))
   {}
   tools))
