/**
 * Metabase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.53.2-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MetabaseApi);
  }
}(this, function(expect, MetabaseApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MetabaseApi.ApiDatasetApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ApiDatasetApi', function() {
    describe('apiDatasetExportFormatPost', function() {
      it('should call apiDatasetExportFormatPost successfully', function(done) {
        //uncomment below and update the code to test apiDatasetExportFormatPost
        //instance.apiDatasetExportFormatPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiDatasetNativePost', function() {
      it('should call apiDatasetNativePost successfully', function(done) {
        //uncomment below and update the code to test apiDatasetNativePost
        //instance.apiDatasetNativePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiDatasetParameterSearchQueryPost', function() {
      it('should call apiDatasetParameterSearchQueryPost successfully', function(done) {
        //uncomment below and update the code to test apiDatasetParameterSearchQueryPost
        //instance.apiDatasetParameterSearchQueryPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiDatasetParameterValuesPost', function() {
      it('should call apiDatasetParameterValuesPost successfully', function(done) {
        //uncomment below and update the code to test apiDatasetParameterValuesPost
        //instance.apiDatasetParameterValuesPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiDatasetPivotPost', function() {
      it('should call apiDatasetPivotPost successfully', function(done) {
        //uncomment below and update the code to test apiDatasetPivotPost
        //instance.apiDatasetPivotPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiDatasetPost', function() {
      it('should call apiDatasetPost successfully', function(done) {
        //uncomment below and update the code to test apiDatasetPost
        //instance.apiDatasetPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiDatasetQueryMetadataPost', function() {
      it('should call apiDatasetQueryMetadataPost successfully', function(done) {
        //uncomment below and update the code to test apiDatasetQueryMetadataPost
        //instance.apiDatasetQueryMetadataPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
