/**
 * Metabase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.53.2-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MetabaseApi);
  }
}(this, function(expect, MetabaseApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MetabaseApi.ApiUserApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ApiUserApi', function() {
    describe('apiUserCurrentGet', function() {
      it('should call apiUserCurrentGet successfully', function(done) {
        //uncomment below and update the code to test apiUserCurrentGet
        //instance.apiUserCurrentGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiUserGet', function() {
      it('should call apiUserGet successfully', function(done) {
        //uncomment below and update the code to test apiUserGet
        //instance.apiUserGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiUserIdDelete', function() {
      it('should call apiUserIdDelete successfully', function(done) {
        //uncomment below and update the code to test apiUserIdDelete
        //instance.apiUserIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiUserIdGet', function() {
      it('should call apiUserIdGet successfully', function(done) {
        //uncomment below and update the code to test apiUserIdGet
        //instance.apiUserIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiUserIdModalModalPut', function() {
      it('should call apiUserIdModalModalPut successfully', function(done) {
        //uncomment below and update the code to test apiUserIdModalModalPut
        //instance.apiUserIdModalModalPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiUserIdPasswordPut', function() {
      it('should call apiUserIdPasswordPut successfully', function(done) {
        //uncomment below and update the code to test apiUserIdPasswordPut
        //instance.apiUserIdPasswordPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiUserIdPut', function() {
      it('should call apiUserIdPut successfully', function(done) {
        //uncomment below and update the code to test apiUserIdPut
        //instance.apiUserIdPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiUserIdReactivatePut', function() {
      it('should call apiUserIdReactivatePut successfully', function(done) {
        //uncomment below and update the code to test apiUserIdReactivatePut
        //instance.apiUserIdReactivatePut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiUserPost', function() {
      it('should call apiUserPost successfully', function(done) {
        //uncomment below and update the code to test apiUserPost
        //instance.apiUserPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiUserRecipientsGet', function() {
      it('should call apiUserRecipientsGet successfully', function(done) {
        //uncomment below and update the code to test apiUserRecipientsGet
        //instance.apiUserRecipientsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
