// Each entry is a case-insensitive regex tested against "<title> <story name>".
// A story runs when any entry matches.
export const STORY_FILTERS: readonly string[] = [
  "DataGrid",
  "static-viz",
  "viz",
  "Patterns/Upsells",
  "^visualizations/shared",
  "^app/embed",
  "^design system",
  "^Components/Overlays/Menu Hover state",
  "^Components/Overlays/Popover (Opened|Overview)",
  "^Components/Overlays/Modal Opened",
  "^Components/Overlays/HoverCard Opened",
  "^Components/Utils/Paper Shadow matrix",
  "^Components/Data display/Card Shadow matrix",
  "^Components/Inputs/Checkbox (Overview|Checkbox\\.Card)$",
  "^Components/Inputs/DatePicker Dates range",
  "^Components/Inputs/Radio (Overview|Radio\\.Card)$",
  "^Components/Inputs/Switch (Overview|Switch\\.Group)$",
  "^Components/Parameters/DatePicker",
  "^Components/Buttons/Button (Variant|Compact|Sections)",
  "^Components/Overlays/Tooltip",
  "^Components/Documents",
  "^Components/Feedback/Alert",
  "^Components/Feedback/Loader Overview",
  "^Components/Ask Before Using/Chip Overview",
  "^Components/Data display/Badge Sizes and variants",
  "^Components/Navigation/NavLink Overview",
  "^Components/Navigation/Tabs/Overview",
  "^Components/Data display/KeyboardShortcut Overview",
  "^Components/Table",
  "^Components/Inputs/PasswordInput Overview",
  "^App/Palette",
  "^viz/GridMapPdfExport",
  "ParameterValueWidget",
  "^Explorations/ExplorationGroupVisualization",
];
