(ns metabase-enterprise.serialization.v2.models
  "See [[metabase.models.serialization]] for documentation.")

(def data-model
  "Schema model types"
  ["Database"
   "Field"
   "FieldUserSettings"
   "Measure"
   "Segment"
   "Table"
   "Channel"])

(def content
  "Content model types"
  ["Action"
   "Card"
   "Collection"
   "Dashboard"
   "Document"
   "Glossary"
   "NativeQuerySnippet"
   "Timeline"])

(def exported-models
  "The list of all models exported by serialization by default. Used for production code and by tests."
  (concat data-model
          content
          ["FieldValues"
           "Metabot"
           "Setting"
           "Transform"
           "TransformJob"
           "TransformTag"]))

(def inlined-models
  "An additional list of models which are inlined into parent entities for serialization.
  These are not extracted and serialized separately, but they may need some processing done.
  For example, the models should also have their entity_id fields populated (if they have one)."
  ["DashboardCard"
   "DashboardTab"
   "Dimension"
   "ParameterCard"
   "DashboardCardSeries"
   "MetabotPrompt"
   "TimelineEvent"
   "TransformJobTransformTag"
   "TransformTransformTag"])

(def excluded-models
  "List of models which are not going to be serialized ever."
  ["ApiKey"
   "ApplicationPermissionsRevision"
   "AuditLog"
   "AuthIdentity"
   "BookmarkOrdering"
   "CacheConfig"
   "CardBookmark"
   "ChannelTemplate"
   "CloudMigration"
   "CollectionBookmark"
   "CollectionPermissionGraphRevision"
   "Comment"
   "CommentReaction"
   "ConnectionImpersonation"
   "ContentTranslation"
   "DashboardBookmark"
   "DataPermissions"
   "DatabaseRouter"
   "Dependency"
   "DocumentBookmark"
   "HTTPAction"
   "ImplicitAction"
   "LoginHistory"
   "MetabotConversation"
   "MetabotMessage"
   "ModelIndex"
   "ModelIndexValue"
   "ModerationReview"
   "Notification"
   "NotificationCard"
   "NotificationHandler"
   "NotificationRecipient"
   "NotificationSubscription"
   "Permissions"
   "PermissionsGroup"
   "PermissionsGroupMembership"
   "PermissionsRevision"
   "PersistedInfo"
   "PythonLibrary"
   "Pulse"
   "PulseCard"
   "PulseChannel"
   "PulseChannelRecipient"
   "Query"
   "QueryAction"
   "QueryCache"
   "QueryExecution"
   "QueryField"
   "QueryTable"
   "RecentViews"
   "RemoteSyncObject"
   "RemoteSyncTask"
   "Revision"
   "Sandbox"
   "SearchIndexMetadata"
   "Secret"
   "SemanticSearchTokenTracking"
   "Session"
   "SupportAccessGrantLog"
   "TaskHistory"
   "Tenant"
   "TransformJobRun"
   "TransformRun"
   "TransformRunCancelation"
   "Undo"
   "User"
   "UserKeyValue"
   "UserParameterValue"
   "ViewLog"])
