(ns metabase-enterprise.serialization.v2.models
  "See [[metabase.models.serialization]] for documentation.")

(def data-model
  "Schema model types"
  ["Database"
   "Field"
   "FieldUserSettings"
   "Measure"
   "Segment"
   "Table"
   "Channel"])

(def data-model-in-collection
  "Data model types that can be found in collections (via published tables).
   These are extracted by ID when discovered via descendants, even if no-data-model is set."
  ["Table"
   "Field"
   "Segment"])

(def content
  "Content model types"
  ["Action"
   "Card"
   "Collection"
   "Dashboard"
   "Document"
   "Glossary"
   "NativeQuerySnippet"
   "Timeline"])

(def exported-models
  "The list of all models exported by serialization by default. Used for production code and by tests."
  (concat data-model
          content
          ["FieldValues"
           "Metabot"
           "PythonLibrary"
           "Setting"
           "Transform"
           "TransformJob"
           "TransformTag"]))

(def inlined-models
  "An additional list of models which are inlined into parent entities for serialization.
  These are not extracted and serialized separately, but they may need some processing done.
  For example, the models should also have their entity_id fields populated (if they have one)."
  ["DashboardCard"
   "DashboardTab"
   "Dimension"
   "ParameterCard"
   "DashboardCardSeries"
   "MetabotPrompt"
   "TimelineEvent"
   "TransformJobTransformTag"
   "TransformTransformTag"])

(def excluded-models
  "List of models which are not going to be serialized ever."
  ["AnalysisFinding"
   "AnalysisFindingError"
   "ApiKey"
   "ApplicationPermissionsRevision"
   "AuditLog"
   "AuthIdentity"
   "BookmarkOrdering"
   "CacheConfig"
   "CardBookmark"
   "ChannelTemplate"
   "CloudMigration"
   "CollectionBookmark"
   "CollectionPermissionGraphRevision"
   "Comment"
   "CommentReaction"
   "ConnectionImpersonation"
   "ContentTranslation"
   "DashboardBookmark"
   "DataPermissions"
   "DatabaseRouter"
   "Dependency"
   "DocumentBookmark"
   "HTTPAction"
   "ImplicitAction"
   "LoginHistory"
   "MetabotConversation"
   "MetabotMessage"
   "ModelIndex"
   "ModelIndexValue"
   "ModerationReview"
   "Notification"
   "NotificationCard"
   "NotificationHandler"
   "NotificationRecipient"
   "NotificationSubscription"
   "Permissions"
   "PermissionsGroup"
   "PermissionsGroupMembership"
   "PermissionsRevision"
   "PersistedInfo"
   "Pulse"
   "PulseCard"
   "PulseChannel"
   "PulseChannelRecipient"
   "Query"
   "QueryAction"
   "QueryCache"
   "QueryExecution"
   "QueryField"
   "QueryTable"
   "RecentViews"
   "RemoteSyncObject"
   "RemoteSyncTask"
   "Revision"
   "Sandbox"
   "SearchIndexMetadata"
   "Secret"
   "SemanticSearchTokenTracking"
   "Session"
   "SupportAccessGrantLog"
   "TaskHistory"
   "TaskRun"
   "Tenant"
   "TransformJobRun"
   "TransformRun"
   "TransformRunCancelation"
   "Undo"
   "User"
   "UserKeyValue"
   "UserParameterValue"
   "ViewLog"
   "Workspace"
   ;; TODO (lbrdnk 2025-12-17) -- I've added rest of the workspace models. I believe some of those will be available for
   ;; serialization, hence we should revisit this later in the project.
   "WorkspaceInput"
   "WorkspaceInputExternal"
   "WorkspaceLog"
   "WorkspaceMerge"
   "WorkspaceMergeTransform"
   "WorkspaceGraph"
   "WorkspaceOutput"
   "WorkspaceOutputExternal"
   "WorkspaceTransform"])
