# -*- mode: yaml -*-
# copy that file as 'config.yml' and edit it to auto-initialize your fresh instance
version: 1
config:
  settings:
    email-smtp-host: localhost
    email-smtp-port: 1025
    email-smtp-username: metabase
    email-smtp-password: metabase@secret
    email-smtp-security: none
  users:
    - first_name: Egor
      last_name: Grushin
      password: Lalaept2
      email: egor@metabase.com
  databases:
    - name: External DB
      engine: postgres
      details:
        host: localhost
        port: 5455
        dbname: metabase
        user: metabase
        password: password
      settings:
        database-enable-actions: true
        database-enable-workspaces: true
        database-enable-table-editing: true
