#! /bin/bash

# Generate the resources/version.properties file
version() {
    # Skip on CircleCI since this is interactive
    if [ ! $CI ]; then
        VERSION_INFO=$(./version)
        IFS=', ' read -a info <<< ${VERSION_INFO}

        echo "Tagging uberjar with version '$VERSION_INFO'..."

        # Ok, now generate the appropriate version.properties file.
        echo "tag=${info[0]}" > resources/version.properties
        echo "hash=${info[1]}" >> resources/version.properties
        echo "branch=${info[2]}" >> resources/version.properties
        echo "date=${info[3]}" >> resources/version.properties
    fi
}

frontend() {
    echo "Running 'npm install' to download javascript dependencies..." &&
    npm install &&

    echo "Running 'webpack -p' to assemble and minify frontend assets..." &&
    ./node_modules/webpack/bin/webpack.js -p
}

sample-dataset() {
    if [ -f resources/sample-dataset.db.mv.db ]; then
        echo "Sample Dataset already generated."
    else
        echo "Running 'lein generate-sample-dataset' to generate the sample dataset..."
        lein generate-sample-dataset
    fi
}

uberjar() {
    echo "Running 'lein uberjar'..."
    lein uberjar
}

sign() {
    echo 'Signing jar...'

    UBERJAR_FILE=$(ls target/uberjar/metabase-*-standalone.jar)
    if [ ! -e "$UBERJAR_FILE" ]; then
        echo "Couldn't find standalone uberjar in target/uberjar!"
        echo "Try again when you're ready to quit playing games."
        exit 1
    fi

    JARSIGNER_ALIAS=metabase

    jarsigner $UBERJAR_FILE $JARSIGNER_ALIAS
}

all() {
    version && frontend && sample-dataset && uberjar && sign
}

# Default to running all but let someone specify one or more sub-tasks to run instead if desired
# e.g.
# ./build-uberjar                  # do everything
# ./build-uberjar version          # just update version.properties
# ./build-uberjar version uberjar  # just update version.properties and build uberjar
if [ "$1" ]; then
    for cmd in "$@"; do
        $cmd
    done
else
    all
fi
