module.exports = {
  diffingEngine: "looks-same",
  storiesFilter: [
    "DataGrid",
    "static-viz",
    "viz",
    "Patterns/Upsells",
    "^visualizations/shared",
    "^app/embed",
    "^design system",
    "^Components/Overlays/Menu Hover state",
    "^Components/Overlays/Popover Opened",
    "^Components/Overlays/Modal Opened",
    "^Components/Overlays/HoverCard Opened",
    "^Components/Utils/Paper Shadow matrix",
    "^Components/Data display/Card Shadow matrix",
    "^Components/Inputs/Checkbox (Overview|Checkbox\\.Card)$",
    "^Components/Inputs/DatePicker Dates range",
    "^Components/Inputs/Radio (Overview|Radio\\.Card)$",
    "^Components/Parameters/DatePicker",
    "^Components/Buttons/Button Compact size, custom color",
    "^Components/Overlays/Tooltip",
    "^Components/Overlays/Popover Overview",
    "^Components/Documents",
    "^Components/Feedback/Alert",
    "^Components/Feedback/Loader Overview",
    "^Components/Ask Before Using/Chip Overview",
    "^Components/Data display/Badge Sizes and variants",
    "^Components/Navigation/NavLink Overview",
    "^Components/Data display/KeyboardShortcut Overview",
    "^Components/Table",
    "^App/Palette",
    "^viz/GridMapPdfExport",
    "ParameterValueWidget",
    "^Explorations/ExplorationGroupVisualization",
  ].join("|"),
  configurations: {
    "chrome.laptop": {
      target: "chrome.docker",
      width: 1366,
      height: 768,
      deviceScaleFactor: 1,
      mobile: false,
    },
  },
  "looks-same": {
    strict: false,
    antialiasingTolerance: 9,
    tolerance: 9,
  },
};
