module.exports = {
  diffingEngine: "looks-same",
  storiesFilter: [
    "DataGrid",
    "static-viz",
    "viz",
    "Patterns/Upsells",
    "^visualizations/shared",
    "^app/embed",
    "^design system",
    "^Patterns/Overlays",
    "^Components/Inputs/DatePicker Dates range",
    "^Components/Parameters/DatePicker",
    "^Components/Buttons/Button Compact size, custom color",
    "^Components/overlays/Tooltip",
    "^Components/Documents",
    "^Components/Feedback/Alert",
    "^Components/Table",
    "^App/Palette",
    "^EmbeddingSDK/SdkQuestion/ChartTypeDropdownInner",
  ].join("|"),
  configurations: {
    "chrome.laptop": {
      target: "chrome.docker",
      width: 1366,
      height: 768,
      deviceScaleFactor: 1,
      mobile: false,
    },
  },
  "looks-same": {
    strict: false,
    antialiasingTolerance: 10,
    tolerance: 10,
  },
};
