import { DASHBOARD_ACTION } from "metabase/dashboard/components/DashboardHeader/DashboardHeaderButtonRow/action-buttons";

export const DASHBOARD_DISPLAY_ACTIONS = [
  DASHBOARD_ACTION.DASHBOARD_EMBED_ACTION,
  DASHBOARD_ACTION.REFRESH_WIDGET,
  DASHBOARD_ACTION.NIGHT_MODE_TOGGLE,
  DASHBOARD_ACTION.FULLSCREEN_TOGGLE,
];

export const DASHBOARD_EDITING_ACTIONS = [];

export const DASHBOARD_BROWSE_ACTIONS = [];

export const DEFAULT_DASHBOARD_ACTIONS = [
  //   ADD_QUESTION: "ADD_QUESTION",
  //   ADD_HEADING_OR_TEXT: "ADD_HEADING_OR_TEXT",
  //   ADD_LINK_CARD: "ADD_LINK_CARD",
  //   ADD_SECTION: "ADD_SECTION",
  //   ADD_TEMPORAL_UNIT: "ADD_TEMPORAL_UNIT",
  //   ADD_FILTER_PARAMETER: "ADD_FILTER_PARAMETER",
  //   ADD_ACTION_ELEMENT: "ADD_ACTION_ELEMENT",
  //   EXTRA_EDIT_BUTTONS_MENU: "EXTRA_EDIT_BUTTONS_MENU",
  //   COPY_ANALYTICS_DASHBOARD: "COPY_ANALYTICS_DASHBOARD",
  //   EDIT_DASHBOARD: "EDIT_DASHBOARD",
  //   DASHBOARD_SUBSCRIPTION: "DASHBOARD_SUBSCRIPTION",
  //   DASHBOARD_EMBED_ACTION: "DASHBOARD_EMBED_ACTION",
  //   REFRESH_WIDGET: "REFRESH_WIDGET",
  //   NIGHT_MODE_TOGGLE: "NIGHT_MODE_TOGGLE",
  //   FULLSCREEN_TOGGLE: "FULLSCREEN_TOGGLE",
  //   DASHBOARD_HEADER_ACTION_DIVIDER: "DASHBOARD_HEADER_ACTION_DIVIDER",
  //   DASHBOARD_BOOKMARK: "DASHBOARD_BOOKMARK",
  //   DASHBOARD_INFO: "DASHBOARD_INFO",
  //   DASHBOARD_ACTION_MENU: "DASHBOARD_ACTION_MENU",
  //   FULLSCREEN_ANALYTICS_DASHBOARD: "FULLSCREEN_ANALYTICS_DASHBOARD",
  DASHBOARD_ACTION.ADD_QUESTION,
  DASHBOARD_ACTION.ADD_HEADING_OR_TEXT,
  DASHBOARD_ACTION.ADD_LINK_CARD,
  DASHBOARD_ACTION.ADD_SECTION,
  DASHBOARD_ACTION.ADD_TEMPORAL_UNIT,
  DASHBOARD_ACTION.ADD_FILTER_PARAMETER,
  DASHBOARD_ACTION.DASHBOARD_HEADER_ACTION_DIVIDER,
  DASHBOARD_ACTION.ADD_ACTION_ELEMENT,
  DASHBOARD_ACTION.EXTRA_EDIT_BUTTONS_MENU,
  DASHBOARD_ACTION.COPY_ANALYTICS_DASHBOARD,
  DASHBOARD_ACTION.EDIT_DASHBOARD,
  DASHBOARD_ACTION.DASHBOARD_SUBSCRIPTION,
  DASHBOARD_ACTION.DASHBOARD_EMBED_ACTION,
  DASHBOARD_ACTION.REFRESH_WIDGET,
  DASHBOARD_ACTION.NIGHT_MODE_TOGGLE,
  DASHBOARD_ACTION.FULLSCREEN_TOGGLE,
  DASHBOARD_ACTION.DASHBOARD_HEADER_ACTION_DIVIDER,
  DASHBOARD_ACTION.DASHBOARD_BOOKMARK,
  DASHBOARD_ACTION.DASHBOARD_INFO,
  DASHBOARD_ACTION.DASHBOARD_ACTION_MENU,
  DASHBOARD_ACTION.FULLSCREEN_ANALYTICS_DASHBOARD,
];
