export enum PUNCTUATOR {
  Comma = ",",
  OpenParenthesis = "(",
  CloseParenthesis = ")",
  Plus = "+",
  Minus = "-",
  Multiply = "*",
  Divide = "/",
  Equal = "=",
  NotEqual = "!=",
  LessThan = "<",
  GreaterThan = ">",
  LessThanEqual = "<=",
  GreaterThanEqual = ">=",
  Not = "not",
  And = "and",
  Or = "or",
}
