var $CLJS = module.exports = {};
/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var aa,ba,da;aa=function(){var a=$CLJS.fa.navigator;return a&&(a=a.userAgent)?a:""};ba=function(a){return-1!=aa().indexOf(a)};
$CLJS.ca=function(a,b){const c=Array.prototype.slice.call(arguments),d=c.shift();if("undefined"==typeof d)throw Error("[goog.string.format] Template required");return d.replace(/%([0\- \+]*)(\d+)?(\.(\d+))?([%sfdiu])/g,function(e,f,g,l,k,m,r,v){if("%"==m)return"%";const w=c.shift();if("undefined"==typeof w)throw Error("[goog.string.format] Not enough arguments");arguments[0]=w;return $CLJS.ca.zb[m].apply(null,arguments)})};da=function(){return ba("iPhone")&&!ba("iPod")&&!ba("iPad")};
$CLJS.ea=$CLJS.ea||{};$CLJS.fa=global;$CLJS.ha="closure_uid_"+(1E9*Math.random()>>>0);$CLJS.fa=global;var ja=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)};$CLJS.ka=class{constructor(a,b){this.name=a;this.value=b}toString(){return this.name}};$CLJS.ma=new $CLJS.ka("OFF",Infinity);$CLJS.na=[$CLJS.ma,new $CLJS.ka("SHOUT",1200),new $CLJS.ka("SEVERE",1E3),new $CLJS.ka("WARNING",900),new $CLJS.ka("INFO",800),new $CLJS.ka("CONFIG",700),new $CLJS.ka("FINE",500),new $CLJS.ka("FINER",400),new $CLJS.ka("FINEST",300),new $CLJS.ka("ALL",0)];$CLJS.ca.zb={};$CLJS.ca.zb.s=function(a,b,c){return isNaN(c)||""==c||a.length>=Number(c)?a:a=-1<b.indexOf("-",0)?a+ja(" ",Number(c)-a.length):ja(" ",Number(c)-a.length)+a};
$CLJS.ca.zb.f=function(a,b,c,d,e){d=a.toString();isNaN(e)||""==e||(d=parseFloat(a).toFixed(e));let f;f=0>Number(a)?"-":0<=b.indexOf("+")?"+":0<=b.indexOf(" ")?" ":"";0<=Number(a)&&(d=f+d);if(isNaN(c)||d.length>=Number(c))return d;d=isNaN(e)?Math.abs(Number(a)).toString():Math.abs(Number(a)).toFixed(e);a=Number(c)-d.length-f.length;0<=b.indexOf("-",0)?d=f+d+ja(" ",a):(b=0<=b.indexOf("0",0)?"0":" ",d=f+ja(b,a)+d);return d};
$CLJS.ca.zb.d=function(a,b,c,d,e,f,g,l){return $CLJS.ca.zb.f(parseInt(a,10),b,c,d,0,f,g,l)};$CLJS.ca.zb.i=$CLJS.ca.zb.d;$CLJS.ca.zb.u=$CLJS.ca.zb.d;ba("Opera");ba("Trident")||ba("MSIE");ba("Edge");!ba("Gecko")||-1!=aa().toLowerCase().indexOf("webkit")&&!ba("Edge")||ba("Trident")||ba("MSIE")||ba("Edge");-1!=aa().toLowerCase().indexOf("webkit")&&!ba("Edge")&&ba("Mobile");ba("Macintosh");ba("Windows");ba("Linux")||ba("CrOS");var ia=$CLJS.fa.navigator||null;ia&&(ia.appVersion||"").indexOf("X11");ba("Android");da();ba("iPad");ba("iPod");da()||ba("iPad")||ba("iPod");aa().toLowerCase().indexOf("kaios");Date.now();