var window=global;var $CLJS=require("./cljs_env.js");require("./cljs.core.js");require("./metabase.shared.formatting.internal.numbers.js");require("./metabase.shared.formatting.internal.numbers_core.js");require("./metabase.util.js");
'use strict';var w1=function(a){return $CLJS.$G(function(b){return function(c,d,e){return $CLJS.p($CLJS.Do.g?$CLJS.Do.g(e):$CLJS.Do.call(null,e))?b.j?b.j(c,d,e):b.call(null,c,d,e):c}},a)},x1=function(a){var b=$CLJS.vk.o;var c=$CLJS.je(a);var d=$CLJS.K.h(c,$CLJS.e1);c=$CLJS.K.h(c,$CLJS.f1);if($CLJS.p($CLJS.p(d)?$CLJS.E.h(c,"currency"):d)){c=$CLJS.a1.g;d=$CLJS.yg.g(d);var e=$CLJS.pb($CLJS.Y0);d=e.g?e.g(d):e.call(null,d);c=c.call($CLJS.a1,d);c=new $CLJS.n(null,2,[$CLJS.d1,c,$CLJS.g1,c],null)}else c=
new $CLJS.n(null,1,[$CLJS.g1,2],null);b=b.call($CLJS.vk,$CLJS.G([c,a]));return $CLJS.p($CLJS.h1.g(a))?$CLJS.Cg.o($CLJS.sh.h(b,$CLJS.h1),$CLJS.g1,$CLJS.h1.g(a),$CLJS.G([$CLJS.d1,$CLJS.h1.g(a)])):b},y1=function(a,b){if(null!=a&&null!=a.og)a=a.og(a,b);else{var c=y1[$CLJS.sa(null==a?null:a)];if(null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else if(c=y1._,null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else throw $CLJS.Oa("NumberFormatter.format-number-basic",a);}return a},z1=function(a,b){var c=$CLJS.jH(a.formatToParts(b),
$CLJS.G([new $CLJS.n(null,1,[$CLJS.fi,!0],null)]));a=$CLJS.p($CLJS.se(function(d){return $CLJS.E.h($CLJS.oj.g(d),"exponentMinusSign")},c))?c:function(){var d=$CLJS.mg(function(f){return $CLJS.Zg.h($CLJS.oj.g(f),"exponentInteger")},c),e=$CLJS.I(d,0,null);d=$CLJS.I(d,1,null);return $CLJS.th.o(e,new $CLJS.P(null,1,5,$CLJS.Q,[new $CLJS.n(null,2,[$CLJS.oj,"exponentPlusSign",$CLJS.zj,"+"],null)],null),$CLJS.G([d]))}();return $CLJS.fe.h($CLJS.q,$CLJS.xg.h(function(d){var e=$CLJS.je(d);d=$CLJS.K.h(e,$CLJS.oj);
e=$CLJS.K.h(e,$CLJS.zj);switch(d){case "exponentSeparator":return"e";default:return e}},a))},A1=function(a,b){switch($CLJS.f1.g(b)){case "scientific":return function(c){return z1(a,c)};default:return function(c){return a.format(c)}}},B1=function(a,b,c,d,e){this.options=a;this.Sg=b;this.Vg=c;this.Gf=d;this.bi=e;this.A=393216;this.M=0},C1=function(a,b){return $CLJS.fe.h($CLJS.q,function(){return function e(d){return new $CLJS.Ld(null,function(){for(var f=d;;)if(f=$CLJS.y(f)){if($CLJS.ad(f)){var g=$CLJS.Rb(f),
l=$CLJS.D(g),k=$CLJS.Od(l);return function(){for(var v=0;;)if(v<l){var w=$CLJS.Pc(g,v),x=$CLJS.je(w);w=$CLJS.K.h(x,$CLJS.oj);x=$CLJS.K.h(x,$CLJS.zj);var A=new $CLJS.R(null,new $CLJS.n(null,2,["currency",null,"integer",null],null),null);A=A.g?A.g(w):A.call(null,w);$CLJS.p(A)&&(w=$CLJS.E.h(w,"integer")?b:x,k.add(w));v+=1}else return!0}()?$CLJS.Rd($CLJS.Td(k),e($CLJS.Sb(f))):$CLJS.Rd($CLJS.Td(k),null)}var m=$CLJS.z(f);m=$CLJS.je(m);var r=$CLJS.K.h(m,$CLJS.oj);m=$CLJS.K.h(m,$CLJS.zj);if($CLJS.p(function(){var v=
new $CLJS.R(null,new $CLJS.n(null,2,["currency",null,"integer",null],null),null);return v.g?v.g(r):v.call(null,r)}()))return $CLJS.Jd($CLJS.E.h(r,"integer")?b:m,e($CLJS.qc(f)));f=$CLJS.qc(f)}else return null},null)}($CLJS.jH(a.Sg.formatToParts(1),$CLJS.G([$CLJS.fi,!0])))}())},D1=function(a){var b=$CLJS.E.h($CLJS.f1.g(a),"currency")?2:null;b=new Intl.NumberFormat("en",$CLJS.Fh(w1($CLJS.Yf([$CLJS.s1,$CLJS.j1,$CLJS.m1,$CLJS.o1,$CLJS.v1,$CLJS.e1,$CLJS.n1,$CLJS.q1,$CLJS.k1,$CLJS.l1],[$CLJS.g1.h(a,b),$CLJS.p1.g(a),
$CLJS.i1.g(a),$CLJS.r1.g(a),$CLJS.E.h($CLJS.f1.g(a),"scientific")?null:$CLJS.f1.h(a,"decimal"),$CLJS.e1.g(a),!0,$CLJS.d1.h(a,b),$CLJS.E.h($CLJS.f1.g(a),"scientific")?"scientific":null,$CLJS.u1.g(a)]))));var c=$CLJS.p1.g(a);var d=$CLJS.e1.g(a);c=$CLJS.p(d)?null==c||$CLJS.E.h(c,"symbol"):d;d=A1(b,a);return new B1(a,b,c,d,$CLJS.ie)},E1=function(a,b){return D1(x1(b)).og(null,a)},H1=function(a,b){var c=$CLJS.sh.o(b,$CLJS.zK,$CLJS.G([$CLJS.f1])),d=Math.abs(a);if(0===a)return"0";if(1E3>d)return F1.h?F1.h(a,
c):F1.call(null,a,c);b=$CLJS.z($CLJS.Be(function(f){return d>=$CLJS.z(f)},G1));var e=$CLJS.I(b,0,null);b=$CLJS.I(b,1,null);return[$CLJS.q.g(function(){var f=a/e,g=$CLJS.vk.o($CLJS.G([c,new $CLJS.n(null,2,[$CLJS.d1,1,$CLJS.g1,1],null)]));return F1.h?F1.h(f,g):F1.call(null,f,g)}()),$CLJS.q.g(b)].join("")},J1=function(a,b){var c=x1(b);if($CLJS.p(I1.g(c)))b=I1.g(c);else if($CLJS.La($CLJS.h1.g(c))&&$CLJS.La($CLJS.d1.g(c))&&$CLJS.Zg.h($CLJS.f1.g(c),"currency")&&Math.abs(a)<($CLJS.E.h($CLJS.f1.g(c),"percent")?
.01:1)){b=$CLJS.Cg.j;var d=$CLJS.sh.h(c,$CLJS.g1);c=$CLJS.u1.h(c,0);b=D1(b.call($CLJS.Cg,d,$CLJS.i1,2>c?2:c))}else b=D1(c);return y1(b,a)};B1.prototype.aa=function(a,b){return new B1(this.options,this.Sg,this.Vg,this.Gf,b)};B1.prototype.Z=function(){return this.bi};
B1.prototype.og=function(a,b){a=this.Gf.g?this.Gf.g(b):this.Gf.call(null,b);var c=$CLJS.t1.g(this.options);$CLJS.p($CLJS.p(c)?$CLJS.Zg.h(c,".,"):c)&&(b=$CLJS.z(c),c=$CLJS.Mc(c),a=$CLJS.XC(a,/[\.,]/,new $CLJS.n(null,2,[",",$CLJS.p(c)?c:"",".",b],null)));$CLJS.p(this.Vg)&&(b=$CLJS.e1.g(this.options),c=$CLJS.Z0(b),a=$CLJS.XC($CLJS.XC(a,[$CLJS.kg(b)," "].join(""),c),$CLJS.kg(b),c));return a};
var I1=new $CLJS.M(null,"number-formatter","number-formatter",929788393),K1=new $CLJS.M(null,"scale","scale",-230427353),L1=new $CLJS.M(null,"negative-in-parentheses","negative-in-parentheses",-1676084141),M1=new $CLJS.M(null,"scientific","scientific",316285837);var N1=new $CLJS.n(null,1,[$CLJS.p1,"symbol"],null),O1=$CLJS.Fh(N1),G1=new $CLJS.P(null,4,5,$CLJS.Q,[new $CLJS.P(null,2,5,$CLJS.Q,[1E12,"T"],null),new $CLJS.P(null,2,5,$CLJS.Q,[1E9,"B"],null),new $CLJS.P(null,2,5,$CLJS.Q,[1E6,"M"],null),new $CLJS.P(null,2,5,$CLJS.Q,[1E3,"k"],null)],null),P1=function(){var a=$CLJS.vh.g($CLJS.ie),b=$CLJS.vh.g($CLJS.ie),c=$CLJS.vh.g($CLJS.ie),d=$CLJS.vh.g($CLJS.ie),e=$CLJS.K.j($CLJS.ie,$CLJS.kj,$CLJS.Th.v?$CLJS.Th.v():$CLJS.Th.call(null));return new $CLJS.NC($CLJS.Fg.h("metabase.shared.formatting.numbers",
"format-number-compact*"),function(f,g){f=$CLJS.je(g);return $CLJS.K.h(f,$CLJS.f1)},e,a,b,c,d)}();P1.ub(null,$CLJS.mh,function(a,b){return H1(a,b)});P1.ub(null,"percent",function(a,b){return[$CLJS.q.g(H1(100*a,b)),"%"].join("")});P1.ub(null,"currency",function(a,b){b=$CLJS.vk.o($CLJS.G([b,N1]));var c=D1(b);return 1E3>Math.abs(a)?c.og(null,a):C1(c,H1(a,b))});P1.ub(null,"scientific",function(a,b){return E1(a,$CLJS.vk.o($CLJS.G([b,new $CLJS.n(null,2,[$CLJS.g1,1,$CLJS.d1,1],null)])))});
var F1=function F1(a,b){b=$CLJS.EJ(b);var d=$CLJS.je(b);b=$CLJS.K.h(d,$CLJS.zK);var e=$CLJS.K.h(d,L1),f=$CLJS.K.h(d,$CLJS.f1),g=$CLJS.K.h(d,K1);return $CLJS.p($CLJS.p(g)?!isNaN(g):g)?(b=g*a,f=$CLJS.sh.h(d,K1),F1.h?F1.h(b,f):F1.call(null,b,f)):$CLJS.p(function(){var l=0>a;return l?e:l}())?["(",$CLJS.q.g(function(){var l=-a,k=$CLJS.Cg.j(d,L1,!1);return F1.h?F1.h(l,k):F1.call(null,l,k)}()),")"].join(""):$CLJS.p(b)?P1.h(a,x1($CLJS.sh.h(d,$CLJS.zK))):$CLJS.E.h($CLJS.yg.g(f),M1)?E1(a,d):J1(a,d)};
module.exports={compact_currency_options_js:O1,format_number:F1};