var window=global;var $CLJS=require("./cljs_env.js");require("./cljs.core.js");require("./clojure.string.js");require("./metabase.types.js");require("./schema.core.js");
'use strict';var ro,to;ro=function(a){if(null!=a&&null!=a.Kb)a=a.Kb(a);else{var b=ro[$CLJS.sa(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=ro._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw $CLJS.Oa("HasPrecondition.precondition",a);}return a};to=function(a,b,c,d){this.vb=a;this.C=b;this.l=c;this.B=d;this.A=2230716170;this.M=139264};$CLJS.uo=function(a){return new to(a,null,null,null)};$CLJS.Ll.prototype.Kb=$CLJS.ra(37,function(){return $CLJS.ue(this.Y)});
$CLJS.Rl.prototype.Kb=$CLJS.ra(36,function(){var a=this;return $CLJS.xh.h($CLJS.ue(a.Y),$CLJS.fe.h($CLJS.yh,function(){return function d(c){return new $CLJS.Ld(null,function(){for(;;){var e=$CLJS.y(c);if(e){if($CLJS.ad(e)){var f=$CLJS.Rb(e),g=$CLJS.D(f),l=$CLJS.Od(g);a:for(var k=0;;)if(k<g){var m=$CLJS.Pc(f,k),r=$CLJS.je(m);m=$CLJS.K.h(r,$CLJS.YM);r=$CLJS.K.h(r,$CLJS.Xj);m=$CLJS.p(m)?$CLJS.xh.h(m,ro($CLJS.um(r))):ro($CLJS.um(r));l.add(m);k+=1}else{f=!0;break a}return f?$CLJS.Rd($CLJS.Td(l),d($CLJS.Sb(e))):
$CLJS.Rd($CLJS.Td(l),null)}l=$CLJS.z(e);f=$CLJS.je(l);l=$CLJS.K.h(f,$CLJS.YM);f=$CLJS.K.h(f,$CLJS.Xj);return $CLJS.Jd($CLJS.p(l)?$CLJS.xh.h(l,ro($CLJS.um(f))):ro($CLJS.um(f)),d($CLJS.qc(e)))}return null}},null)}(a.options)}()))});$CLJS.bm.prototype.Kb=$CLJS.ra(35,function(){return $CLJS.ue(this.Y)});$CLJS.h=to.prototype;$CLJS.h.ga=function(a,b){return this.N(null,b,null)};
$CLJS.h.N=function(a,b,c){switch(b instanceof $CLJS.M?b.T:null){case "schemas":return this.vb;default:return $CLJS.K.j(this.l,b,c)}};$CLJS.h.oa=function(a,b,c){return $CLJS.qd(function(d,e){var f=$CLJS.I(e,0,null);e=$CLJS.I(e,1,null);return b.j?b.j(d,f,e):b.call(null,d,f,e)},c,this)};
$CLJS.h.S=function(a,b,c){return $CLJS.rg(b,function(d){return $CLJS.rg(b,$CLJS.wg,""," ","",c,d)},"#schema.core.CondPre{",", ","}",c,$CLJS.th.h(new $CLJS.P(null,1,5,$CLJS.Q,[new $CLJS.P(null,2,5,$CLJS.Q,[$CLJS.uN,this.vb],null)],null),this.l))};$CLJS.h.ia=function(){return new $CLJS.kf(this,1,new $CLJS.P(null,1,5,$CLJS.Q,[$CLJS.uN],null),$CLJS.p(this.l)?$CLJS.Wb(this.l):$CLJS.oe())};$CLJS.h.Z=function(){return this.C};$CLJS.h.ba=function(){return 1+$CLJS.D(this.l)};
$CLJS.h.X=function(){var a=this.B;return null!=a?a:this.B=a=-56613580^$CLJS.vc(this)};$CLJS.h.W=function(a,b){return null!=b&&this.constructor===b.constructor&&$CLJS.E.h(this.vb,b.vb)&&$CLJS.E.h(this.l,b.l)};$CLJS.h.ra=function(a,b){return $CLJS.fd(new $CLJS.R(null,new $CLJS.n(null,1,[$CLJS.uN,null],null),null),b)?$CLJS.sh.h($CLJS.sb($CLJS.uf.h($CLJS.ie,this),this.C),b):new to(this.vb,this.C,$CLJS.ke($CLJS.sh.h(this.l,b)),null)};
$CLJS.h.ma=function(a,b){switch(b instanceof $CLJS.M?b.T:null){case "schemas":return!0;default:return $CLJS.fd(this.l,b)}};$CLJS.h.V=function(a,b,c){return $CLJS.p($CLJS.O.h?$CLJS.O.h($CLJS.uN,b):$CLJS.O.call(null,$CLJS.uN,b))?new to(c,this.C,this.l,null):new to(this.vb,this.C,$CLJS.Cg.j(this.l,b,c),null)};$CLJS.h.$=function(){return $CLJS.y($CLJS.th.h(new $CLJS.P(null,1,5,$CLJS.Q,[new $CLJS.gd($CLJS.uN,this.vb)],null),this.l))};$CLJS.h.aa=function(a,b){return new to(this.vb,b,this.l,this.B)};
$CLJS.h.ca=function(a,b){return $CLJS.Zc(b)?this.V(null,$CLJS.Pc(b,0),$CLJS.Pc(b,1)):$CLJS.qd($CLJS.Xa,this,b)};
$CLJS.h.Da=function(){var a=this;return $CLJS.Sl($CLJS.qm,function(){return function d(c){return new $CLJS.Ld(null,function(){for(;;){var e=$CLJS.y(c);if(e){if($CLJS.ad(e)){var f=$CLJS.Rb(e),g=$CLJS.D(f),l=$CLJS.Od(g);a:for(var k=0;;)if(k<g){var m=$CLJS.Pc(f,k);m=new $CLJS.n(null,2,[$CLJS.YM,ro($CLJS.um(m)),$CLJS.Xj,m],null);l.add(m);k+=1}else{f=!0;break a}return f?$CLJS.Rd($CLJS.Td(l),d($CLJS.Sb(e))):$CLJS.Rd($CLJS.Td(l),null)}l=$CLJS.z(e);return $CLJS.Jd(new $CLJS.n(null,2,[$CLJS.YM,ro($CLJS.um(l)),
$CLJS.Xj,l],null),d($CLJS.qc(e)))}return null}},null)}(a.vb)}(),function(b){return new $CLJS.Dd(null,$CLJS.NN,new $CLJS.Dd(null,b,null,1,null),2,null)})};$CLJS.h.Ca=function(){return $CLJS.Jd($CLJS.BN,$CLJS.xg.h($CLJS.vm,this.vb))};$CLJS.h.na=$CLJS.gc;$CLJS.h.S=function(a,b){return $CLJS.Hb(b,this.Ca(null))};$CLJS.vo=$CLJS.Gm($CLJS.mo,$CLJS.ue(function(a){return $CLJS.oa(null==a?"":String(a))}),"Non-blank string");$CLJS.wo=$CLJS.Cm(function(a){return $CLJS.ui(a,$CLJS.RL)},"Valid field type");$CLJS.xo=$CLJS.Cm(function(a){return $CLJS.ui(a,$CLJS.NL)||$CLJS.ui(a,$CLJS.KK)},"Valid semantic type");$CLJS.yo=$CLJS.Gm($CLJS.po,$CLJS.Sg,"positive integer");$CLJS.zo=$CLJS.Gm($CLJS.po,$CLJS.ue($CLJS.so),"integer \x3e\x3d 0");$CLJS.Ao=$CLJS.he([$CLJS.lo,$CLJS.lo]);$CLJS.Bo=$CLJS.uo($CLJS.G([$CLJS.qo,$CLJS.mo]));