var window=global;var $CLJS=require("./cljs_env.js");require("./cljs.core.js");require("./metabase.shared.formatting.constants.js");require("./metabase.shared.formatting.internal.date_builder.js");require("./metabase.shared.formatting.internal.date_formatters.js");require("./metabase.shared.formatting.internal.date_options.js");require("./metabase.shared.util.time.js");
'use strict';var J0,K0,L0,M0,N0,O0,P0,Q0,R0,T0,U0,V0;J0=function(a){a=$CLJS.je(a);a=$CLJS.K.h(a,$CLJS.u_);return $CLJS.E.h(a,"compact")};
K0=function(a,b){return $CLJS.p(b)?function e(d){return new $CLJS.Ld(null,function(){for(;;){var f=$CLJS.y(d);if(f){if($CLJS.ad(f)){var g=$CLJS.Rb(f),l=$CLJS.D(g),k=$CLJS.Od(l);a:for(var m=0;;)if(m<l){var r=$CLJS.Pc(g,m);r="string"===typeof r?$CLJS.XC(r,/\//,b):r;k.add(r);m+=1}else{g=!0;break a}return g?$CLJS.Rd($CLJS.Td(k),e($CLJS.Sb(f))):$CLJS.Rd($CLJS.Td(k),null)}k=$CLJS.z(f);return $CLJS.Jd("string"===typeof k?$CLJS.XC(k,/\//,b):k,e($CLJS.qc(f)))}return null}},null)}(a):a};
L0=function(a){return function d(c){return new $CLJS.Ld(null,function(){for(;;){var e=$CLJS.y(c);if(e){if($CLJS.ad(e)){var f=$CLJS.Rb(e),g=$CLJS.D(f),l=$CLJS.Od(g);return function(){for(var m=0;;)if(m<g){var r=$CLJS.Pc(f,m),v=l,w=r;r=$CLJS.E.h($CLJS.c_,w)?$CLJS.e_:$CLJS.E.h(":month-full",w)?$CLJS.e_:$CLJS.E.h($CLJS.q_,w)?$CLJS.m_:$CLJS.E.h(":day-of-week-full",w)?$CLJS.m_:r;v.add(r);m+=1}else return!0}()?$CLJS.Rd($CLJS.Td(l),d($CLJS.Sb(e))):$CLJS.Rd($CLJS.Td(l),null)}var k=$CLJS.z(e);return $CLJS.Jd(function(){var m=
k;return $CLJS.E.h($CLJS.c_,m)?$CLJS.e_:$CLJS.E.h(":month-full",m)?$CLJS.e_:$CLJS.E.h($CLJS.q_,m)?$CLJS.m_:$CLJS.E.h(":day-of-week-full",m)?$CLJS.m_:k}(),d($CLJS.qc(e)))}return null}},null)}(a)};
M0=function(a){var b=$CLJS.je(a),c=$CLJS.K.h(b,$CLJS.s_);a=$CLJS.K.h(b,$CLJS.rJ);b=$CLJS.K.h(b,$CLJS.Vh);if($CLJS.p(c))return c;c=$CLJS.dv($CLJS.I_,new $CLJS.P(null,2,5,$CLJS.Q,[a,b],null));if($CLJS.p(c))return c;c=$CLJS.K.h($CLJS.H_,b);if($CLJS.p(c))return c;c=$CLJS.K.h($CLJS.v_,a);if($CLJS.p(c))return c;c=$CLJS.CJ($CLJS.pI);$CLJS.p($CLJS.DJ("metabase.shared.formatting.internal.date-formatters",c))&&$CLJS.lH("metabase.shared.formatting.internal.date-formatters",c,$CLJS.oy.o($CLJS.G(["Unrecognized date style",
new $CLJS.n(null,2,[$CLJS.rJ,a,$CLJS.Vh,b],null)])),null);return $CLJS.L_};N0=function(a){a=$CLJS.je(a);var b=$CLJS.K.h(a,$CLJS.G_),c=$CLJS.K.h(a,$CLJS.tJ);var d=$CLJS.je(a);var e=$CLJS.K.h(d,$CLJS.s_);d=$CLJS.vk.o($CLJS.G([d,$CLJS.K.h($CLJS.x_,e)]));d=M0(d);b=$CLJS.p(b)?K0(d,b):d;c=$CLJS.p(c)?$CLJS.th.h(new $CLJS.P(null,2,5,$CLJS.Q,[$CLJS.m_,", "],null),b):b;return J0(a)?L0(c):c};O0=function(a){a=$CLJS.je(a);var b=$CLJS.K.h(a,$CLJS.oj);return J0(a)&&$CLJS.Zg.h(b,"tooltip")};
P0=function(a){var b=$CLJS.je(a);a=$CLJS.K.h(b,$CLJS.uJ);var c=$CLJS.K.h(b,$CLJS.t_),d=$CLJS.K.h(b,$CLJS.xJ);a:{var e="string"===typeof c;if(e){e=$CLJS.K.h($CLJS.w_,c);if($CLJS.p(e)){b=e;break a}throw $CLJS.Jo("Unknown time format",b);}b=e}if($CLJS.p(b))return b;if($CLJS.p(c))return c;c=$CLJS.dv($CLJS.U_,new $CLJS.P(null,2,5,$CLJS.Q,[d,a],null));if($CLJS.p(c))return c;c=$CLJS.K.h($CLJS.w_,d);if($CLJS.p(c))return c;c=$CLJS.CJ($CLJS.pI);$CLJS.p($CLJS.DJ("metabase.shared.formatting.internal.date-formatters",
c))&&$CLJS.lH("metabase.shared.formatting.internal.date-formatters",c,$CLJS.oy.o($CLJS.G(["Unrecognized time style",new $CLJS.n(null,2,[$CLJS.xJ,d,$CLJS.uJ,a],null)])),null);return $CLJS.V_};
Q0=function(a){var b=$CLJS.je(a);a=$CLJS.K.h(b,$CLJS.yJ);var c=$CLJS.K.h(b,$CLJS.uJ),d=$CLJS.p(a)?N0(b):null,e=$CLJS.p(c)?P0(b):null;a=$CLJS.p($CLJS.p(d)?e:d)?$CLJS.th.o(d,new $CLJS.P(null,1,5,$CLJS.Q,[", "],null),$CLJS.G([e])):function(){if($CLJS.p(d))return d;if($CLJS.p(e))return e;var f=$CLJS.CJ($CLJS.pI);$CLJS.p($CLJS.DJ("metabase.shared.formatting.internal.date-formatters",f))&&$CLJS.lH("metabase.shared.formatting.internal.date-formatters",f,$CLJS.oy.o($CLJS.G(["Unrecognized date/time format",
b])),null);return $CLJS.L_}();return $CLJS.E_(a)};R0=function(a){var b=$CLJS.K.h($CLJS.pb($CLJS.W_),a);return $CLJS.p(b)?b:$CLJS.K.h($CLJS.wh.h($CLJS.W_,function(c){return $CLJS.fd(c,a)?c:$CLJS.Cg.j(c,a,Q0(a))}),a)};
$CLJS.S0=function(a){a=$CLJS.BD.j($CLJS.EJ(a),$CLJS.Vh,$CLJS.yg);var b=$CLJS.vk.o;var c=$CLJS.Vh.g(a);c=$CLJS.Z_.g?$CLJS.Z_.g(c):$CLJS.Z_.call(null,c);a=b.call($CLJS.vk,$CLJS.G([$CLJS.Y_,$CLJS.p(c)?new $CLJS.n(null,1,[$CLJS.uJ,"minutes"],null):null,a]));var d=$CLJS.je(a);b=$CLJS.K.h(d,$CLJS.zK);c=$CLJS.K.h(d,$CLJS.X_);var e=$CLJS.K.h(d,$CLJS.oj);a=$CLJS.K.h(d,$CLJS.Vh);d=$CLJS.sh.o(d,$CLJS.zK,$CLJS.G([$CLJS.X_]));d=$CLJS.p($CLJS.a0.g?$CLJS.a0.g(a):$CLJS.a0.call(null,a))?$CLJS.Cg.j(d,$CLJS.yJ,!1):
d;e=$CLJS.E.h(e,"tooltip")?$CLJS.Cg.j(d,$CLJS.u_,"condensed"):d;b=$CLJS.p($CLJS.p(b)?b:c)?$CLJS.Cg.j(e,$CLJS.u_,"compact"):e;return $CLJS.La($CLJS.$_.g?$CLJS.$_.g(a):$CLJS.$_.call(null,a))?$CLJS.sh.h(b,$CLJS.tJ):b};
T0=function(a,b){b=$CLJS.S0(b);var c=$CLJS.I0.h(a,b);if($CLJS.p($CLJS.E0.o($CLJS.G([c])))){c=$CLJS.D0.o($CLJS.G([c,b]));a=$CLJS.I(c,0,null);c=$CLJS.I(c,1,null);var d=$CLJS.je(b);d=$CLJS.K.h(d,$CLJS.u_);var e=new $CLJS.R(null,new $CLJS.n(null,2,["compact",null,"condensed",null],null),null);d=e.g?e.g(d):e.call(null,d);$CLJS.La(d)||$CLJS.La($CLJS.H0.o($CLJS.G([a,c])))?(b=O0(b)?$CLJS.O_:$CLJS.P_,b=[$CLJS.q.g(b(a))," – ",$CLJS.q.g(b(c))].join("")):b=$CLJS.La($CLJS.G0.o($CLJS.G([a,c])))?[$CLJS.q.g((O0(b)?
$CLJS.M_:$CLJS.N_)(a))," – ",$CLJS.q.g((O0(b)?$CLJS.O_:$CLJS.P_)(c))].join(""):[$CLJS.q.g((O0(b)?$CLJS.M_:$CLJS.N_)(a))," – ",$CLJS.q.g($CLJS.E_(new $CLJS.P(null,3,5,$CLJS.Q,[$CLJS.d_,", ",$CLJS.ph],null))(c))].join("")}else b=$CLJS.q.g(a);return b};
$CLJS.W0=function(a,b){b=$CLJS.S0(b);var c=$CLJS.je(b),d=$CLJS.K.h(c,U0),e=$CLJS.K.h(c,V0),f=$CLJS.K.h(c,$CLJS.oj),g=$CLJS.K.h(c,$CLJS.Vh);b=$CLJS.I0.h(a,c);if($CLJS.p(d))switch(g instanceof $CLJS.M?g.T:null){case "hour-of-day":return(0,$CLJS.R_)(b);case "day-of-week":return(0,$CLJS.S_)(b);default:throw $CLJS.Jo("is-exclude option is only compatible with hour-of-day and day-of-week units",new $CLJS.n(null,1,[$CLJS.ij,c],null));}else{(d=$CLJS.E.h(g,$CLJS.vJ))?(d=new $CLJS.R(null,new $CLJS.n(null,2,
["tooltip",null,"cell",null],null),null),f=d.g?d.g(f):d.call(null,f),e=$CLJS.p(f)?$CLJS.La(e):f):e=d;if($CLJS.p(e))return T0(a,c);a=R0(c);return a.g?a.g(b):a.call(null,b)}};U0=new $CLJS.M(null,"is-exclude","is-exclude",1738462979);V0=new $CLJS.M(null,"no-range","no-range",-1511420040);var X0=new $CLJS.n(null,3,[$CLJS.wJ,$CLJS.E_(new $CLJS.P(null,3,5,$CLJS.Q,[$CLJS.ph,"-",$CLJS.i_],null)),$CLJS.Nu,$CLJS.E_(new $CLJS.P(null,4,5,$CLJS.Q,["Q",$CLJS.Nu,"-",$CLJS.ph],null)),$CLJS.wK,$CLJS.Q_],null);
module.exports={format_for_parameter:function(a,b){b=$CLJS.S0(b);var c=$CLJS.I0.h(a,b);if($CLJS.La($CLJS.E0.o($CLJS.G([c]))))return $CLJS.q.g(a);a=$CLJS.Vh.g(b);a=X0.g?X0.g(a):X0.call(null,a);if($CLJS.p(a))return a.g?a.g(c):a.call(null,c);c=$CLJS.D0.o($CLJS.G([c,b]));b=$CLJS.I(c,0,null);c=$CLJS.I(c,1,null);return $CLJS.p($CLJS.F0.o($CLJS.G([b,c])))?(0,$CLJS.Q_)(b):[$CLJS.q.g((0,$CLJS.Q_)(b)),"~",$CLJS.q.g((0,$CLJS.Q_)(c))].join("")},format_range_with_unit:T0,format_datetime_with_unit:$CLJS.W0};