export {
  type RegisteredVisualization,
  type SettingWidgetLoader,
  type VisualizationComponentLoader,
  canSavePng,
  getDefaultSize,
  getIconForVisualizationType,
  getMaxDimensionsSupported,
  getMaxMetricsSupported,
  getSettingWidgetComponent,
  getVisualization,
  getVisualizationComponent,
  getVisualizationRaw,
  getVisualizationTransformed,
  isCartesianChart,
  loadSettingWidgets,
  loadVisualizationComponents,
  prefetchVisualizationComponent,
  registerSettingWidgetLoaders,
  registerVisualization,
  setDefaultVisualization,
  visualizations,
} from "./lib/registry";
export { extractRemappedColumns, extractRemappings } from "./lib/remapping";
