export const FIELD_PRIORITY = [
  "type/Boolean",
  "type/Date",
  "type/DateTime",
  "type/DateTimeWithTZ",
  "type/DateTimeWithLocalTZ",
  "type/DateTimeWithZoneOffset",
  "type/DateTimeWithZoneID",
  "list",
  "type/Integer",
  "type/Float",
  "type/Category",
  "type/PK",
  "type/FK",
  "type/Text",
];
