// Produces corpus artifacts. Touches no database and no Metabase instance.
//
//   node generate.ts golden [--source ../scenarios/corpus/northwind.json] [--out ../artifacts/golden]
//   node generate.ts scale --data-scale 1000 [--seed 42] [--out ../artifacts/scale-1000]
//
// Output directory:
//   corpus.json    — entities to create, consumed by apply.ts
//   warehouse.sql  — Postgres DDL for the warehouse the corpus queries (empty tables + comments).
//                    Apply it to any Postgres, then point apply.ts at that database.
//
// Scale tiers follow dev.search-perf's multipliers (cards 1x, tables 1x, dashboards 0.3x, collections
// 0.1x, models 0.1x, metrics/documents 0.05x, segments/measures 0.02x). Same seed => byte-identical
// output. Actions, extra databases, users and groups from search-perf are not generated.
import { join } from "node:path";
import {
  type Corpus, type EntityDef, type TableDef, type CollectionDef,
  cardTable, corpusItems, fail, isCardLike, parseArgs, readJson, validateCorpus, writeJson, writeText,
} from "./lib.ts";

const HERE = import.meta.dirname;
const args = parseArgs(process.argv.slice(2));
const mode = args._[0];

// ------------------------------------------------------------------------------------------ SQL

const sqlString = (s: string) => `'${s.replaceAll("'", "''")}'`;
const sqlIdent = (s: string) => (/^[a-z_][a-z0-9_]*$/.test(s) ? s : `"${s.replaceAll('"', '""')}"`);

function warehouseSql(c: Corpus): string {
  const lines = [
    `-- Warehouse for corpus ${c.corpusId}. Generated by corpus-gen/generate.ts; do not edit.`,
    `-- Empty tables: Metabase only needs the schema to sync. Re-running drops and recreates the schema.`,
    `DROP SCHEMA IF EXISTS ${sqlIdent(c.schema)} CASCADE;`,
    `CREATE SCHEMA ${sqlIdent(c.schema)};`,
    "",
  ];
  for (const t of c.tables) {
    const q = `${sqlIdent(c.schema)}.${sqlIdent(t.name)}`;
    const cols = t.columns.map((col) => `  ${sqlIdent(col.name)} ${col.type}`).join(",\n");
    lines.push(`CREATE TABLE ${q} (\n${cols}\n);`);
    if (t.description) lines.push(`COMMENT ON TABLE ${q} IS ${sqlString(t.description)};`);
  }
  return lines.join("\n") + "\n";
}

// --------------------------------------------------------------------------------------- golden

function golden(): void {
  const source = args.source ?? join(HERE, "../scenarios/corpus/northwind.json");
  const out = args.out ?? join(HERE, "../artifacts/golden");
  const c = readJson<Corpus>(source);
  // Resolve default tables so apply.ts needs no knowledge of collection defaults.
  const entities = c.entities.map((e) => (isCardLike(e.model) ? { ...e, table: cardTable(c, e) } : e));
  const { collectionDefaultTable: _, ...rest } = c;
  emit(out, { ...rest, entities });
}

// ---------------------------------------------------------------------------------------- scale

/** mulberry32 — small, fast, deterministic. */
function prng(seed: number) {
  let a = seed >>> 0;
  const next = () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
  const pick = <T>(xs: readonly T[]): T => xs[Math.floor(next() * xs.length)];
  return { next, pick };
}

const V = {
  domains: ["sales", "finance", "marketing", "product", "support", "logistics", "people", "growth", "risk", "ops", "partners", "pricing"],
  measures: ["Net revenue", "Orders", "Active users", "Refunds", "Gross margin", "Conversion rate", "Ticket volume", "Shipping cost",
    "Churn rate", "Signups", "Average order value", "Inventory on hand", "Ad spend", "Headcount", "Chargebacks", "Page views",
    "Returns", "Retention", "Resolution time", "Units sold", "Discount usage", "Invoices overdue", "Trial conversions", "NPS"],
  dims: ["by country", "by channel", "by product category", "by campaign", "by warehouse", "by carrier", "by plan", "by region",
    "by device", "by cohort", "by sales rep", "by team", "by payment method", "by store", "by supplier", "by segment"],
  windows: ["daily", "weekly", "monthly", "quarterly", "year to date", "last 30 days", "last 12 months", "trailing 90 days"],
  scopes: ["EMEA", "North America", "APAC", "Germany", "Poland", "Japan", "enterprise accounts", "SMB", "new customers",
    "returning customers", "mobile app", "web shop", "wholesale", "marketplace"],
  boards: ["overview", "deep-dive", "health", "tracker", "review", "scorecard", "pulse", "monitor"],
  docTopics: ["runbook", "definitions", "postmortem", "planning notes", "onboarding guide", "FAQ", "retro", "spec"],
  colTypes: ["bigint", "text", "numeric(12,2)", "timestamptz", "boolean", "int", "date"],
  colNames: ["id", "created_at", "amount", "status", "country", "channel", "customer_id", "quantity", "category", "updated_at", "region", "score"],
};

function scale(): void {
  const dataScale = Number(args["data-scale"]);
  if (!Number.isInteger(dataScale) || dataScale < 1) fail("--data-scale <positive int> is required");
  const seed = Number(args.seed ?? 42);
  const out = args.out ?? join(HERE, `../artifacts/scale-${dataScale}`);
  const r = prng(seed);
  const n = (mult: number) => Math.max(1, Math.floor(dataScale * mult));
  const pad = (i: number) => String(i).padStart(5, "0");

  const tables: TableDef[] = Array.from({ length: n(1.0) }, (_, i) => {
    const domain = r.pick(V.domains);
    const cols = new Set<string>(["id"]);
    while (cols.size < 5) cols.add(r.pick(V.colNames));
    return {
      key: `table/t-${pad(i)}`,
      name: `${domain}_${r.pick(["fct", "dim", "stg", "agg"])}_${pad(i)}`,
      description: r.next() < 0.5 ? `${r.pick(V.measures)} ${r.pick(V.dims)} for ${r.pick(V.scopes)}.` : undefined,
      columns: [...cols].map((name) => ({ name, type: name === "id" ? "bigint" : r.pick(V.colTypes) })),
    };
  });

  // collections[0] is restricted so permission filtering is exercised at scale too.
  // (The name mixes two random domains, e.g. "Sinance": kept because fixing it changes the RNG stream.)
  const collections: CollectionDef[] = Array.from({ length: n(0.1) }, (_, i) => ({
    key: `collection/c-${pad(i)}`,
    name: `${r.pick(V.domains)[0].toUpperCase()}${r.pick(V.domains).slice(1)} ${r.pick(V.scopes)} ${pad(i)}`,
    ...(i === 0 ? { restricted: true } : {}),
  }));

  const coll = () => r.pick(collections).key;
  const tbl = () => r.pick(tables).key;
  const title = () => `${r.pick(V.measures)} ${r.pick(V.dims)}, ${r.pick(V.windows)}`;
  const desc = () => (r.next() < 0.6 ? `${r.pick(V.measures)} ${r.pick(V.dims)} for ${r.pick(V.scopes)}, ${r.pick(V.windows)}.` : undefined);

  const entities: EntityDef[] = [];
  const add = (model: EntityDef["model"], count: number, make: (i: number) => Omit<EntityDef, "key" | "model">) => {
    for (let i = 0; i < count; i++) entities.push({ key: `${model}/${model[0]}-${pad(i)}`, model, ...make(i) });
  };
  add("card", n(1.0), (i) => ({ name: `${title()} #${pad(i)}`, description: desc(), collection: coll(), table: tbl() }));
  add("dataset", n(0.1), (i) => ({ name: `${r.pick(V.measures)} model — ${r.pick(V.scopes)} #${pad(i)}`, description: desc(), collection: coll(), table: tbl() }));
  add("metric", n(0.05), (i) => ({ name: `${r.pick(V.measures)} (${r.pick(V.scopes)}) #${pad(i)}`, description: desc(), collection: coll(), table: tbl() }));
  add("dashboard", n(0.3), (i) => ({ name: `${r.pick(V.domains)} ${r.pick(V.boards)} — ${r.pick(V.scopes)} #${pad(i)}`, description: desc(), collection: coll() }));
  add("document", n(0.05), (i) => ({ name: `${r.pick(V.domains)} ${r.pick(V.docTopics)} #${pad(i)}`, body: `${desc() ?? title()} Owner: ${r.pick(V.domains)} team.`, collection: coll() }));
  add("segment", n(0.02), (i) => ({ name: `${r.pick(V.scopes)} ${r.pick(V.measures).toLowerCase()} segment #${pad(i)}`, description: desc(), table: tbl() }));
  add("measure", n(0.02), (i) => ({ name: `Total ${r.pick(V.measures).toLowerCase()} #${pad(i)}`, description: desc(), table: tbl() }));

  emit(out, {
    corpusId: `scale-${dataScale}-seed-${seed}`,
    comment: "Synthetic scale corpus for latency and agreement metrics. Not labelled — do not use for quality.",
    seed, dataScale,
    database: { key: "database/scale-warehouse", name: `Scale warehouse ${dataScale}` },
    schema: `scale_${dataScale}`,
    tables, collections, entities,
  });
}

// ----------------------------------------------------------------------------------------- emit

function emit(out: string, c: Corpus): void {
  const errs = validateCorpus(c);
  if (errs.length) fail(`generated corpus invalid:\n  ${errs.slice(0, 20).join("\n  ")}`);
  writeJson(join(out, "corpus.json"), c);
  writeText(join(out, "warehouse.sql"), warehouseSql(c));
  const counts = Object.entries(Object.groupBy(c.entities, (e) => e.model)).map(([m, v]) => `${m}=${v!.length}`);
  console.log(`${c.corpusId}: tables=${c.tables.length} collections=${c.collections.length} ${counts.join(" ")}`);
  console.log(`  corpus items (database, tables, collections, entities): ${corpusItems(c).length}`);
  console.log(`  wrote ${out}/corpus.json, ${out}/warehouse.sql`);
}

if (mode === "golden") golden();
else if (mode === "scale") scale();
else fail("usage: node generate.ts golden|scale [options]  (see header comment)");
