export const ENTERPRISE_PLUGIN_NAME_MAPPING = {
  database_routing: "metabase-enterprise/database_routing",
  snippets: "metabase-enterprise/snippets",
  embedding_iframe_sdk_setup: "metabase-enterprise/embedding_iframe_sdk_setup",
  settings: "metabase-enterprise/settings",
  model_persistence: "metabase-enterprise/model_persistence",
  comments: "metabase-enterprise/comments",
  whitelabel: "metabase-enterprise/whitelabel",
  sandboxes: "metabase-enterprise/sandboxes",
  clean_up: "metabase-enterprise/clean_up",
  tools: "metabase-enterprise/tools",
  advanced_permissions: "metabase-enterprise/advanced_permissions",
  sharing: "metabase-enterprise/sharing",
  metabot: "metabase-enterprise/metabot",
  rich_text_editing: "metabase-enterprise/rich_text_editing",
  "ai-entity-analysis": "metabase-enterprise/ai-entity-analysis",
  license: "metabase-enterprise/license",
  user_provisioning: "metabase-enterprise/user_provisioning",
  application_permissions: "metabase-enterprise/application_permissions",
  auth: "metabase-enterprise/auth",
  "smtp-override": "metabase-enterprise/smtp-override",
  "ai-sql-fixer": "metabase-enterprise/ai-sql-fixer",
  embedding: "metabase-enterprise/embedding",
  admin: "metabase-enterprise/admin",
  dependencies: "metabase-enterprise/dependencies",
  feature_level_permissions: "metabase-enterprise/feature_level_permissions",
  shared: "metabase-enterprise/shared",
  transforms: "metabase-enterprise/transforms",
  "transforms-python": "metabase-enterprise/transforms-python",
  remote_sync: "metabase-enterprise/remote_sync",
  public: "metabase-enterprise/public",
  support: "metabase-enterprise/support",
  upload_management: "metabase-enterprise/upload_management",
  "public-sharing": "metabase-enterprise/public-sharing",
  embedding_iframe_sdk: "metabase-enterprise/embedding_iframe_sdk",
  api: "metabase-enterprise/api",
  "table-editing": "metabase-enterprise/table-editing",
  resource_downloads: "metabase-enterprise/resource_downloads",
  browse: "metabase-enterprise/browse",
  documents: "metabase-enterprise/documents",
  semantic_search: "metabase-enterprise/semantic_search",
  database_replication: "metabase-enterprise/database_replication",
  library: "metabase-enterprise/data-studio/library",
  caching: "metabase-enterprise/caching",
  group_managers: "metabase-enterprise/group_managers",
  collections: "metabase-enterprise/collections",
  audit_app: "metabase-enterprise/audit_app",
  content_translation: "metabase-enterprise/content_translation",
  "embedding-sdk": "metabase-enterprise/embedding-sdk",
  entities: "metabase-enterprise/entities",
  google_drive: "metabase-enterprise/google_drive",
  content_verification: "metabase-enterprise/content_verification",
  moderation: "metabase-enterprise/moderation",
  tenants: "metabase-enterprise/tenants",
  workspaces: "metabase-enterprise/data-studio/workspaces",

  // Embedding SDK specific plugins
  sdk_notifications: "embedding-sdk-ee/notifications",
};

export type ENTERPRISE_PLUGIN_NAME =
  keyof typeof ENTERPRISE_PLUGIN_NAME_MAPPING;
