import userEvent from "@testing-library/user-event";

import {
  findRequests,
  setupPropertiesEndpoints,
  setupSettingsEndpoints,
  setupUpdateSettingEndpoint,
} from "__support__/server-mocks";
import { mockSettings } from "__support__/settings";
import { renderWithProviders, screen, waitFor } from "__support__/ui";
import { createMockState } from "metabase/redux/store/mocks";
import { createMockSettings } from "metabase-types/api/mocks";

import { McpAppsSettings } from "./McpAppsSettings";

const setup = async ({
  commonOrigins = [],
  customOrigins = "",
  enabled = true,
}: {
  commonOrigins?: string[];
  customOrigins?: string;
  enabled?: boolean;
} = {}) => {
  const settings = createMockSettings({
    "mcp-enabled?": enabled,
    "mcp-apps-cors-enabled-clients": commonOrigins,
    "mcp-apps-cors-custom-origins": customOrigins,
  });

  setupPropertiesEndpoints(settings);
  setupSettingsEndpoints([]);
  setupUpdateSettingEndpoint();

  renderWithProviders(<McpAppsSettings />, {
    storeInitialState: createMockState({
      settings: mockSettings(settings),
    }),
  });

  await screen.findByText("MCP server");
};

describe("McpAppsSettings", () => {
  it("shows a docs link for the MCP server", async () => {
    await setup();

    expect(screen.getByRole("link", { name: "Learn more" })).toHaveAttribute(
      "href",
      "https://www.metabase.com/docs/latest/ai/mcp.html",
    );
  });

  it("can toggle the MCP server", async () => {
    await setup();

    await userEvent.click(screen.getByRole("switch", { name: "MCP server" }));

    const puts = await findRequests("PUT");
    expect(puts).toHaveLength(1);
    expect(puts[0].url).toContain("/setting/mcp-enabled%3F");
    expect(puts[0].body).toEqual({ value: false });
  });

  it("should show all MCP client toggles", async () => {
    await setup();

    expect(
      await screen.findByText("Show inline charts in these MCP clients"),
    ).toBeInTheDocument();

    expect(
      await screen.findByText(
        "Select which MCP clients can display inline charts generated by Metabase. Their sandbox domains will be automatically added to the CORS allowlist.",
      ),
    ).toBeInTheDocument();

    expect(
      await screen.findByRole("switch", { name: "Claude" }),
    ).toBeInTheDocument();
    expect(
      await screen.findByRole("switch", { name: "Cursor and VS Code" }),
    ).toBeInTheDocument();
    expect(
      await screen.findByRole("switch", { name: "ChatGPT" }),
    ).toBeInTheDocument();
  });

  it("can toggle all MCP clients on", async () => {
    await setup();

    await userEvent.click(await screen.findByLabelText("Claude"));
    await userEvent.click(await screen.findByLabelText("Cursor and VS Code"));
    await userEvent.click(await screen.findByLabelText("ChatGPT"));

    const puts = await findRequests("PUT");
    expect(puts).toHaveLength(3);

    expect(puts[0].body).toEqual({ value: ["claude"] });
    expect(puts[1].body).toEqual({ value: ["claude", "cursor-vscode"] });
    expect(puts[2].body).toEqual({
      value: ["claude", "cursor-vscode", "chatgpt"],
    });
  });

  it("shows 'Install in Cursor' link only when the Cursor and VS Code switch is enabled", async () => {
    await setup();

    expect(
      screen.queryByRole("link", { name: "Install in Cursor" }),
    ).not.toBeInTheDocument();

    await userEvent.click(
      await screen.findByRole("switch", { name: "Cursor and VS Code" }),
    );

    expect(
      await screen.findByRole("link", { name: "Install in Cursor" }),
    ).toBeInTheDocument();
  });

  it("updates custom inline chart origins on blur", async () => {
    await setup({ customOrigins: "https://librechat.example.com" });

    const input = await screen.findByPlaceholderText("https://*.example.com");

    await waitFor(() => {
      expect(input).toHaveValue("https://librechat.example.com");
    });

    await userEvent.clear(input);

    // MCP client custom origins are separated by spaces
    await userEvent.type(
      input,
      "https://librechat.example.com https://openwebui.example.com",
    );

    await userEvent.tab();

    const puts = await findRequests("PUT");
    expect(puts).toHaveLength(1);

    const [{ url, body }] = puts;
    expect(url).toContain("/setting/mcp-apps-cors-custom-origins");

    expect(body).toEqual({
      value: "https://librechat.example.com https://openwebui.example.com",
    });
  });

  it("hides MCP client configuration when the MCP server is off", async () => {
    await setup({ enabled: false });

    expect(screen.queryByLabelText("Claude")).not.toBeInTheDocument();
    expect(
      screen.queryByPlaceholderText("https://*.example.com"),
    ).not.toBeInTheDocument();
  });
});
