export const enginesConfig = new Map<string, { placeholder: string }>([
  [
    "athena",
    {
      placeholder: "jdbc:athena://WorkGroup=primary;Region=us-east-1;",
    },
  ],
  [
    "bigquery-cloud-sdk",
    {
      placeholder:
        "jdbc:bigquery://https://www.googleapis.com/bigquery/v2:443;ProjectId=MyBigQueryProject;OAuthType=1;",
    },
  ],
  [
    "clickhouse",
    {
      placeholder: "jdbc:clickhouse:https://localhost:8443?ssl=true",
    },
  ],
  [
    "druid",
    {
      placeholder:
        "jdbc:avatica:remote:url=http://localhost:8888/druid/v2/sql/avatica/;transparent_reconnection=true",
    },
  ],
  [
    "druid-jdbc",
    {
      placeholder:
        "jdbc:avatica:remote:url=http://localhost:8888/druid/v2/sql/avatica/;transparent_reconnection=true",
    },
  ],
  [
    "databricks",
    {
      placeholder:
        "jdbc:databricks://127.0.0.1:8123;httpPath=/sql/1.0/endpoints/abc;OAuthSecret=1234567890;OAuth2ClientId=xyz",
    },
  ],
  [
    "mysql",
    {
      placeholder: "jdbc:mysql://user:pass@host:3306/dbname?ssl=true",
    },
  ],
  [
    "oracle",
    {
      placeholder:
        "jdbc:oracle:thin:@mydbhost:1521/mydbservice?ssl_server_cert_dn=ServerDN",
    },
  ],
  [
    "postgres",
    {
      placeholder: "jdbc:postgresql://localhost:5432/mydb",
    },
  ],
  [
    "presto-jdbc",
    {
      placeholder:
        "jdbc:presto://host:1234/sample-catalog/sample-schema?SSL=true&SSLTrustStorePassword=1234",
    },
  ],
  [
    "redshift",
    {
      placeholder:
        "jdbc:redshift://examplecluster.abc123xyz789.us-west-2.redshift.amazonaws.com:5439/dev",
    },
  ],
  [
    "snowflake",
    {
      placeholder:
        "snowflake://example.snowflakecomputing.com/?db=maindb&warehouse=mainwarehouse",
    },
  ],
  [
    "sparksql",
    {
      placeholder: "jdbc:sparksql:Server=127.0.0.1;",
    },
  ],
  [
    "sqlite",
    {
      placeholder: "jdbc:sqlite:///C:/path/to/database.db",
    },
  ],
  [
    "sqlserver",
    {
      placeholder: "jdbc:sqlserver://mydbhost:1433;databaseName=mydb",
    },
  ],
  [
    "starburst",
    {
      placeholder:
        "jdbc:trino://starburst.example.com:43011/hive/sales?user=test&password=secret&SSL=true&roles=system:myrole",
    },
  ],
  [
    "vertica",
    {
      placeholder:
        "jdbc:trino://starburst.example.com:43011/hive/sales?user=test&password=secret&SSL=true&roles=system:myrole",
    },
  ],
]);
