CREATE TABLE table_test_plan(name string, sub_region string, region string);
INSERT INTO table_test_plan VALUES ('Afghanistan', 'Southern Asia', 'Asia');
INSERT INTO table_test_plan VALUES ('Åland Islands', 'Northern Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('Albania', 'Southern Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('Algeria', 'Northern Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('American Samoa', 'Polynesia', 'Oceania');
INSERT INTO table_test_plan VALUES ('Andorra', 'Southern Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('Angola', 'Middle Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Anguilla', 'Caribbean', 'Americas');
INSERT INTO table_test_plan VALUES ('Antarctica', '', '');
INSERT INTO table_test_plan VALUES ('Antigua and Barbuda', 'Caribbean', 'Americas');
INSERT INTO table_test_plan VALUES ('Argentina', 'South America', 'Americas');
INSERT INTO table_test_plan VALUES ('Armenia', 'Western Asia', 'Asia');
INSERT INTO table_test_plan VALUES ('Aruba', 'Caribbean', 'Americas');
INSERT INTO table_test_plan VALUES ('Australia', 'Australia and New Zealand', 'Oceania');
INSERT INTO table_test_plan VALUES ('Austria', 'Western Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('Azerbaijan', 'Western Asia', 'Asia');
INSERT INTO table_test_plan VALUES ('Bahamas', 'Caribbean', 'Americas');
INSERT INTO table_test_plan VALUES ('Bahrain', 'Western Asia', 'Asia');
INSERT INTO table_test_plan VALUES ('Bangladesh', 'Southern Asia', 'Asia');
INSERT INTO table_test_plan VALUES ('Barbados', 'Caribbean', 'Americas');
INSERT INTO table_test_plan VALUES ('Belarus', 'Eastern Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('Belgium', 'Western Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('Belize', 'Central America', 'Americas');
INSERT INTO table_test_plan VALUES ('Benin', 'Western Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Bermuda', 'Northern America', 'Americas');
INSERT INTO table_test_plan VALUES ('Bhutan', 'Southern Asia', 'Asia');
INSERT INTO table_test_plan VALUES ('Bolivia (Plurinational State of)', 'South America', 'Americas');
INSERT INTO table_test_plan VALUES ('Bonaire, Sint Eustatius and Saba', 'Caribbean', 'Americas');
INSERT INTO table_test_plan VALUES ('Bosnia and Herzegovina', 'Southern Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('Botswana', 'Southern Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Bouvet Island', '', '');
INSERT INTO table_test_plan VALUES ('Brazil', 'South America', 'Americas');
INSERT INTO table_test_plan VALUES ('British Indian Ocean Territory', '', '');
INSERT INTO table_test_plan VALUES ('Brunei Darussalam', 'South-Eastern Asia', 'Asia');
INSERT INTO table_test_plan VALUES ('Bulgaria', 'Eastern Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('Burkina Faso', 'Western Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Burundi', 'Eastern Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Cambodia', 'South-Eastern Asia', 'Asia');
INSERT INTO table_test_plan VALUES ('Cameroon', 'Middle Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Canada', 'Northern America', 'Americas');
INSERT INTO table_test_plan VALUES ('Cabo Verde', 'Western Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Cayman Islands', 'Caribbean', 'Americas');
INSERT INTO table_test_plan VALUES ('Central African Republic', 'Middle Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Chad', 'Middle Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Chile', 'South America', 'Americas');
INSERT INTO table_test_plan VALUES ('China', 'Eastern Asia', 'Asia');
INSERT INTO table_test_plan VALUES ('Christmas Island', '', '');
INSERT INTO table_test_plan VALUES ('Cocos (Keeling) Islands', '', '');
INSERT INTO table_test_plan VALUES ('Colombia', 'South America', 'Americas');
INSERT INTO table_test_plan VALUES ('Comoros', 'Eastern Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Congo', 'Middle Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Congo (Democratic Republic of the)', 'Middle Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Cook Islands', 'Polynesia', 'Oceania');
INSERT INTO table_test_plan VALUES ('Costa Rica', 'Central America', 'Americas');
INSERT INTO table_test_plan VALUES ('Côte dIvoire', 'Western Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Croatia', 'Southern Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('Cuba', 'Caribbean', 'Americas');
INSERT INTO table_test_plan VALUES ('Curaçao', 'Caribbean', 'Americas');
INSERT INTO table_test_plan VALUES ('Cyprus', 'Western Asia', 'Asia');
INSERT INTO table_test_plan VALUES ('Czech Republic', 'Eastern Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('Denmark', 'Northern Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('Djibouti', 'Eastern Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Dominica', 'Caribbean', 'Americas');
INSERT INTO table_test_plan VALUES ('Dominican Republic', 'Caribbean', 'Americas');
INSERT INTO table_test_plan VALUES ('Ecuador', 'South America', 'Americas');
INSERT INTO table_test_plan VALUES ('Egypt', 'Northern Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('El Salvador', 'Central America', 'Americas');
INSERT INTO table_test_plan VALUES ('Equatorial Guinea', 'Middle Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Eritrea', 'Eastern Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Estonia', 'Northern Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('Ethiopia', 'Eastern Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Falkland Islands (Malvinas)', 'South America', 'Americas');
INSERT INTO table_test_plan VALUES ('Faroe Islands', 'Northern Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('Fiji', 'Melanesia', 'Oceania');
INSERT INTO table_test_plan VALUES ('Finland', 'Northern Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('France', 'Western Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('French Guiana', 'South America', 'Americas');
INSERT INTO table_test_plan VALUES ('French Polynesia', 'Polynesia', 'Oceania');
INSERT INTO table_test_plan VALUES ('French Southern Territories', '', '');
INSERT INTO table_test_plan VALUES ('Gabon', 'Middle Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Gambia', 'Western Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Georgia', 'Western Asia', 'Asia');
INSERT INTO table_test_plan VALUES ('Germany', 'Western Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('Ghana', 'Western Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Gibraltar', 'Southern Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('Greece', 'Southern Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('Greenland', 'Northern America', 'Americas');
INSERT INTO table_test_plan VALUES ('Grenada', 'Caribbean', 'Americas');
INSERT INTO table_test_plan VALUES ('Guadeloupe', 'Caribbean', 'Americas');
INSERT INTO table_test_plan VALUES ('Guam', 'Micronesia', 'Oceania');
INSERT INTO table_test_plan VALUES ('Guatemala', 'Central America', 'Americas');
INSERT INTO table_test_plan VALUES ('Guernsey', 'Northern Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('Guinea', 'Western Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Guinea-Bissau', 'Western Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Guyana', 'South America', 'Americas');
INSERT INTO table_test_plan VALUES ('Haiti', 'Caribbean', 'Americas');
INSERT INTO table_test_plan VALUES ('Heard Island and McDonald Islands', '', '');
INSERT INTO table_test_plan VALUES ('Holy See', 'Southern Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('Honduras', 'Central America', 'Americas');
INSERT INTO table_test_plan VALUES ('Hong Kong', 'Eastern Asia', 'Asia');
INSERT INTO table_test_plan VALUES ('Hungary', 'Eastern Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('Iceland', 'Northern Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('India', 'Southern Asia', 'Asia');
INSERT INTO table_test_plan VALUES ('Indonesia', 'South-Eastern Asia', 'Asia');
INSERT INTO table_test_plan VALUES ('Iran (Islamic Republic of)', 'Southern Asia', 'Asia');
INSERT INTO table_test_plan VALUES ('Iraq', 'Western Asia', 'Asia');
INSERT INTO table_test_plan VALUES ('Ireland', 'Northern Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('Isle of Man', 'Northern Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('Israel', 'Western Asia', 'Asia');
INSERT INTO table_test_plan VALUES ('Italy', 'Southern Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('Jamaica', 'Caribbean', 'Americas');
INSERT INTO table_test_plan VALUES ('Japan', 'Eastern Asia', 'Asia');
INSERT INTO table_test_plan VALUES ('Jersey', 'Northern Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('Jordan', 'Western Asia', 'Asia');
INSERT INTO table_test_plan VALUES ('Kazakhstan', 'Central Asia', 'Asia');
INSERT INTO table_test_plan VALUES ('Kenya', 'Eastern Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Kiribati', 'Micronesia', 'Oceania');
INSERT INTO table_test_plan VALUES ('Korea (Democratic People Republic of)', 'Eastern Asia', 'Asia');
INSERT INTO table_test_plan VALUES ('Korea (Republic of)', 'Eastern Asia', 'Asia');
INSERT INTO table_test_plan VALUES ('Kuwait', 'Western Asia', 'Asia');
INSERT INTO table_test_plan VALUES ('Kyrgyzstan', 'Central Asia', 'Asia');
INSERT INTO table_test_plan VALUES ('Lao People Democratic Republic', 'South-Eastern Asia', 'Asia');
INSERT INTO table_test_plan VALUES ('Latvia', 'Northern Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('Lebanon', 'Western Asia', 'Asia');
INSERT INTO table_test_plan VALUES ('Lesotho', 'Southern Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Liberia', 'Western Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Libya', 'Northern Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Liechtenstein', 'Western Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('Lithuania', 'Northern Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('Luxembourg', 'Western Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('Macao', 'Eastern Asia', 'Asia');
INSERT INTO table_test_plan VALUES ('Macedonia (the former Yugoslav Republic of)', 'Southern Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('Madagascar', 'Eastern Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Malawi', 'Eastern Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Malaysia', 'South-Eastern Asia', 'Asia');
INSERT INTO table_test_plan VALUES ('Maldives', 'Southern Asia', 'Asia');
INSERT INTO table_test_plan VALUES ('Mali', 'Western Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Malta', 'Southern Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('Marshall Islands', 'Micronesia', 'Oceania');
INSERT INTO table_test_plan VALUES ('Martinique', 'Caribbean', 'Americas');
INSERT INTO table_test_plan VALUES ('Mauritania', 'Western Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Mauritius', 'Eastern Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Mayotte', 'Eastern Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Mexico', 'Central America', 'Americas');
INSERT INTO table_test_plan VALUES ('Micronesia (Federated States of)', 'Micronesia', 'Oceania');
INSERT INTO table_test_plan VALUES ('Moldova (Republic of)', 'Eastern Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('Monaco', 'Western Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('Mongolia', 'Eastern Asia', 'Asia');
INSERT INTO table_test_plan VALUES ('Montenegro', 'Southern Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('Montserrat', 'Caribbean', 'Americas');
INSERT INTO table_test_plan VALUES ('Morocco', 'Northern Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Mozambique', 'Eastern Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Myanmar', 'South-Eastern Asia', 'Asia');
INSERT INTO table_test_plan VALUES ('Namibia', 'Southern Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Nauru', 'Micronesia', 'Oceania');
INSERT INTO table_test_plan VALUES ('Nepal', 'Southern Asia', 'Asia');
INSERT INTO table_test_plan VALUES ('Netherlands', 'Western Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('New Caledonia', 'Melanesia', 'Oceania');
INSERT INTO table_test_plan VALUES ('New Zealand', 'Australia and New Zealand', 'Oceania');
INSERT INTO table_test_plan VALUES ('Nicaragua', 'Central America', 'Americas');
INSERT INTO table_test_plan VALUES ('Niger', 'Western Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Nigeria', 'Western Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Niue', 'Polynesia', 'Oceania');
INSERT INTO table_test_plan VALUES ('Norfolk Island', 'Australia and New Zealand', 'Oceania');
INSERT INTO table_test_plan VALUES ('Northern Mariana Islands', 'Micronesia', 'Oceania');
INSERT INTO table_test_plan VALUES ('Norway', 'Northern Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('Oman', 'Western Asia', 'Asia');
INSERT INTO table_test_plan VALUES ('Pakistan', 'Southern Asia', 'Asia');
INSERT INTO table_test_plan VALUES ('Palau', 'Micronesia', 'Oceania');
INSERT INTO table_test_plan VALUES ('Palestine, State of', 'Western Asia', 'Asia');
INSERT INTO table_test_plan VALUES ('Panama', 'Central America', 'Americas');
INSERT INTO table_test_plan VALUES ('Papua New Guinea', 'Melanesia', 'Oceania');
INSERT INTO table_test_plan VALUES ('Paraguay', 'South America', 'Americas');
INSERT INTO table_test_plan VALUES ('Peru', 'South America', 'Americas');
INSERT INTO table_test_plan VALUES ('Philippines', 'South-Eastern Asia', 'Asia');
INSERT INTO table_test_plan VALUES ('Pitcairn', 'Polynesia', 'Oceania');
INSERT INTO table_test_plan VALUES ('Poland', 'Eastern Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('Portugal', 'Southern Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('Puerto Rico', 'Caribbean', 'Americas');
INSERT INTO table_test_plan VALUES ('Qatar', 'Western Asia', 'Asia');
INSERT INTO table_test_plan VALUES ('Réunion', 'Eastern Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Romania', 'Eastern Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('Russian Federation', 'Eastern Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('Rwanda', 'Eastern Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Saint Barthélemy', 'Caribbean', 'Americas');
INSERT INTO table_test_plan VALUES ('Saint Helena, Ascension and Tristan da Cunha', 'Western Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Saint Kitts and Nevis', 'Caribbean', 'Americas');
INSERT INTO table_test_plan VALUES ('Saint Lucia', 'Caribbean', 'Americas');
INSERT INTO table_test_plan VALUES ('Saint Martin (French part)', 'Caribbean', 'Americas');
INSERT INTO table_test_plan VALUES ('Saint Pierre and Miquelon', 'Northern America', 'Americas');
INSERT INTO table_test_plan VALUES ('Saint Vincent and the Grenadines', 'Caribbean', 'Americas');
INSERT INTO table_test_plan VALUES ('Samoa', 'Polynesia', 'Oceania');
INSERT INTO table_test_plan VALUES ('San Marino', 'Southern Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('Sao Tome and Principe', 'Middle Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Saudi Arabia', 'Western Asia', 'Asia');
INSERT INTO table_test_plan VALUES ('Senegal', 'Western Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Serbia', 'Southern Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('Seychelles', 'Eastern Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Sierra Leone', 'Western Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Singapore', 'South-Eastern Asia', 'Asia');
INSERT INTO table_test_plan VALUES ('Sint Maarten (Dutch part)', 'Caribbean', 'Americas');
INSERT INTO table_test_plan VALUES ('Slovakia', 'Eastern Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('Slovenia', 'Southern Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('Solomon Islands', 'Melanesia', 'Oceania');
INSERT INTO table_test_plan VALUES ('Somalia', 'Eastern Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('South Africa', 'Southern Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('South Georgia and the South Sandwich Islands', '', '');
INSERT INTO table_test_plan VALUES ('South Sudan', 'Eastern Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Spain', 'Southern Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('Sri Lanka', 'Southern Asia', 'Asia');
INSERT INTO table_test_plan VALUES ('Sudan', 'Northern Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Suriname', 'South America', 'Americas');
INSERT INTO table_test_plan VALUES ('Svalbard and Jan Mayen', 'Northern Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('Swaziland', 'Southern Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Sweden', 'Northern Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('Switzerland', 'Western Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('Syrian Arab Republic', 'Western Asia', 'Asia');
INSERT INTO table_test_plan VALUES ('Taiwan, Province of China', 'Eastern Asia', 'Asia');
INSERT INTO table_test_plan VALUES ('Tajikistan', 'Central Asia', 'Asia');
INSERT INTO table_test_plan VALUES ('Tanzania, United Republic of', 'Eastern Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Thailand', 'South-Eastern Asia', 'Asia');
INSERT INTO table_test_plan VALUES ('Timor-Leste', 'South-Eastern Asia', 'Asia');
INSERT INTO table_test_plan VALUES ('Togo', 'Western Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Tokelau', 'Polynesia', 'Oceania');
INSERT INTO table_test_plan VALUES ('Tonga', 'Polynesia', 'Oceania');
INSERT INTO table_test_plan VALUES ('Trinidad and Tobago', 'Caribbean', 'Americas');
INSERT INTO table_test_plan VALUES ('Tunisia', 'Northern Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Turkey', 'Western Asia', 'Asia');
INSERT INTO table_test_plan VALUES ('Turkmenistan', 'Central Asia', 'Asia');
INSERT INTO table_test_plan VALUES ('Turks and Caicos Islands', 'Caribbean', 'Americas');
INSERT INTO table_test_plan VALUES ('Tuvalu', 'Polynesia', 'Oceania');
INSERT INTO table_test_plan VALUES ('Uganda', 'Eastern Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Ukraine', 'Eastern Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('United Arab Emirates', 'Western Asia', 'Asia');
INSERT INTO table_test_plan VALUES ('United Kingdom of Great Britain and Northern Ireland', 'Northern Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('United States of America', 'Northern America', 'Americas');
INSERT INTO table_test_plan VALUES ('United States Minor Outlying Islands', '', '');
INSERT INTO table_test_plan VALUES ('Uruguay', 'South America', 'Americas');
INSERT INTO table_test_plan VALUES ('Uzbekistan', 'Central Asia', 'Asia');
INSERT INTO table_test_plan VALUES ('Vanuatu', 'Melanesia', 'Oceania');
INSERT INTO table_test_plan VALUES ('Venezuela (Bolivarian Republic of)', 'South America', 'Americas');
INSERT INTO table_test_plan VALUES ('Viet Nam', 'South-Eastern Asia', 'Asia');
INSERT INTO table_test_plan VALUES ('Virgin Islands (British)', 'Caribbean', 'Americas');
INSERT INTO table_test_plan VALUES ('Virgin Islands (U.S.)', 'Caribbean', 'Americas');
INSERT INTO table_test_plan VALUES ('Wallis and Futuna', 'Polynesia', 'Oceania');
INSERT INTO table_test_plan VALUES ('Western Sahara', 'Northern Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Yemen', 'Western Asia', 'Asia');
INSERT INTO table_test_plan VALUES ('Zambia', 'Eastern Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('Zimbabwe', 'Eastern Africa', 'Africa');
INSERT INTO table_test_plan VALUES ('German Federal Republic', 'Western Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('German Democratic Republic', 'Eastern Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('Yugoslavia', 'Eastern Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('Kosovo', 'Eastern Europe', 'Europe');
INSERT INTO table_test_plan VALUES ('Ivory Coast', '', 'Africa');