DROP VIEW IF EXISTS V_PA_USER_FLOWS;

CREATE OR REPLACE VIEW V_PA_USER_FLOWS AS
SELECT
    SOURCE_URL AS "SOURCE",
    TARGET_URL AS "TARGET",
    COUNT(*)   AS "VALUE"
FROM (
  SELECT
    STEP_NUM,
    SESSION_ID,
    URL_PATH                                                           AS SOURCE_URL,
    LEAD(URL_PATH) OVER (PARTITION BY SESSION_ID ORDER BY CREATED_AT) AS TARGET_URL
  FROM (
    SELECT
      SESSION_ID,
      URL_PATH,
      CREATED_AT,
      ROW_NUMBER() OVER (PARTITION BY SESSION_ID ORDER BY CREATED_AT) AS STEP_NUM
    FROM PRODUCT_ANALYTICS_EVENT
    WHERE EVENT_TYPE = 1
  ) ORDERED_EVENTS
) FLOWS
WHERE TARGET_URL IS NOT NULL
  AND SOURCE_URL != TARGET_URL
  AND NOT EXISTS (
    SELECT 1
    FROM (
      SELECT
        SESSION_ID,
        URL_PATH,
        ROW_NUMBER() OVER (PARTITION BY SESSION_ID ORDER BY CREATED_AT) AS STEP_NUM
      FROM PRODUCT_ANALYTICS_EVENT
      WHERE EVENT_TYPE = 1
    ) PREV
    WHERE PREV.SESSION_ID = FLOWS.SESSION_ID
      AND PREV.URL_PATH = FLOWS.TARGET_URL
      AND PREV.STEP_NUM < FLOWS.STEP_NUM
  )
GROUP BY STEP_NUM, SOURCE_URL, TARGET_URL;
