DROP VIEW IF EXISTS V_PA_EVENTS;

CREATE OR REPLACE VIEW V_PA_EVENTS AS
SELECT
  ID,
  SITE_ID,
  SESSION_ID,
  VISIT_ID,
  EVENT_TYPE,
  EVENT_NAME,
  URL_PATH,
  URL_QUERY,
  REFERRER_PATH,
  REFERRER_QUERY,
  REFERRER_DOMAIN,
  PAGE_TITLE,
  UTM_SOURCE,
  UTM_MEDIUM,
  UTM_CAMPAIGN,
  UTM_CONTENT,
  UTM_TERM,
  GCLID,
  FBCLID,
  CREATED_AT
FROM PRODUCT_ANALYTICS_EVENT;
