/**
 * Metabase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.53.2-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MetabaseApi);
  }
}(this, function(expect, MetabaseApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MetabaseApi.ApiCardIdPutRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ApiCardIdPutRequest', function() {
    it('should create an instance of ApiCardIdPutRequest', function() {
      // uncomment below and update the code to test ApiCardIdPutRequest
      //var instance = new MetabaseApi.ApiCardIdPutRequest();
      //expect(instance).to.be.a(MetabaseApi.ApiCardIdPutRequest);
    });

    it('should have the property enableEmbedding (base name: "enable_embedding")', function() {
      // uncomment below and update the code to test the property enableEmbedding
      //var instance = new MetabaseApi.ApiCardIdPutRequest();
      //expect(instance).to.be();
    });

    it('should have the property visualizationSettings (base name: "visualization_settings")', function() {
      // uncomment below and update the code to test the property visualizationSettings
      //var instance = new MetabaseApi.ApiCardIdPutRequest();
      //expect(instance).to.be();
    });

    it('should have the property dashboardTabId (base name: "dashboard_tab_id")', function() {
      // uncomment below and update the code to test the property dashboardTabId
      //var instance = new MetabaseApi.ApiCardIdPutRequest();
      //expect(instance).to.be();
    });

    it('should have the property collectionPreview (base name: "collection_preview")', function() {
      // uncomment below and update the code to test the property collectionPreview
      //var instance = new MetabaseApi.ApiCardIdPutRequest();
      //expect(instance).to.be();
    });

    it('should have the property datasetQuery (base name: "dataset_query")', function() {
      // uncomment below and update the code to test the property datasetQuery
      //var instance = new MetabaseApi.ApiCardIdPutRequest();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new MetabaseApi.ApiCardIdPutRequest();
      //expect(instance).to.be();
    });

    it('should have the property archived (base name: "archived")', function() {
      // uncomment below and update the code to test the property archived
      //var instance = new MetabaseApi.ApiCardIdPutRequest();
      //expect(instance).to.be();
    });

    it('should have the property collectionPosition (base name: "collection_position")', function() {
      // uncomment below and update the code to test the property collectionPosition
      //var instance = new MetabaseApi.ApiCardIdPutRequest();
      //expect(instance).to.be();
    });

    it('should have the property embeddingParams (base name: "embedding_params")', function() {
      // uncomment below and update the code to test the property embeddingParams
      //var instance = new MetabaseApi.ApiCardIdPutRequest();
      //expect(instance).to.be();
    });

    it('should have the property resultMetadata (base name: "result_metadata")', function() {
      // uncomment below and update the code to test the property resultMetadata
      //var instance = new MetabaseApi.ApiCardIdPutRequest();
      //expect(instance).to.be();
    });

    it('should have the property collectionId (base name: "collection_id")', function() {
      // uncomment below and update the code to test the property collectionId
      //var instance = new MetabaseApi.ApiCardIdPutRequest();
      //expect(instance).to.be();
    });

    it('should have the property cacheTtl (base name: "cache_ttl")', function() {
      // uncomment below and update the code to test the property cacheTtl
      //var instance = new MetabaseApi.ApiCardIdPutRequest();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new MetabaseApi.ApiCardIdPutRequest();
      //expect(instance).to.be();
    });

    it('should have the property display (base name: "display")', function() {
      // uncomment below and update the code to test the property display
      //var instance = new MetabaseApi.ApiCardIdPutRequest();
      //expect(instance).to.be();
    });

    it('should have the property parameters (base name: "parameters")', function() {
      // uncomment below and update the code to test the property parameters
      //var instance = new MetabaseApi.ApiCardIdPutRequest();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new MetabaseApi.ApiCardIdPutRequest();
      //expect(instance).to.be();
    });

    it('should have the property dashboardId (base name: "dashboard_id")', function() {
      // uncomment below and update the code to test the property dashboardId
      //var instance = new MetabaseApi.ApiCardIdPutRequest();
      //expect(instance).to.be();
    });

  });

}));
