/**
 * Metabase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.53.2-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MetabaseApi);
  }
}(this, function(expect, MetabaseApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MetabaseApi.ApiDashboardDashboardIdDashcardDashcardIdCardCardIdQueryExportFormatPostRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ApiDashboardDashboardIdDashcardDashcardIdCardCardIdQueryExportFormatPostRequest', function() {
    it('should create an instance of ApiDashboardDashboardIdDashcardDashcardIdCardCardIdQueryExportFormatPostRequest', function() {
      // uncomment below and update the code to test ApiDashboardDashboardIdDashcardDashcardIdCardCardIdQueryExportFormatPostRequest
      //var instance = new MetabaseApi.ApiDashboardDashboardIdDashcardDashcardIdCardCardIdQueryExportFormatPostRequest();
      //expect(instance).to.be.a(MetabaseApi.ApiDashboardDashboardIdDashcardDashcardIdCardCardIdQueryExportFormatPostRequest);
    });

    it('should have the property formatRows (base name: "format_rows")', function() {
      // uncomment below and update the code to test the property formatRows
      //var instance = new MetabaseApi.ApiDashboardDashboardIdDashcardDashcardIdCardCardIdQueryExportFormatPostRequest();
      //expect(instance).to.be();
    });

    it('should have the property parameters (base name: "parameters")', function() {
      // uncomment below and update the code to test the property parameters
      //var instance = new MetabaseApi.ApiDashboardDashboardIdDashcardDashcardIdCardCardIdQueryExportFormatPostRequest();
      //expect(instance).to.be();
    });

    it('should have the property pivotResults (base name: "pivot_results")', function() {
      // uncomment below and update the code to test the property pivotResults
      //var instance = new MetabaseApi.ApiDashboardDashboardIdDashcardDashcardIdCardCardIdQueryExportFormatPostRequest();
      //expect(instance).to.be();
    });

  });

}));
