(ns metabase.util.i18n.validation-test
  "Validates that every translated string in `resources/i18n/*.edn` parses as a valid
  `java.text.MessageFormat` pattern. The `.edn` files are build artifacts generated by
  `./bin/i18n/build-translation-resources`; when absent (fresh checkout), the test no-ops and the
  CI `i18n` workflow runs the build step before invoking it."
  (:require
   [clojure.java.io :as io]
   [clojure.test :refer :all]
   [clojure.tools.reader.edn :as edn]
   [metabase.util.i18n.impl :as i18n.impl])
  (:import
   (java.text MessageFormat)))

(set! *warn-on-reflection* true)

(def ^:private known-invalid-translations
  "Source-string → locale pairs whose translation is known to be a broken MessageFormat pattern in
  the current `.po` files. Entries here are tolerated (the runtime already falls back to English
  for them); the goal of this allow-list is to catch *new* breakage, not to leak the existing
  backlog into test noise.

  Nearly all of these are translators who wrapped `{{...}}` or `{login}` in quote characters
  without also escaping the braces via `''...''` as MessageFormat requires. Crowdin corrections
  have been submitted; remove entries as fixes are pulled in via the translation-update workflow."
  #{["ar-SA" "[[...]] clauses must contain at least one '''{{...}}''' clause."]
    ["ar-SA" "Invalid query: found ''[['' or '''{{''' with no matching '']]'' or ''}}''"]
    ["ar-SA" "Invalid '''{{...}}''' clause: expected a param name"]
    ["ar-SA" "User lookup filter. The placeholder '''{login}''' will be replaced by the user supplied login."]
    ["ar-SA" "'''{{...}}''' clauses cannot be empty."]
    ["cs" "User lookup filter. The placeholder '''{login}''' will be replaced by the user supplied login."]
    ["es" "[[...]] clauses must contain at least one '''{{...}}''' clause."]
    ["es" "Invalid query: found ''[['' or '''{{''' with no matching '']]'' or ''}}''"]
    ["es" "Invalid '''{{...}}''' clause: expected a param name"]
    ["es" "User lookup filter. The placeholder '''{login}''' will be replaced by the user supplied login."]
    ["es" "'''{{...}}''' clauses cannot be empty."]
    ["fr" "Invalid query: found ''[['' or '''{{''' with no matching '']]'' or ''}}''"]
    ["pl" "[[...]] clauses must contain at least one '''{{...}}''' clause."]
    ["pl" "Invalid query: found ''[['' or '''{{''' with no matching '']]'' or ''}}''"]
    ["pl" "Invalid '''{{...}}''' clause: expected a param name"]
    ["pl" "User lookup filter. The placeholder '''{login}''' will be replaced by the user supplied login."]
    ["pl" "'''{{...}}''' clauses cannot be empty."]
    ["sk" "trashed {0}"]
    ["sl" "[[...]] clauses must contain at least one '''{{...}}''' clause."]
    ["sl" "Invalid query: found ''[['' or '''{{''' with no matching '']]'' or ''}}''"]
    ["sl" "Invalid '''{{...}}''' clause: expected a param name"]
    ["sl" "User lookup filter. The placeholder '''{login}''' will be replaced by the user supplied login."]
    ["sl" "'''{{...}}''' clauses cannot be empty."]
    ["zh-CN" "Invalid query: found ''[['' or '''{{''' with no matching '']]'' or ''}}''"]
    ["zh-HK" "Group membership lookup filter. The placeholders '{dn}' and '{uid}' will be replaced by the user''s Distinguished Name and UID, respectively."]})

(defn- locale-resource ^java.net.URL [locale-name]
  (io/resource (format "i18n/%s.edn" locale-name)))

(defn- translated-forms
  "Normalize a translation value into a seq of form-strings. Plural entries are vectors; we drop
  non-string elements defensively so a missing plural form doesn't NPE inside MessageFormat."
  [translated]
  (if (string? translated)
    [translated]
    (filter string? translated)))

(defn- valid-message-format? [^String s]
  (try
    (MessageFormat. s)
    true
    (catch IllegalArgumentException _ false)))

(deftest ^:parallel translations-are-valid-message-format-test
  (testing "Every translated string under resources/i18n/*.edn parses as a valid MessageFormat"
    (doseq [locale-name          (i18n.impl/available-locale-names)
            :let                 [resource (locale-resource locale-name)]
            :when                resource
            :let                 [messages (-> resource slurp edn/read-string :messages)]
            [english translated] messages
            :when                (not (contains? known-invalid-translations [locale-name english]))
            t                    (translated-forms translated)]
      (testing (format "locale %s, source %s, translated %s" locale-name (pr-str english) (pr-str t))
        (is (valid-message-format? t)
            (format "Translated string is not a valid java.text.MessageFormat pattern. Fix it in locales/%s.po, or add [%s %s] to `known-invalid-translations` if the fix has to come from Crowdin."
                    locale-name (pr-str locale-name) (pr-str english)))))))
