import type { MetabotId, SuggestedMetabotPrompt } from "metabase-types/api";

export const mockSuggestedPrompts: Record<MetabotId, SuggestedMetabotPrompt[]> =
  {
    "1": [
      {
        id: 1,
        metabot_id: 1,
        prompt: "What is the total revenue for this quarter?",
        model: "metric",
        model_id: 1,
        model_name: "Quarterly Revenue Calculator",
        created_at: "2025-05-15T10:30:00Z",
        updated_at: "2025-05-15T10:30:00Z",
      },
      {
        id: 2,
        metabot_id: 1,
        prompt:
          "Show me the customer acquisition trends over the last 6 months",
        model: "model",
        model_id: 2,
        model_name: "Customer Acquisition Trend Analyzer",
        created_at: "2025-05-15T11:15:00Z",
        updated_at: "2025-05-15T11:15:00Z",
      },
      {
        id: 3,
        metabot_id: 1,
        prompt: "What are our top performing products by sales volume?",
        model: "metric",
        model_id: 3,
        model_name: "Product Performance Ranking",
        created_at: "2025-05-15T14:22:00Z",
        updated_at: "2025-05-16T09:45:00Z",
      },
      {
        id: 4,
        metabot_id: 1,
        prompt: "How has our monthly recurring revenue changed this year?",
        model: "model",
        model_id: 1,
        model_name: "MRR Growth Tracker",
        created_at: "2025-05-16T08:30:00Z",
        updated_at: "2025-05-16T08:30:00Z",
      },
      {
        id: 5,
        metabot_id: 1,
        prompt: "What is our customer churn rate compared to last quarter?",
        model: "metric",
        model_id: 2,
        model_name: "Churn Rate Comparator",
        created_at: "2025-05-16T13:10:00Z",
        updated_at: "2025-05-16T13:10:00Z",
      },
      {
        id: 6,
        metabot_id: 1,
        prompt: "Show me the geographic distribution of our user base",
        model: "model",
        model_id: 4,
        model_name: "Geographic User Distribution Mapper",
        created_at: "2025-05-17T16:45:00Z",
        updated_at: "2025-05-18T10:20:00Z",
      },
      {
        id: 7,
        metabot_id: 1,
        prompt: "What is the average order value for new customers?",
        model: "metric",
        model_id: 4,
        model_name: "New Customer AOV Calculator",
        created_at: "2025-05-18T09:15:00Z",
        updated_at: "2025-05-18T09:15:00Z",
      },
      {
        id: 8,
        metabot_id: 1,
        prompt: "How do our conversion rates vary by traffic source?",
        model: "model",
        model_id: 3,
        model_name: "Traffic Source Conversion Analyzer",
        created_at: "2025-05-18T15:30:00Z",
        updated_at: "2025-05-18T15:30:00Z",
      },
    ],
    "2": [
      {
        id: 1,
        metabot_id: 1,
        prompt: "What is the total revenue for this quarter?",
        model: "metric",
        model_id: 1,
        model_name: "Quarterly Revenue Calculator",
        created_at: "2025-05-15T10:30:00Z",
        updated_at: "2025-05-15T10:30:00Z",
      },
    ],
  };
