CREATE TABLE public.table_test_plan
 (
  name character varying(100) COLLATE pg_catalog."default",
  sub_region character varying(100) COLLATE pg_catalog."default",
  region character varying(100) COLLATE pg_catalog."default"
 );

INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Afghanistan', 'Southern Asia', 'Asia');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Åland Islands', 'Northern Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Albania', 'Southern Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Algeria', 'Northern Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('American Samoa', 'Polynesia', 'Oceania');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Andorra', 'Southern Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Angola', 'Middle Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Anguilla', 'Caribbean', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Antarctica', '', '');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Antigua and Barbuda', 'Caribbean', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Argentina', 'South America', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Armenia', 'Western Asia', 'Asia');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Aruba', 'Caribbean', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Australia', 'Australia and New Zealand', 'Oceania');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Austria', 'Western Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Azerbaijan', 'Western Asia', 'Asia');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Bahamas', 'Caribbean', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Bahrain', 'Western Asia', 'Asia');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Bangladesh', 'Southern Asia', 'Asia');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Barbados', 'Caribbean', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Belarus', 'Eastern Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Belgium', 'Western Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Belize', 'Central America', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Benin', 'Western Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Bermuda', 'Northern America', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Bhutan', 'Southern Asia', 'Asia');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Bolivia (Plurinational State of)', 'South America', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Bonaire, Sint Eustatius and Saba', 'Caribbean', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Bosnia and Herzegovina', 'Southern Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Botswana', 'Southern Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Bouvet Island', '', '');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Brazil', 'South America', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('British Indian Ocean Territory', '', '');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Brunei Darussalam', 'South-Eastern Asia', 'Asia');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Bulgaria', 'Eastern Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Burkina Faso', 'Western Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Burundi', 'Eastern Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Cambodia', 'South-Eastern Asia', 'Asia');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Cameroon', 'Middle Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Canada', 'Northern America', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Cabo Verde', 'Western Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Cayman Islands', 'Caribbean', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Central African Republic', 'Middle Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Chad', 'Middle Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Chile', 'South America', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('China', 'Eastern Asia', 'Asia');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Christmas Island', '', '');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Cocos (Keeling) Islands', '', '');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Colombia', 'South America', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Comoros', 'Eastern Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Congo', 'Middle Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Congo (Democratic Republic of the)', 'Middle Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Cook Islands', 'Polynesia', 'Oceania');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Costa Rica', 'Central America', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Côte dIvoire', 'Western Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Croatia', 'Southern Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Cuba', 'Caribbean', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Curaçao', 'Caribbean', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Cyprus', 'Western Asia', 'Asia');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Czech Republic', 'Eastern Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Denmark', 'Northern Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Djibouti', 'Eastern Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Dominica', 'Caribbean', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Dominican Republic', 'Caribbean', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Ecuador', 'South America', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Egypt', 'Northern Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('El Salvador', 'Central America', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Equatorial Guinea', 'Middle Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Eritrea', 'Eastern Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Estonia', 'Northern Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Ethiopia', 'Eastern Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Falkland Islands (Malvinas)', 'South America', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Faroe Islands', 'Northern Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Fiji', 'Melanesia', 'Oceania');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Finland', 'Northern Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('France', 'Western Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('French Guiana', 'South America', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('French Polynesia', 'Polynesia', 'Oceania');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('French Southern Territories', '', '');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Gabon', 'Middle Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Gambia', 'Western Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Georgia', 'Western Asia', 'Asia');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Germany', 'Western Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Ghana', 'Western Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Gibraltar', 'Southern Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Greece', 'Southern Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Greenland', 'Northern America', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Grenada', 'Caribbean', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Guadeloupe', 'Caribbean', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Guam', 'Micronesia', 'Oceania');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Guatemala', 'Central America', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Guernsey', 'Northern Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Guinea', 'Western Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Guinea-Bissau', 'Western Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Guyana', 'South America', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Haiti', 'Caribbean', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Heard Island and McDonald Islands', '', '');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Holy See', 'Southern Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Honduras', 'Central America', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Hong Kong', 'Eastern Asia', 'Asia');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Hungary', 'Eastern Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Iceland', 'Northern Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('India', 'Southern Asia', 'Asia');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Indonesia', 'South-Eastern Asia', 'Asia');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Iran (Islamic Republic of)', 'Southern Asia', 'Asia');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Iraq', 'Western Asia', 'Asia');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Ireland', 'Northern Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Isle of Man', 'Northern Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Israel', 'Western Asia', 'Asia');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Italy', 'Southern Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Jamaica', 'Caribbean', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Japan', 'Eastern Asia', 'Asia');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Jersey', 'Northern Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Jordan', 'Western Asia', 'Asia');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Kazakhstan', 'Central Asia', 'Asia');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Kenya', 'Eastern Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Kiribati', 'Micronesia', 'Oceania');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Korea (Democratic People Republic of)', 'Eastern Asia', 'Asia');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Korea (Republic of)', 'Eastern Asia', 'Asia');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Kuwait', 'Western Asia', 'Asia');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Kyrgyzstan', 'Central Asia', 'Asia');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Lao People Democratic Republic', 'South-Eastern Asia', 'Asia');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Latvia', 'Northern Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Lebanon', 'Western Asia', 'Asia');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Lesotho', 'Southern Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Liberia', 'Western Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Libya', 'Northern Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Liechtenstein', 'Western Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Lithuania', 'Northern Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Luxembourg', 'Western Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Macao', 'Eastern Asia', 'Asia');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Macedonia (the former Yugoslav Republic of)', 'Southern Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Madagascar', 'Eastern Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Malawi', 'Eastern Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Malaysia', 'South-Eastern Asia', 'Asia');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Maldives', 'Southern Asia', 'Asia');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Mali', 'Western Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Malta', 'Southern Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Marshall Islands', 'Micronesia', 'Oceania');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Martinique', 'Caribbean', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Mauritania', 'Western Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Mauritius', 'Eastern Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Mayotte', 'Eastern Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Mexico', 'Central America', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Micronesia (Federated States of)', 'Micronesia', 'Oceania');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Moldova (Republic of)', 'Eastern Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Monaco', 'Western Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Mongolia', 'Eastern Asia', 'Asia');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Montenegro', 'Southern Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Montserrat', 'Caribbean', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Morocco', 'Northern Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Mozambique', 'Eastern Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Myanmar', 'South-Eastern Asia', 'Asia');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Namibia', 'Southern Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Nauru', 'Micronesia', 'Oceania');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Nepal', 'Southern Asia', 'Asia');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Netherlands', 'Western Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('New Caledonia', 'Melanesia', 'Oceania');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('New Zealand', 'Australia and New Zealand', 'Oceania');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Nicaragua', 'Central America', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Niger', 'Western Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Nigeria', 'Western Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Niue', 'Polynesia', 'Oceania');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Norfolk Island', 'Australia and New Zealand', 'Oceania');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Northern Mariana Islands', 'Micronesia', 'Oceania');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Norway', 'Northern Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Oman', 'Western Asia', 'Asia');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Pakistan', 'Southern Asia', 'Asia');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Palau', 'Micronesia', 'Oceania');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Palestine, State of', 'Western Asia', 'Asia');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Panama', 'Central America', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Papua New Guinea', 'Melanesia', 'Oceania');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Paraguay', 'South America', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Peru', 'South America', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Philippines', 'South-Eastern Asia', 'Asia');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Pitcairn', 'Polynesia', 'Oceania');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Poland', 'Eastern Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Portugal', 'Southern Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Puerto Rico', 'Caribbean', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Qatar', 'Western Asia', 'Asia');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Réunion', 'Eastern Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Romania', 'Eastern Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Russian Federation', 'Eastern Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Rwanda', 'Eastern Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Saint Barthélemy', 'Caribbean', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Saint Helena, Ascension and Tristan da Cunha', 'Western Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Saint Kitts and Nevis', 'Caribbean', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Saint Lucia', 'Caribbean', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Saint Martin (French part)', 'Caribbean', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Saint Pierre and Miquelon', 'Northern America', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Saint Vincent and the Grenadines', 'Caribbean', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Samoa', 'Polynesia', 'Oceania');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('San Marino', 'Southern Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Sao Tome and Principe', 'Middle Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Saudi Arabia', 'Western Asia', 'Asia');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Senegal', 'Western Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Serbia', 'Southern Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Seychelles', 'Eastern Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Sierra Leone', 'Western Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Singapore', 'South-Eastern Asia', 'Asia');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Sint Maarten (Dutch part)', 'Caribbean', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Slovakia', 'Eastern Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Slovenia', 'Southern Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Solomon Islands', 'Melanesia', 'Oceania');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Somalia', 'Eastern Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('South Africa', 'Southern Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('South Georgia and the South Sandwich Islands', '', '');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('South Sudan', 'Eastern Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Spain', 'Southern Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Sri Lanka', 'Southern Asia', 'Asia');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Sudan', 'Northern Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Suriname', 'South America', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Svalbard and Jan Mayen', 'Northern Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Swaziland', 'Southern Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Sweden', 'Northern Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Switzerland', 'Western Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Syrian Arab Republic', 'Western Asia', 'Asia');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Taiwan, Province of China', 'Eastern Asia', 'Asia');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Tajikistan', 'Central Asia', 'Asia');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Tanzania, United Republic of', 'Eastern Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Thailand', 'South-Eastern Asia', 'Asia');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Timor-Leste', 'South-Eastern Asia', 'Asia');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Togo', 'Western Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Tokelau', 'Polynesia', 'Oceania');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Tonga', 'Polynesia', 'Oceania');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Trinidad and Tobago', 'Caribbean', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Tunisia', 'Northern Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Turkey', 'Western Asia', 'Asia');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Turkmenistan', 'Central Asia', 'Asia');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Turks and Caicos Islands', 'Caribbean', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Tuvalu', 'Polynesia', 'Oceania');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Uganda', 'Eastern Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Ukraine', 'Eastern Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('United Arab Emirates', 'Western Asia', 'Asia');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('United Kingdom of Great Britain and Northern Ireland', 'Northern Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('United States of America', 'Northern America', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('United States Minor Outlying Islands', '', '');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Uruguay', 'South America', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Uzbekistan', 'Central Asia', 'Asia');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Vanuatu', 'Melanesia', 'Oceania');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Venezuela (Bolivarian Republic of)', 'South America', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Viet Nam', 'South-Eastern Asia', 'Asia');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Virgin Islands (British)', 'Caribbean', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Virgin Islands (U.S.)', 'Caribbean', 'Americas');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Wallis and Futuna', 'Polynesia', 'Oceania');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Western Sahara', 'Northern Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Yemen', 'Western Asia', 'Asia');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Zambia', 'Eastern Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Zimbabwe', 'Eastern Africa', 'Africa');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('German Federal Republic', 'Western Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('German Democratic Republic', 'Eastern Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Yugoslavia', 'Eastern Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Kosovo', 'Eastern Europe', 'Europe');
INSERT INTO public.table_test_plan(name, sub_region, region) VALUES ('Ivory Coast', '', 'Africa');
