import {
  AddActionElementButton,
  AddFilterParameterButton,
  AddHeadingOrTextButton,
  AddLinkCardButton,
  AddQuestionButton,
  AddSectionButton,
  AddTemporalUnitButton,
  CancelEditButton,
  CopyAnalyticsDashboardButton,
  DashboardActionMenu,
  DashboardInfoButton,
  DashboardSubscriptionButton,
  EditDashboardButton,
  FullscreenAnalyticsDashboard,
  SaveEditButton,
} from "./index";

export const DASHBOARD_HEADER_BUTTON_MAP = {
  ADD_ACTION_ELEMENT: {
    component: AddActionElementButton,
    enabled: () => true,
  },
  ADD_FILTER_PARAMETER: AddFilterParameterButton,
  ADD_HEADING_OR_TEXT: AddHeadingOrTextButton,
  ADD_LINK_CARD: AddLinkCardButton,
  ADD_QUESTION: AddQuestionButton,
  ADD_SECTION: AddSectionButton,
  ADD_TEMPORAL_UNIT: AddTemporalUnitButton,
  CANCEL_EDIT: CancelEditButton,
  COPY_ANALYTICS_DASHBOARD: CopyAnalyticsDashboardButton,
  DASHBOARD_ACTION_MENU: DashboardActionMenu,
  DASHBOARD_INFO: DashboardInfoButton,
  EDIT_DASHBOARD: EditDashboardButton,
  SAVE_EDIT: SaveEditButton,
  DASHBOARD_SUBSCRIPTION: DashboardSubscriptionButton,
  FULLSCREEN_ANALYTICS_DASHBOARD: FullscreenAnalyticsDashboard,
};
