(ns metabase-enterprise.metabot.tools.custom-viz
  "Enterprise implementation of the Metabot custom visualization tool."
  (:require
   [clojure.string :as str]
   [metabase-enterprise.custom-viz-plugin.cache :as custom-viz.cache]
   [metabase-enterprise.custom-viz-plugin.js-validate :as js-validate]
   [metabase-enterprise.custom-viz-plugin.manifest :as custom-viz.manifest]
   [metabase-enterprise.custom-viz-plugin.models.custom-viz-plugin :as custom-viz-plugin]
   [metabase-enterprise.custom-viz-plugin.settings :as custom-viz.settings]
   [metabase.api.common :as api]
   [metabase.events.core :as events]
   [metabase.lib-be.core :as lib-be]
   [metabase.lib.core :as lib]
   [metabase.metabot.agent.links :as links]
   [metabase.metabot.agent.streaming :as streaming]
   [metabase.metabot.tmpl :as te]
   [metabase.metabot.tools.custom-viz :as tools.custom-viz]
   [metabase.metabot.tools.shared :as shared]
   [metabase.metabot.tools.util :as metabot.tools.u]
   [metabase.premium-features.core :as premium-features :refer [defenterprise-schema]]
   [metabase.util :as u]
   [metabase.util.json :as json]
   [metabase.util.log :as log]
   [toucan2.core :as t2])
  (:import
   (java.io ByteArrayOutputStream)
   (java.nio.file Files OpenOption Path)
   (java.nio.file.attribute FileAttribute)
   (org.apache.commons.compress.archivers.tar TarArchiveEntry TarArchiveOutputStream)
   (org.apache.commons.compress.compressors.gzip GzipCompressorOutputStream)))

(set! *warn-on-reflection* true)

(def ^:private generated-repo-dir-name "metabase-generated-custom-viz")

(defn- non-blank
  [s]
  (when (string? s)
    (not-empty (str/trim s))))

(defn- slugify
  [s]
  (let [cleaned   (-> (or (non-blank s) "custom-viz")
                      u/lower-case-en
                      (str/replace #"^custom:" "")
                      (str/replace #"[^a-z0-9]+" "-")
                      (str/replace #"^-+|-+$" ""))
        truncated (subs cleaned 0 (min 64 (count cleaned)))]
    (or (non-blank truncated) "custom-viz")))

(defn- plugin-identifier
  [identifier display-name]
  (slugify (or (non-blank identifier) display-name)))

(defn- existing-identifier
  [identifier]
  (some-> identifier
          non-blank
          (str/replace #"(?i)^custom:" "")
          non-blank))

(defn- stringify-map-keys
  [value]
  (cond
    (map? value)
    (into {}
          (map (fn [[k v]]
                 [(cond
                    (keyword? k) (name k)
                    (string? k)  k
                    :else        (str k))
                  (stringify-map-keys v)]))
          value)

    (sequential? value)
    (mapv stringify-map-keys value)

    :else
    value))

(defn- plugin-bundle-js
  [factory-js]
  (if (str/includes? factory-js "__customVizPlugin__")
    factory-js
    (te/lines
     "(function () {"
     "  \"use strict\";"
     "  var factory = ("
     factory-js
     "  );"
     "  if (typeof factory !== \"function\") {"
     "    throw new Error(\"Custom visualization factory must be a function\");"
     "  }"
     "  globalThis.__customVizPlugin__ = factory;"
     "})();")))

(defn- source-index-js
  [factory-js]
  (if (str/includes? factory-js "__customVizPlugin__")
    factory-js
    (te/lines
     "const createVisualization = ("
     factory-js
     ");"
     ""
     "export default createVisualization;")))

(defn- package-json
  [identifier]
  (json/encode {:name identifier
                :version "1.0.0"
                :private true
                :type "module"
                :scripts {:build "vite build && node pack.mjs"}
                :dependencies {"@metabase/custom-viz" "^1.0.0"}}))

(defn- manifest-json
  [identifier description]
  (json/encode (cond-> {:name identifier
                        :metabase {:version ""}}
                 (non-blank description) (assoc :description description))))

(defn- readme
  [{:keys [display-name description]}]
  (te/lines
   (str "# " display-name)
   ""
   (or (non-blank description)
       "Generated by Metabot.")
   ""
   "This source repository was generated by Metabot and packaged as a Metabase custom visualization plugin."))

(defn- repo-files
  [{:keys [identifier display-name description factory-js]}]
  [["package.json" (package-json identifier)]
   ["metabase-plugin.json" (manifest-json identifier description)]
   ["README.md" (readme {:display-name display-name :description description})]
   ["src/index.js" (source-index-js factory-js)]
   ["dist/index.js" (plugin-bundle-js factory-js)]])

(defn- ensure-parent!
  [^Path path]
  (when-let [parent (.getParent path)]
    (Files/createDirectories parent (into-array FileAttribute []))))

(defn- write-repo!
  [identifier files]
  (let [root (Files/createDirectories
              (Path/of (System/getProperty "java.io.tmpdir")
                       (into-array String [generated-repo-dir-name]))
              (into-array FileAttribute []))
        dir  (Files/createTempDirectory root (str identifier "-")
                                        (into-array FileAttribute []))]
    (doseq [[relative-path content] files
            :let [path (.resolve dir ^String relative-path)]]
      (ensure-parent! path)
      (Files/writeString path (str content) (into-array OpenOption [])))
    (str dir)))

(defn- content-bytes
  ^bytes [content]
  (if (bytes? content)
    content
    (.getBytes (str content) "UTF-8")))

(defn- make-tgz-bytes
  ^bytes [files]
  (let [baos (ByteArrayOutputStream.)]
    (with-open [gz  (GzipCompressorOutputStream. baos)
                tar (TarArchiveOutputStream. gz)]
      (doseq [[relative-path content] files
              :let [^bytes bs (content-bytes content)
                    entry     (doto (TarArchiveEntry. ^String relative-path)
                                (.setSize (alength bs)))]]
        (.putArchiveEntry tar entry)
        (.write tar bs 0 (alength bs))
        (.closeArchiveEntry tar))
      (.finish tar))
    (.toByteArray baos)))

(defn- upsert-plugin!
  [identifier display-name bundle-bytes]
  (let [validated (custom-viz.cache/validate-bundle! bundle-bytes)
        existing  (custom-viz-plugin/select-one-non-blob :identifier identifier)
        plugin    (if existing
                    (custom-viz.cache/save-bundle! existing validated)
                    (custom-viz.cache/insert-bundle! identifier validated))]
    (when (not= display-name (:display_name plugin))
      (t2/update! :model/CustomVizPlugin (:id plugin) {:display_name display-name}))
    (let [result (custom-viz-plugin/select-one-non-blob :id (:id plugin))]
      (events/publish-event! (if existing
                               :event/custom-viz-plugin-update
                               :event/custom-viz-plugin-create)
                             (cond-> {:object  result
                                      :user-id api/*current-user-id*}
                               existing (assoc :previous-object existing)))
      result)))

(defn- plugin-runtime-info
  [{:keys [id identifier display_name icon bundle_hash manifest dev_bundle_url]}]
  (cond-> {:id           id
           :identifier   identifier
           :display_name display_name
           :icon         icon
           :bundle_url   (cond-> (format "/api/ee/custom-viz-plugin/%d/bundle" id)
                           bundle_hash (str "?v=" bundle_hash))
           :bundle_hash  bundle_hash
           :manifest     manifest}
    dev_bundle_url (assoc :dev_bundle_url dev_bundle_url)))

(defn- custom-viz-visualization-settings
  [settings plugin]
  (assoc (stringify-map-keys (or settings {}))
         "custom_viz.plugin" (stringify-map-keys (plugin-runtime-info plugin))))

(defn- query-for-id
  [query-id]
  (or (get (shared/current-queries-state) query-id)
      (get (shared/current-queries-state) (str query-id))
      (throw (ex-info (str "Query not found with ID: " query-id)
                      {:agent-error? true
                       :query-id query-id
                       :available-queries (keys (shared/current-queries-state))}))))

;;; ------------------------------------------------ Visualization catalog ------------------------------------------------

(defn- dev-only-plugin?
  [plugin]
  (nil? (:bundle_hash plugin)))

(defn- visible-plugin?
  [dev-mode? plugin]
  (and (= :active (:status plugin))
       (:enabled plugin)
       (custom-viz.manifest/compatible? plugin)
       (not (and (not dev-mode?) (dev-only-plugin? plugin)))))

(defn- plugin-description
  [{:keys [manifest]}]
  (or (non-blank (:description manifest))
      "No description provided."))

(defn- plugin->visualization-type
  [{:keys [identifier display_name] :as plugin}]
  {:source      :custom
   :identifier  identifier
   :name        display_name
   :description (plugin-description plugin)})

(defn- active-custom-visualization-types
  []
  (let [dev-mode? (custom-viz.settings/custom-viz-plugin-dev-mode-enabled)]
    (->> (custom-viz-plugin/select-non-blob :status :active
                                            :enabled true
                                            {:order-by [[:display_name :asc]]})
         (filter (partial visible-plugin? dev-mode?))
         (mapv plugin->visualization-type))))

(defenterprise-schema list-visualization-types-tool :- :map
  "List built-in and reusable custom visualization types available to the agent."
  :feature :none
  [_args :- [:map {:closed true}]]
  (let [built-in (tools.custom-viz/built-in-types)
        custom   (active-custom-visualization-types)]
    {:output (tools.custom-viz/format-visualization-types-output {:built-in built-in :custom custom})
     :structured-output {:built-in-visualizations built-in
                         :custom-visualizations   custom}}))

;;; ------------------------------------------------ Validation ------------------------------------------------

(defn- col->sample-meta
  "Convert a Lib result column to the custom-viz `Column` shape a plugin sees in
   `props.series[0].data.cols`."
  [col]
  {:name           (:name col)
   :display_name   (or (:display-name col) (:name col))
   :base_type      (some-> (:base-type col) u/qualified-name)
   :effective_type (some-> (:effective-type col) u/qualified-name)
   :semantic_type  (some-> (:semantic-type col) u/qualified-name)
   :source         "fields"})

(defn- sample-value
  "A type-appropriate placeholder value for `col` in sample row `i`, so a plugin's
   `checkRenderable`/`mount` runs against realistically-typed data."
  [col i]
  (let [t    (str (:base_type col) "|" (:semantic_type col) "|" (:effective_type col))
        has? (fn [re] (boolean (re-find re t)))]
    (cond
      (has? #"Latitude")                   (+ 37.5 (* i 0.4))
      (has? #"Longitude")                  (- -122.0 (* i 0.4))
      (has? #"Integer|BigInteger")         (* (inc i) 10)
      (has? #"Float|Decimal|Number")       (+ 12.5 (* i 7.25))
      (has? #"Boolean")                    (even? i)
      (has? #"Date|Time|Temporal|Instant") (format "2024-%02d-15T08:30:00Z" (inc (mod i 12)))
      :else                                (str (or (:display_name col) "Item") " " (inc i)))))

(defn- query->sample
  "Build a `{:series :settings}` dataset for validation from the real query's
   result columns (resolved via Lib, no query execution). Falls back to a generic
   shape when the columns can't be resolved (e.g. an unrunnable native query)."
  [query settings]
  (or (try
        (let [mp   (lib-be/application-database-metadata-provider (:database query))
              cols (mapv col->sample-meta (lib/returned-columns (lib/query mp query)))]
          (when (seq cols)
            {:series   [{:data {:cols cols
                                :rows (vec (for [i (range 5)] (mapv #(sample-value % i) cols)))}}]
             :settings (or settings {})}))
        (catch Exception e
          (log/debug e "custom-viz validation: could not derive query columns; using generic sample")
          nil))
      (js-validate/generic-sample settings)))

(defn- validate-factory-js!
  "Run the generated bundle through the headless validation harness before it is
   persisted. Throws an agent error describing the failure if the plugin is
   malformed, so the agent repairs `factory_js` instead of shipping a broken
   visualization that only fails in the browser."
  [factory-js query settings]
  (let [result (js-validate/run-validation (plugin-bundle-js factory-js)
                                           (query->sample query settings))]
    (when-not (:ok result)
      (throw (ex-info (str "The generated custom visualization failed validation and was not saved. "
                           (:error result)
                           " Fix factory_js and call create_custom_visualization again for the same query_id.")
                      {:agent-error? true :stage (:stage result)})))
    (when-let [renderable-error (:renderable-error result)]
      (log/debugf "custom-viz validation: checkRenderable threw on sample data (non-fatal): %s"
                  renderable-error))
    result))

(defn- output
  [{:keys [chart-id query-id identifier display-name repository-path]}]
  (te/lines
   "<result>"
   (format "<custom-visualization id=\"%s\" identifier=\"%s\">" chart-id identifier)
   (format "<name>%s</name>" display-name)
   (format "<query-id>%s</query-id>" query-id)
   (format "<display>custom:%s</display>" identifier)
   (when repository-path
     (format "<repository-path>%s</repository-path>" repository-path))
   "</custom-visualization>"
   "</result>"
   "<instructions>"
   "Custom visualization applied successfully. The user is now viewing it in the chat."
   (str "Reference it using: [Custom visualization](metabase://chart/" chart-id ")")
   "</instructions>"))

(defn- render-custom-viz-result
  [{:keys [query-id query identifier display-name description repository-path plugin visualization-settings]}]
  (let [display      (str "custom:" identifier)
        chart-id     (str (random-uuid))
        question-url (links/pseudo-card->link
                      {:type "question"
                       :name display-name
                       :dataset_query query
                       :display display
                       :displayIsLocked true
                       :visualization_settings (custom-viz-visualization-settings visualization-settings plugin)})
        structured   (cond-> {:result-type :custom-visualization
                              :custom-viz-plugin-id (:id plugin)
                              :identifier identifier
                              :display-name display-name
                              :description description
                              :repository-path repository-path
                              :query-id query-id
                              :query query
                              :chart-id chart-id
                              :chart-type display
                              :chart-link (str "metabase://chart/" chart-id)}
                       (nil? repository-path) (dissoc :repository-path))]
    {:output (output {:chart-id chart-id
                      :query-id query-id
                      :identifier identifier
                      :display-name display-name
                      :repository-path repository-path})
     :structured-output structured
     ;; Render the custom visualization inline in the chat (same embed path as
     ;; charts) instead of navigating the user to a separate question page.
     :data-parts [(streaming/adhoc-viz-part {:query   query
                                             :link    question-url
                                             :title   display-name
                                             :display display})]}))

(defn- reusable-plugin!
  [identifier]
  (let [plugin (or (custom-viz-plugin/select-one-non-blob :identifier identifier)
                   (throw (ex-info (str "Custom visualization not found with identifier: " identifier
                                        ". Call list_visualization_types before creating a new visualization type.")
                                   {:agent-error? true :identifier identifier})))]
    (when-not (visible-plugin? (custom-viz.settings/custom-viz-plugin-dev-mode-enabled) plugin)
      (throw (ex-info (str "Custom visualization " identifier " is not available for reuse. Call "
                           "list_visualization_types before choosing an existing visualization.")
                      {:agent-error? true :identifier identifier})))
    plugin))

(defenterprise-schema create-custom-visualization-tool :- :map
  "Create, update, or reuse a custom visualization plugin and render a query with it."
  :feature :none
  [{:keys [query_id display_name identifier description factory_js visualization_settings]}
   :- tools.custom-viz/create-custom-visualization-schema]
  (try
    (premium-features/assert-has-feature :custom-viz "Custom visualizations")
    (let [query (query-for-id query_id)]
      (if-let [factory-js (non-blank factory_js)]
        (do
          (api/check-superuser)
          (when-not (non-blank display_name)
            (throw (ex-info "display_name is required when creating or updating a custom visualization."
                            {:agent-error? true})))
          (when-not (non-blank description)
            (throw (ex-info "description is required when creating or updating a custom visualization."
                            {:agent-error? true})))
          (let [identifier      (plugin-identifier identifier display_name)
                display-name    (non-blank display_name)
                _               (validate-factory-js! factory-js query visualization_settings)
                files           (repo-files {:identifier identifier
                                             :display-name display-name
                                             :description description
                                             :factory-js factory-js})
                repository-path (write-repo! identifier files)
                bundle-bytes    (make-tgz-bytes files)
                plugin          (do
                                  (custom-viz.settings/custom-viz-enabled! true)
                                  (upsert-plugin! identifier display-name bundle-bytes))]
            (render-custom-viz-result {:query-id query_id
                                       :query query
                                       :identifier identifier
                                       :display-name display-name
                                       :description description
                                       :repository-path repository-path
                                       :plugin plugin
                                       :visualization-settings visualization_settings})))
        (let [identifier (existing-identifier identifier)]
          (when-not identifier
            (throw (ex-info "identifier is required when reusing a custom visualization without factory_js."
                            {:agent-error? true})))
          (let [plugin (reusable-plugin! identifier)]
            (render-custom-viz-result {:query-id query_id
                                       :query query
                                       :identifier identifier
                                       :display-name (:display_name plugin)
                                       :description (plugin-description plugin)
                                       :plugin plugin
                                       :visualization-settings visualization_settings})))))
    (catch Exception e
      (if (:agent-error? (ex-data e))
        {:output (ex-message e)}
        (do
          (log/error e "Failed to create custom visualization")
          (metabot.tools.u/handle-agent-error e))))))
