(ns metabase-enterprise.metabot.tools.custom-viz
  "Enterprise implementation of the Metabot custom visualization tool."
  (:require
   [clojure.string :as str]
   [metabase-enterprise.custom-viz-plugin.cache :as custom-viz.cache]
   [metabase-enterprise.custom-viz-plugin.models.custom-viz-plugin :as custom-viz-plugin]
   [metabase-enterprise.custom-viz-plugin.settings :as custom-viz.settings]
   [metabase.api.common :as api]
   [metabase.events.core :as events]
   [metabase.metabot.agent.links :as links]
   [metabase.metabot.agent.streaming :as streaming]
   [metabase.metabot.tmpl :as te]
   [metabase.metabot.tools.custom-viz :as tools.custom-viz]
   [metabase.metabot.tools.shared :as shared]
   [metabase.metabot.tools.util :as metabot.tools.u]
   [metabase.premium-features.core :as premium-features :refer [defenterprise-schema]]
   [metabase.util :as u]
   [metabase.util.json :as json]
   [metabase.util.log :as log]
   [toucan2.core :as t2])
  (:import
   (java.io ByteArrayOutputStream)
   (java.nio.file Files OpenOption Path)
   (java.nio.file.attribute FileAttribute)
   (org.apache.commons.compress.archivers.tar TarArchiveEntry TarArchiveOutputStream)
   (org.apache.commons.compress.compressors.gzip GzipCompressorOutputStream)))

(set! *warn-on-reflection* true)

(def ^:private generated-repo-dir-name "metabase-generated-custom-viz")

(defn- non-blank
  [s]
  (when (string? s)
    (not-empty (str/trim s))))

(defn- slugify
  [s]
  (let [cleaned   (-> (or (non-blank s) "custom-viz")
                      u/lower-case-en
                      (str/replace #"^custom:" "")
                      (str/replace #"[^a-z0-9]+" "-")
                      (str/replace #"^-+|-+$" ""))
        truncated (subs cleaned 0 (min 64 (count cleaned)))]
    (or (non-blank truncated) "custom-viz")))

(defn- plugin-identifier
  [identifier display-name]
  (slugify (or (non-blank identifier) display-name)))

(defn- stringify-map-keys
  [value]
  (cond
    (map? value)
    (into {}
          (map (fn [[k v]]
                 [(cond
                    (keyword? k) (name k)
                    (string? k)  k
                    :else        (str k))
                  (stringify-map-keys v)]))
          value)

    (sequential? value)
    (mapv stringify-map-keys value)

    :else
    value))

(defn- plugin-bundle-js
  [factory-js]
  (if (str/includes? factory-js "__customVizPlugin__")
    factory-js
    (te/lines
     "(function () {"
     "  \"use strict\";"
     "  var factory = ("
     factory-js
     "  );"
     "  if (typeof factory !== \"function\") {"
     "    throw new Error(\"Custom visualization factory must be a function\");"
     "  }"
     "  globalThis.__customVizPlugin__ = factory;"
     "})();")))

(defn- source-index-js
  [factory-js]
  (if (str/includes? factory-js "__customVizPlugin__")
    factory-js
    (te/lines
     "const createVisualization = ("
     factory-js
     ");"
     ""
     "export default createVisualization;")))

(defn- package-json
  [identifier]
  (json/encode {:name identifier
                :version "1.0.0"
                :private true
                :type "module"
                :scripts {:build "vite build && node pack.mjs"}
                :dependencies {"@metabase/custom-viz" "^1.0.0"}}))

(defn- manifest-json
  [identifier]
  (json/encode {:name identifier
                :metabase {:version ""}}))

(defn- readme
  [{:keys [display-name description]}]
  (te/lines
   (str "# " display-name)
   ""
   (or (non-blank description)
       "Generated by Metabot.")
   ""
   "This source repository was generated by Metabot and packaged as a Metabase custom visualization plugin."))

(defn- repo-files
  [{:keys [identifier display-name description factory-js]}]
  [["package.json" (package-json identifier)]
   ["metabase-plugin.json" (manifest-json identifier)]
   ["README.md" (readme {:display-name display-name :description description})]
   ["src/index.js" (source-index-js factory-js)]
   ["dist/index.js" (plugin-bundle-js factory-js)]])

(defn- ensure-parent!
  [^Path path]
  (when-let [parent (.getParent path)]
    (Files/createDirectories parent (into-array FileAttribute []))))

(defn- write-repo!
  [identifier files]
  (let [root (Files/createDirectories
              (Path/of (System/getProperty "java.io.tmpdir")
                       (into-array String [generated-repo-dir-name]))
              (into-array FileAttribute []))
        dir  (Files/createTempDirectory root (str identifier "-")
                                        (into-array FileAttribute []))]
    (doseq [[relative-path content] files
            :let [path (.resolve dir ^String relative-path)]]
      (ensure-parent! path)
      (Files/writeString path (str content) (into-array OpenOption [])))
    (str dir)))

(defn- content-bytes
  ^bytes [content]
  (if (bytes? content)
    content
    (.getBytes (str content) "UTF-8")))

(defn- make-tgz-bytes
  ^bytes [files]
  (let [baos (ByteArrayOutputStream.)]
    (with-open [gz  (GzipCompressorOutputStream. baos)
                tar (TarArchiveOutputStream. gz)]
      (doseq [[relative-path content] files
              :let [^bytes bs (content-bytes content)
                    entry     (doto (TarArchiveEntry. ^String relative-path)
                                (.setSize (alength bs)))]]
        (.putArchiveEntry tar entry)
        (.write tar bs 0 (alength bs))
        (.closeArchiveEntry tar))
      (.finish tar))
    (.toByteArray baos)))

(defn- upsert-plugin!
  [identifier display-name bundle-bytes]
  (let [validated (custom-viz.cache/validate-bundle! bundle-bytes)
        existing  (custom-viz-plugin/select-one-non-blob :identifier identifier)
        plugin    (if existing
                    (custom-viz.cache/save-bundle! existing validated)
                    (custom-viz.cache/insert-bundle! identifier validated))]
    (when (not= display-name (:display_name plugin))
      (t2/update! :model/CustomVizPlugin (:id plugin) {:display_name display-name}))
    (let [result (custom-viz-plugin/select-one-non-blob :id (:id plugin))]
      (events/publish-event! (if existing
                               :event/custom-viz-plugin-update
                               :event/custom-viz-plugin-create)
                             (cond-> {:object  result
                                      :user-id api/*current-user-id*}
                               existing (assoc :previous-object existing)))
      result)))

(defn- plugin-runtime-info
  [{:keys [id identifier display_name icon bundle_hash manifest dev_bundle_url]}]
  (cond-> {:id           id
           :identifier   identifier
           :display_name display_name
           :icon         icon
           :bundle_url   (cond-> (format "/api/ee/custom-viz-plugin/%d/bundle" id)
                           bundle_hash (str "?v=" bundle_hash))
           :bundle_hash  bundle_hash
           :manifest     manifest}
    dev_bundle_url (assoc :dev_bundle_url dev_bundle_url)))

(defn- visualization-settings
  [settings plugin]
  (assoc (stringify-map-keys (or settings {}))
         "custom_viz.plugin" (stringify-map-keys (plugin-runtime-info plugin))))

(defn- query-for-id
  [query-id]
  (or (get (shared/current-queries-state) query-id)
      (get (shared/current-queries-state) (str query-id))
      (throw (ex-info (str "Query not found with ID: " query-id)
                      {:agent-error? true
                       :query-id query-id
                       :available-queries (keys (shared/current-queries-state))}))))

(defn- output
  [{:keys [chart-id query-id identifier display-name repository-path]}]
  (te/lines
   "<result>"
   (format "<custom-visualization id=\"%s\" identifier=\"%s\">" chart-id identifier)
   (format "<name>%s</name>" display-name)
   (format "<query-id>%s</query-id>" query-id)
   (format "<display>custom:%s</display>" identifier)
   (format "<repository-path>%s</repository-path>" repository-path)
   "</custom-visualization>"
   "</result>"
   "<instructions>"
   "Custom visualization created and applied successfully. The user is now viewing it in the chat."
   (str "Reference it using: [Custom visualization](metabase://chart/" chart-id ")")
   "</instructions>"))

(defenterprise-schema create-custom-visualization-tool :- :map
  "Create or update a custom visualization plugin and render a query with it."
  :feature :none
  [{:keys [query_id display_name identifier description factory_js visualization_settings]}
   :- tools.custom-viz/create-custom-visualization-schema]
  (try
    (api/check-superuser)
    (premium-features/assert-has-feature :custom-viz "Custom visualizations")
    (when-not (non-blank factory_js)
      (throw (ex-info "factory_js must not be blank" {:agent-error? true})))
    (let [identifier      (plugin-identifier identifier display_name)
          display-name    (or (non-blank display_name) identifier)
          query           (query-for-id query_id)
          files           (repo-files {:identifier identifier
                                       :display-name display-name
                                       :description description
                                       :factory-js factory_js})
          repository-path (write-repo! identifier files)
          bundle-bytes    (make-tgz-bytes files)
          plugin          (do
                            (custom-viz.settings/custom-viz-enabled! true)
                            (upsert-plugin! identifier display-name bundle-bytes))
          display         (str "custom:" identifier)
          chart-id        (str (random-uuid))
          question-url    (links/pseudo-card->link
                           {:type "question"
                            :name display-name
                            :dataset_query query
                            :display display
                            :displayIsLocked true
                            :visualization_settings (visualization-settings visualization_settings plugin)})
          structured      {:result-type :custom-visualization
                           :custom-viz-plugin-id (:id plugin)
                           :identifier identifier
                           :display-name display-name
                           :repository-path repository-path
                           :query-id query_id
                           :query query
                           :chart-id chart-id
                           :chart-type display
                           :chart-link (str "metabase://chart/" chart-id)}]
      {:output (output {:chart-id chart-id
                        :query-id query_id
                        :identifier identifier
                        :display-name display-name
                        :repository-path repository-path})
       :structured-output structured
       :data-parts [(streaming/navigate-to-part question-url)]})
    (catch Exception e
      (if (:agent-error? (ex-data e))
        {:output (ex-message e)}
        (do
          (log/error e "Failed to create custom visualization")
          (metabot.tools.u/handle-agent-error e))))))
