export const LEGEND_CIRCLE_SIZE = 10;
export const LEGEND_CIRCLE_MARGIN_RIGHT = 4;
export const LEGEND_ITEM_MARGIN_RIGHT = 24;
export const LEGEND_ITEM_MARGIN_RIGHT_GRID = 16;

export const DEFAULT_LEGEND_FONT_SIZE = 14;
export const DEFAULT_LEGEND_LINE_HEIGHT = 20;
export const DEFAULT_LEGEND_FONT_WEIGHT = 700;
