DROP VIEW IF EXISTS V_PA_EVENT_DATA;

CREATE OR REPLACE SQL SECURITY INVOKER VIEW V_PA_EVENT_DATA AS
SELECT
  ID,
  EVENT_ID,
  DATA_KEY,
  STRING_VALUE,
  NUMBER_VALUE,
  DATE_VALUE,
  DATA_TYPE,
  CREATED_AT
FROM PRODUCT_ANALYTICS_EVENT_DATA;
