(ns metabase.agent-lib.capabilities.catalog.top-level
  "Top-level structured-program capability entries."
  (:require
   [metabase.lib.core :as lib]))

(set! *warn-on-reflection* true)

(def ^{:doc "Top-level structured-program capability entries."}
  capabilities
  [{:op 'filter,            :binding lib/filter,            :kind :top-level, :arities #{1}, :prompt-forms ["[\"filter\", clause]"], :shape "[\"filter\", clause]", :example "[\"filter\", [\"time-interval\", [\"field\", 2058], -12, \"month\"]]"}
   {:op 'aggregate,         :binding lib/aggregate,         :kind :top-level, :arities #{1}, :prompt-forms ["[\"aggregate\", aggregation]"], :shape "[\"aggregate\", [\"sum\", [\"field\", 2056]]]", :example "[\"aggregate\", [\"sum\", [\"field\", 2056]]]"}
   {:op 'breakout,          :binding lib/breakout,          :kind :top-level, :arities #{1}, :prompt-forms ["[\"breakout\", breakout-form]"], :shape "[\"breakout\", [\"field\", 3134]]", :example "[\"breakout\", [\"field\", 3134]]"}
   {:op 'with-fields,       :binding lib/with-fields,       :kind :top-level, :arities #{1}, :prompt-forms ["[\"with-fields\", [field-or-ref, ...]]"], :shape "[\"with-fields\", [[\"field\", 2204], [\"expression-ref\", \"Net Amount\"]]]", :example "[\"with-fields\", [[\"field\", 2204], [\"expression-ref\", \"Net Amount\"]]]"}
   {:op 'limit,             :binding lib/limit,             :kind :top-level, :arities #{1}, :prompt-forms ["[\"limit\", 10]"], :shape "[\"limit\", 10]", :example "[\"limit\", 10]"}
   {:op 'expression,        :binding lib/expression,        :kind :top-level, :arities #{2}, :prompt-forms ["[\"expression\", \"Name\", expr]"], :shape "[\"expression\", \"Net Amount\", [\"-\", [\"field\", 2624], [\"field\", 2641]]]", :example "[\"expression\", \"Net Amount\", [\"-\", [\"field\", 2624], [\"field\", 2641]]]", :prompt-notes ["If an `expression` uses `aggregation-ref`, add `append-stage` first. Do not define ratios over aggregations in the same stage that creates those aggregations."]}
   {:op 'join,              :binding lib/join,              :kind :top-level, :arities #{1}, :prompt-forms ["[\"join\", join-clause]"], :shape "[\"join\", [\"join-clause\", [\"table\", 42]]]", :example "[\"join\", [\"join-clause\", [\"table\", 42]]]", :prompt-notes ["If a related table is already surfaced in the source-table context, first try using its field ids directly without an explicit join." "Direct related-field refs are the default for one-hop related tables." "Use an explicit join when you need custom join behavior, a join alias, explicit joined-field selection, self-joins, or direct related-field refs do not work." "If an explicit join returns a permission error, retry with direct related-field refs before switching to SQL."]}
   {:op 'order-by,          :kind :top-level, :runtime-provided? true, :arities #{1 2}, :prompt-forms ["[\"order-by\", orderable]" "[\"order-by\", orderable, \"desc\"]"], :shape "[\"order-by\", [\"desc\", [\"aggregation-ref\", 0]]] or [\"order-by\", [\"aggregation-ref\", 0], \"desc\"]", :example "[\"order-by\", [\"desc\", [\"aggregation-ref\", 0]]]"}
   {:op 'append-stage,      :binding lib/append-stage,      :kind :top-level, :arities #{0}, :prompt-forms ["[\"append-stage\"]"], :shape "[\"append-stage\"]", :example "[\"append-stage\"]", :prompt-notes ["If you filter on `[\"aggregation-ref\", index]`, insert `append-stage` first. Do not filter on an aggregation result in the same stage that creates it."]}
   {:op 'drop-stage,        :binding lib/drop-stage,        :kind :top-level, :arities #{0}, :prompt-forms ["[\"drop-stage\"]"], :shape "[\"drop-stage\"]", :example "[\"drop-stage\"]"}
   {:op 'drop-empty-stages, :binding lib/drop-empty-stages, :kind :top-level, :arities #{0}, :prompt-forms ["[\"drop-empty-stages\"]"], :shape "[\"drop-empty-stages\"]", :example "[\"drop-empty-stages\"]"}
   {:op 'with-page,         :binding lib/with-page,         :kind :top-level, :arities #{1}, :prompt-forms ["[\"with-page\", {\"page\": 2, \"items\": 25}]"], :shape "[\"with-page\", {\"page\": 2, \"items\": 25}]", :example "[\"with-page\", {\"page\": 2, \"items\": 25}]", :prompt-notes ["Use JSON objects only for helpers that explicitly show one, such as `[\"with-page\", {\"page\": 2, \"items\": 25}]`."]}])
