/* eslint-disable import/no-commonjs */

const groups = {
  confusing: [
    "addEventListener",
    "defaultstatus",
    "opera",
    "removeEventListener",
  ],
  window: [
    "ContentSearchHandoffUIController",
    "ContentSearchUIController",
    "InstallTrigger",
    "NewtabRenderUtils",
    "PropTypes",
    "RPMAddMessageListener",
    "RPMSendAsyncMessage",
    "alert",
    "atob",
    "blur",
    "btoa",
    "caches",
    "cancelAnimationFrame",
    "cancelIdleCallback",
    "captureEvents",
    "clearInterval",
    "clearTimeout",
    "clientInformation",
    "close",
    "closed",
    "confirm",
    "createImageBitmap",
    "crossOriginIsolated",
    "crypto",
    "customElements",
    "devicePixelRatio",
    "document",
    "dump",
    "event",
    "external",
    "fetch",
    "find",
    "focus",
    "frameElement",
    "frames",
    "fullScreen",
    "getComputedStyle",
    "getDefaultComputedStyle",
    "getSelection",
    "history",
    "indexedDB",
    "innerHeight",
    "innerWidth",
    "isSecureContext",
    "length",
    "litElementVersions",
    "litHtmlVersions",
    "localStorage",
    "location",
    "locationbar",
    "matchMedia",
    "menubar",
    "moveBy",
    "moveTo",
    "mozInnerScreenX",
    "mozInnerScreenY",
    "name",
    "navigator",
    "onabort",
    "onafterprint",
    "onanimationcancel",
    "onanimationend",
    "onanimationiteration",
    "onanimationstart",
    "onauxclick",
    "onbeforeinput",
    "onbeforeprint",
    "onbeforetoggle",
    "onbeforeunload",
    "onblur",
    "oncancel",
    "oncanplay",
    "oncanplaythrough",
    "onchange",
    "onclick",
    "onclose",
    "oncontextlost",
    "oncontextmenu",
    "oncontextrestored",
    "oncopy",
    "oncuechange",
    "oncut",
    "ondblclick",
    "ondevicemotion",
    "ondeviceorientation",
    "ondeviceorientationabsolute",
    "ondrag",
    "ondragend",
    "ondragenter",
    "ondragexit",
    "ondragleave",
    "ondragover",
    "ondragstart",
    "ondrop",
    "ondurationchange",
    "onemptied",
    "onended",
    "onerror",
    "onfocus",
    "onformdata",
    "ongamepadconnected",
    "ongamepaddisconnected",
    "ongotpointercapture",
    "onhashchange",
    "oninput",
    "oninvalid",
    "onkeydown",
    "onkeypress",
    "onkeyup",
    "onlanguagechange",
    "onload",
    "onloadeddata",
    "onloadedmetadata",
    "onloadstart",
    "onlostpointercapture",
    "onmessage",
    "onmessageerror",
    "onmousedown",
    "onmouseenter",
    "onmouseleave",
    "onmousemove",
    "onmouseout",
    "onmouseover",
    "onmouseup",
    "onmozfullscreenchange",
    "onmozfullscreenerror",
    "onoffline",
    "ononline",
    "onpagehide",
    "onpageshow",
    "onpaste",
    "onpause",
    "onplay",
    "onplaying",
    "onpointercancel",
    "onpointerdown",
    "onpointerenter",
    "onpointerleave",
    "onpointermove",
    "onpointerout",
    "onpointerover",
    "onpointerup",
    "onpopstate",
    "onprogress",
    "onratechange",
    "onrejectionhandled",
    "onreset",
    "onresize",
    "onscroll",
    "onscrollend",
    "onsecuritypolicyviolation",
    "onseeked",
    "onseeking",
    "onselect",
    "onselectionchange",
    "onselectstart",
    "onslotchange",
    "onstalled",
    "onstorage",
    "onsubmit",
    "onsuspend",
    "ontimeupdate",
    "ontoggle",
    "ontransitioncancel",
    "ontransitionend",
    "ontransitionrun",
    "ontransitionstart",
    "onunhandledrejection",
    "onunload",
    "onvolumechange",
    "onwaiting",
    "onwebkitanimationend",
    "onwebkitanimationiteration",
    "onwebkitanimationstart",
    "onwebkittransitionend",
    "onwheel",
    "open",
    "opener",
    "origin",
    "outerHeight",
    "outerWidth",
    "pageXOffset",
    "pageYOffset",
    "parent",
    "performance",
    "personalbar",
    "postMessage",
    "print",
    "prompt",
    "queueMicrotask",
    "reactiveElementVersions",
    "releaseEvents",
    "reportError",
    "requestAnimationFrame",
    "requestIdleCallback",
    "resizeBy",
    "resizeTo",
    "screen",
    "screenLeft",
    "screenTop",
    "screenX",
    "screenY",
    "scroll",
    "scrollBy",
    "scrollByLines",
    "scrollByPages",
    "scrollMaxX",
    "scrollMaxY",
    "scrollTo",
    "scrollX",
    "scrollY",
    "scrollbars",
    "self",
    "sessionStorage",
    "setInterval",
    "setResizable",
    "setTimeout",
    "speechSynthesis",
    "status",
    "statusbar",
    "stop",
    "structuredClone",
    "toolbar",
    "top",
    "updateCommands",
    "visualViewport",
  ],
  global: [
    "clearImmediate",
    "setImmediate",
    "clearInterval",
    "clearTimeout",
    "setInterval",
    "setTimeout",
    "queueMicrotask",
    "structuredClone",
    "atob",
    "btoa",
    "performance",
    "navigator",
    "fetch",
    "crypto",
  ],
};

const lookup = {};

for (const key in groups) {
  const group = groups[key];
  for (const item of group) {
    lookup[item] ??= [];
    lookup[item].push(key);
  }
}

function all(whitelist = []) {
  const res = [];
  for (const item in lookup) {
    const groups = lookup[item];
    if (groups.length === 0) {
      continue;
    }

    if (whitelist.includes(item)) {
      continue;
    }

    const notConfusing = groups.filter(group => group !== "confusing");
    if (notConfusing.length === 0) {
      res.push({
        name: item,
        message: `Confusing global`,
      });
      continue;
    }

    const corrected = notConfusing.map(group => `${group}.${item}`);

    const list = corrected.reduce((a, b, idx, arr) => {
      if (a === "") {
        return `'${b}'`;
      }
      const sep = idx < arr.length - 1 ? ", " : " or ";
      return `${a}${sep}'${b}'`;
    }, "");

    res.push({
      name: item,
      message: `Confusing global, use ${list} instead`,
    });
  }

  return res;
}

module.exports = all;
