DROP VIEW IF EXISTS v_query_log;


CREATE OR REPLACE VIEW v_query_log AS
SELECT id AS entity_id,
       started_at,
       cast(running_time AS double precision) / 1000 AS running_time_seconds,
       result_rows,
       native AS is_native,
       context AS query_source,
       error,
       coalesce(executor_id, 0) AS user_id,
       card_id,
       'card_' || card_id AS card_qualified_id,
       dashboard_id,
       'dashboard_' || dashboard_id AS dashboard_qualified_id,
       pulse_id,
       database_id,
       'database_' || database_id AS database_qualified_id,
       cache_hit,
       action_id,
       'action_' || action_id AS action_qualified_id,
       transform_id,
       'transform_' || transform_id AS transform_qualified_id,
       lens_id,
       lens_params,
       query,
       embedding_client,
       embedding_route,
       CASE WHEN embedding_client LIKE '%-preview' THEN TRUE ELSE FALSE END AS is_preview,
       embedding_sdk_version,
       metabase_version,
       auth_method,
       is_sandboxed,
       is_impersonated,
       is_db_routed,
       parameters,
       tenant_id,
       embedding_hostname,
       embedding_path,
       user_agent,
       sanitized_user_agent,
       ip_address
FROM query_execution
    LEFT JOIN query ON query_execution.hash = query.query_hash;
