name: Total time looking for field values per day
entity_id: LN9YtKcxZk_kybyRjJx1J
created_at: '2023-11-13T20:45:10.662006Z'
creator_id: internal@metabase.com
display: line
collection_id: vG58R8k-QddHWA7_47umn
query_type: query
database_id: Internal Metabase Database
table_id: [Internal Metabase Database, public, v_tasks]
parameters: []
parameter_mappings: []
dataset_query:
  database: Internal Metabase Database
  stages:
  - aggregation:
    - - sum
      - {}
      - - field
        - {base-type: type/Float, effective-type: type/Float}
        - [Internal Metabase Database, public, v_tasks, duration_seconds]
    breakout:
    - - field
      - {base-type: type/DateTimeWithLocalTZ, temporal-unit: day, effective-type: type/DateTimeWithLocalTZ}
      - [Internal Metabase Database, public, v_tasks, started_at]
    - - field
      - {base-type: type/Text, join-alias: Databases - Database Qualified, effective-type: type/Text}
      - [Internal Metabase Database, public, v_databases, name]
    filters:
    - - =
      - {}
      - - field
        - {base-type: type/Text, effective-type: type/Text}
        - [Internal Metabase Database, public, v_tasks, task]
      - field values scanning
      - update-field-values
    - - time-interval
      - {include-current: true}
      - - field
        - {base-type: type/DateTimeWithLocalTZ, lib/uuid: 7dcb5e6b-e7d8-4983-a7bc-8c56747e4b1a}
        - started_at
      - -14
      - day
    joins:
    - alias: Databases - Database Qualified
      conditions:
      - - =
        - {}
        - - field
          - {base-type: type/Text, effective-type: type/Text}
          - [Internal Metabase Database, public, v_tasks, database_qualified_id]
        - - field
          - {base-type: type/Text, join-alias: Databases - Database Qualified, effective-type: type/Text}
          - [Internal Metabase Database, public, v_databases, entity_qualified_id]
      fields: all
      stages:
      - {source-card: -19557ZnrWiDgG4h4cKxF, lib/type: mbql.stage/mbql}
      strategy: left-join
      lib/options: {lib/uuid: 0645b8b1-b0a4-42ac-99df-28b2004c0a1d}
      lib/type: mbql/join
    source-card: PKhlEfegdbTozSMfj0aLB
    lib/type: mbql.stage/mbql
  lib/type: mbql/query
result_metadata:
- active: true
  base_type: type/DateTimeWithLocalTZ
  database_type: timestamptz
  display_name: 'Started At: Day'
  effective_type: type/DateTimeWithLocalTZ
  field_ref:
  - field
  - [Internal Metabase Database, public, v_tasks, started_at]
  - {temporal-unit: day}
  id: [Internal Metabase Database, public, v_tasks, started_at]
  inherited_temporal_unit: day
  name: started_at
  position: 4
  semantic_type: type/CreationTimestamp
  source: breakout
  table_id: [Internal Metabase Database, public, v_tasks]
  unit: day
  visibility_type: normal
  lib/breakout?: true
  lib/card-id: 142
  lib/deduplicated-name: started_at
  lib/desired-column-alias: started_at
  lib/from-model?: true
  lib/original-display-name: Started At
  lib/original-name: started_at
  lib/source: source/previous-stage
  lib/source-column-alias: started_at
  lib/temporal-unit: day
  qp/implicit-field?: true
- active: true
  base_type: type/Text
  database_type: varchar
  display_name: Databases - Database Qualified → Name
  effective_type: type/Text
  field_ref:
  - field
  - [Internal Metabase Database, public, v_databases, name]
  - {join-alias: Databases - Database Qualified}
  id: [Internal Metabase Database, public, v_databases, name]
  name: name
  position: 4
  semantic_type: type/Name
  source: breakout
  table_id: [Internal Metabase Database, public, v_databases]
  visibility_type: normal
  lib/breakout?: true
  lib/card-id: 117
  lib/deduplicated-name: name
  lib/desired-column-alias: Databases - Database Qualified__name
  lib/from-model?: true
  lib/join-alias: Databases - Database Qualified
  lib/original-display-name: Name
  lib/original-join-alias: Databases - Database Qualified
  lib/original-name: name
  lib/source: source/joins
  lib/source-column-alias: name
  qp/implicit-field?: true
- base_type: type/Float
  display_name: Sum of Duration Seconds
  effective_type: type/Float
  field_ref: [aggregation, 0]
  name: sum
  semantic_type: type/Quantity
  source: aggregation
  lib/deduplicated-name: sum
  lib/desired-column-alias: sum
  lib/original-name: sum
  lib/source: source/aggregations
  lib/source-column-alias: sum
visualization_settings:
  column_settings: null
  graph.dimensions: [started_at, name]
  graph.metrics: [sum]
  graph.series_order: null
  graph.series_order_dimension: null
card_schema: 23
serdes/meta:
- {id: LN9YtKcxZk_kybyRjJx1J, label: total_time_looking_for_field_values_per_day, model: Card}
dashboard_id: Glqmoytsnu0n6rfLUjock
source_card_id: PKhlEfegdbTozSMfj0aLB
type: question
