name: Get Docker Info
description: Determines the registry, repository, and tag a container image is pushed to.

inputs:
  repo:
    description: Registry and repo, e.g. "metabase/metabase". Overrides branch derived repo.
    required: false
    default: ''
  tag:
    description: Docker tag, e.g. v1.87.2. Overrides a branch derived tag.
    required: false
    default: ''
  branch:
    description: Branch name (defaults to current branch)
    required: false
    default: ${{ github.head_ref || github.ref_name }}
  edition:
    description: Edition (ee or oss)
    required: false
    default: ee
  owner:
    description: Repository owner (defaults to current repo owner)
    required: false
    default: ${{ github.repository_owner }}

outputs:
  repo:
    description: Docker repository name
    value: ${{ steps.docker-info.outputs.repo }}
  tag:
    description: Docker tag
    value: ${{ steps.docker-info.outputs.tag }}
  full_image:
    description: Full Docker image name (repo:tag)
    value: ${{ steps.docker-info.outputs.full_image }}

runs:
  using: "composite"
  steps:
    - name: Determine Docker info
      id: docker-info
      uses: actions/github-script@v9
      with:
        script: | # js      
          const branch = '${{ inputs.branch }}';
          const edition = '${{ inputs.edition }}';
          const owner = '${{ inputs.owner }}';

          let tag = '${{ inputs.tag}}';
          if (!tag) {
            tag = branch === 'master' ? 'latest' : `${branch.replaceAll('/', '-')}-${edition}`;
          }

          let repo = '${{ inputs.repo }}';
          if (!repo) {
            if (branch === 'master') {
              repo = edition === 'ee' ? `${owner}/metabase-enterprise-head` : `${owner}/metabase-head`; 
            } else {
              repo = `${owner}/metabase-dev`; 
            }
          }

          core.setOutput('repo', repo);
          core.setOutput('tag', tag);
          core.setOutput('full_image', `${repo}:${tag}`);

          console.log(`Resolved: repo = ${repo}, tag = ${tag}`);
