/**
 * Shared home for the dashboard-filters-matrix family
 * (e2e/test/scenarios/dashboard-filters-matrix/*.cy.spec.ts).
 *
 * Upstream splits one 216-case parameterised suite across 11 generated
 * `page-N.cy.spec.ts` files, each a two-line wrapper calling `runPage(N)` from
 * the shared `helpers/matrix-helpers.ts` (which slices `helpers/matrix.ts`).
 *
 * This module ports BOTH the runner machinery AND the full 216-entry `matrix`
 * data array — because the data array is the family's shared resource, not a
 * per-page helper. With it here, every page spec (page-0..page-10) is a thin
 * three-line spec that just calls `runPage(N)`, exactly like the Cypress
 * originals. Do NOT re-slice the data per page.
 *
 * Porting notes:
 * - `it(...)` inside `run()` becomes Playwright `test(...)`, generated at
 *   collection time under a `test.describe`. `test`/`expect` come from
 *   ./fixtures.
 * - `H.restore()` / `cy.signInAsAdmin()` → `mb.restore()` / `mb.signInAsAdmin()`.
 * - `cy.request("PUT", "/api/field/:id", ...)` → `mb.api.put(...)`.
 * - `H.createQuestion` / `H.createDashboardWithQuestions` /
 *   `H.updateDashboardCards` / `H.visitDashboard` → the shared factory / helper
 *   ports (factories.ts, dashboard-core.ts, ui.ts).
 * - `H.filterWidget().contains(name).click()` → filterWidget(page).filter(...).
 * - `cy.findByTestId("loading-indicator").should("not.exist")` → toHaveCount(0).
 * - `cy.findByTestId(component).should("be.visible")` → toBeVisible().
 */
import type { Page } from "@playwright/test";

import type { MetabaseApi } from "./api";
import { filterWidget } from "./dashboard";
import { updateDashboardCards } from "./dashboard-core";
import {
  createDashboardWithQuestions,
  createQuestion,
  type StructuredQuestionDetails,
} from "./factories";
import { expect, test } from "./fixtures";
import { SAMPLE_DATABASE } from "./sample-data";
import { visitDashboard } from "./ui";


export type TestCase = {
  arity: "single" | "multi";
  type: "search" | "dropdown" | "plain";
  adminType: "search" | "list" | "plain";
  operator: "Is" | "Contains";
  source: "connected" | "card" | "custom";
  results: "large" | "small";
  component: "token-field" | "list-field" | "single-select-list-field";
};

// there are 216 test cases so we need 11 spec files
const PER_PAGE = 20;

/** Values-query-type slice used by the parameter/field settings. */
type ValuesQueryType = "search" | "list" | "none";

export function runPage(pageNumber: number) {
  runAll(page(pageNumber));
}

export function page(number: number): TestCase[] {
  const start = number * PER_PAGE;
  const end = start + PER_PAGE;
  return matrix.slice(start, end);
}

export function runAll(cases: TestCase[]) {
  test.describe("scenarios > dashboard > parameters > matrix", () => {
    cases.forEach(run);
  });
}

export function run(testCase: TestCase) {
  test(`a parameter (${filterName(testCase)}) where the admin field setting is ${testCase.adminType} should render ${testCase.component}`, async ({
    page: pageObj,
    mb,
  }) => {
    await mb.restore();
    await mb.signInAsAdmin();

    await setup(pageObj, mb.api, testCase);

    await openParameterWidget(pageObj, testCase);
    await expect(pageObj.getByTestId("loading-indicator")).toHaveCount(0);

    await checkComponent(pageObj, testCase);
  });
}

function filterName(testCase: TestCase) {
  return `${testCase.arity} ${testCase.type} ${testCase.adminType} ${testCase.results} ${testCase.operator} ${testCase.source}`;
}

function queryType(
  type: "search" | "dropdown" | "list" | "plain",
): ValuesQueryType {
  switch (type) {
    case "search":
      return "search";
    case "dropdown":
    case "list":
      return "list";
    case "plain":
      return "none";
  }
}

const { PEOPLE, PEOPLE_ID, ACCOUNTS, ACCOUNTS_ID } = SAMPLE_DATABASE;

function parameterSource(testCase: TestCase, otherCardId: number) {
  if (testCase.source === "connected") {
    return {};
  }
  if (testCase.source === "card") {
    return {
      values_source_type: "card" as const,
      values_source_config: {
        card_id: otherCardId,
        value_field: ["field", ACCOUNTS.FIRST_NAME, null],
      },
    };
  }
  if (testCase.source === "custom") {
    const count = testCase.results === "large" ? 1050 : 5;
    return {
      values_source_type: "static-list" as const,
      values_source_config: {
        values: new Array(count).fill(0).map((_, i) => `Value ${i}`),
      },
    };
  }
  return {};
}

async function setup(page: Page, api: MetabaseApi, testCase: TestCase) {
  const column = testCase.results === "large" ? PEOPLE.NAME : PEOPLE.SOURCE;

  // TODO: set the values source and source type

  // Set field admin setting
  await api.put(`/api/field/${column}`, {
    has_field_values: queryType(testCase.adminType),
  });

  const otherCard = await createQuestion(api, {
    name: "Accounts Question",
    query: { "source-table": ACCOUNTS_ID },
  });
  const otherCardId = otherCard.id;

  const question: StructuredQuestionDetails = {
    name: "People Question",
    query: { "source-table": PEOPLE_ID },
    collection: "Our Analytics",
  };

  const type = testCase.operator === "Is" ? "string/=" : "string/contains";

  const parameter = {
    id: "5aefc726",
    name: filterName(testCase),
    slug: "filter",
    type,
    values_query_type: queryType(testCase.type),
    ...parameterSource(testCase, otherCardId),
  };

  const { dashboard, questions: cards } = await createDashboardWithQuestions(
    api,
    {
      dashboardDetails: {
        parameters: [parameter],
      },
      questions: [question],
    },
  );
  const [firstCard] = cards;

  await updateDashboardCards(api, {
    dashboard_id: dashboard.id,
    cards: [
      {
        card_id: firstCard.id,
        parameter_mappings: [
          {
            parameter_id: parameter.id,
            card_id: firstCard.id,
            target: ["dimension", ["field", column, null]],
          },
        ],
      },
    ],
  });

  await visitDashboard(page, api, dashboard.id);
}

async function openParameterWidget(page: Page, testCase: TestCase) {
  // Cypress: H.filterWidget().contains(filterName(test)).click() — first match.
  await filterWidget(page)
    .filter({ hasText: filterName(testCase) })
    .first()
    .click();
}

async function checkComponent(page: Page, testCase: TestCase) {
  if (testCase.component === "token-field") {
    await expect(page.getByTestId("token-field")).toBeVisible();
  }
  if (testCase.component === "list-field") {
    await expect(page.getByTestId("list-field")).toBeVisible();
  }
  if (testCase.component === "single-select-list-field") {
    await expect(page.getByTestId("single-select-list-field")).toBeVisible();
  }
}

// there are 216 test cases so we need 11 spec files (upstream helpers/matrix.ts,
// inlined here so the whole family lives in one support module).
const matrix: TestCase[] = [
  {
    arity: "single",
    type: "search",
    adminType: "search",
    operator: "Is",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "search",
    operator: "Is",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "search",
    operator: "Is",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "search",
    operator: "Is",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "search",
    operator: "Is",
    source: "custom",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "search",
    operator: "Is",
    source: "custom",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "search",
    operator: "Contains",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "search",
    operator: "Contains",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "search",
    operator: "Contains",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "search",
    operator: "Contains",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "search",
    operator: "Contains",
    source: "custom",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "search",
    operator: "Contains",
    source: "custom",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "list",
    operator: "Is",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "list",
    operator: "Is",
    source: "connected",
    results: "small",
    component: "list-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "list",
    operator: "Is",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "list",
    operator: "Is",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "list",
    operator: "Is",
    source: "custom",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "list",
    operator: "Is",
    source: "custom",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "list",
    operator: "Contains",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "list",
    operator: "Contains",
    source: "connected",
    results: "small",
    component: "list-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "list",
    operator: "Contains",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "list",
    operator: "Contains",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "list",
    operator: "Contains",
    source: "custom",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "list",
    operator: "Contains",
    source: "custom",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "plain",
    operator: "Is",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "plain",
    operator: "Is",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "plain",
    operator: "Is",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "plain",
    operator: "Is",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "plain",
    operator: "Is",
    source: "custom",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "plain",
    operator: "Is",
    source: "custom",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "plain",
    operator: "Contains",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "plain",
    operator: "Contains",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "plain",
    operator: "Contains",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "plain",
    operator: "Contains",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "plain",
    operator: "Contains",
    source: "custom",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "plain",
    operator: "Contains",
    source: "custom",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "search",
    operator: "Is",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "search",
    operator: "Is",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "search",
    operator: "Is",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "search",
    operator: "Is",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "search",
    operator: "Is",
    source: "custom",
    results: "large",
    component: "list-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "search",
    operator: "Is",
    source: "custom",
    results: "small",
    component: "list-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "search",
    operator: "Contains",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "search",
    operator: "Contains",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "search",
    operator: "Contains",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "search",
    operator: "Contains",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "search",
    operator: "Contains",
    source: "custom",
    results: "large",
    component: "list-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "search",
    operator: "Contains",
    source: "custom",
    results: "small",
    component: "list-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "list",
    operator: "Is",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "list",
    operator: "Is",
    source: "connected",
    results: "small",
    component: "list-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "list",
    operator: "Is",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "list",
    operator: "Is",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "list",
    operator: "Is",
    source: "custom",
    results: "large",
    component: "list-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "list",
    operator: "Is",
    source: "custom",
    results: "small",
    component: "list-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "list",
    operator: "Contains",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "list",
    operator: "Contains",
    source: "connected",
    results: "small",
    component: "list-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "list",
    operator: "Contains",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "list",
    operator: "Contains",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "list",
    operator: "Contains",
    source: "custom",
    results: "large",
    component: "list-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "list",
    operator: "Contains",
    source: "custom",
    results: "small",
    component: "list-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "plain",
    operator: "Is",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "plain",
    operator: "Is",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "plain",
    operator: "Is",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "plain",
    operator: "Is",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "plain",
    operator: "Is",
    source: "custom",
    results: "large",
    component: "list-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "plain",
    operator: "Is",
    source: "custom",
    results: "small",
    component: "list-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "plain",
    operator: "Contains",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "plain",
    operator: "Contains",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "plain",
    operator: "Contains",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "plain",
    operator: "Contains",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "plain",
    operator: "Contains",
    source: "custom",
    results: "large",
    component: "list-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "plain",
    operator: "Contains",
    source: "custom",
    results: "small",
    component: "list-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "search",
    operator: "Is",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "search",
    operator: "Is",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "search",
    operator: "Is",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "search",
    operator: "Is",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "search",
    operator: "Is",
    source: "custom",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "search",
    operator: "Is",
    source: "custom",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "search",
    operator: "Contains",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "search",
    operator: "Contains",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "search",
    operator: "Contains",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "search",
    operator: "Contains",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "search",
    operator: "Contains",
    source: "custom",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "search",
    operator: "Contains",
    source: "custom",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "list",
    operator: "Is",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "list",
    operator: "Is",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "list",
    operator: "Is",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "list",
    operator: "Is",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "list",
    operator: "Is",
    source: "custom",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "list",
    operator: "Is",
    source: "custom",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "list",
    operator: "Contains",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "list",
    operator: "Contains",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "list",
    operator: "Contains",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "list",
    operator: "Contains",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "list",
    operator: "Contains",
    source: "custom",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "list",
    operator: "Contains",
    source: "custom",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "plain",
    operator: "Is",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "plain",
    operator: "Is",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "plain",
    operator: "Is",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "plain",
    operator: "Is",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "plain",
    operator: "Is",
    source: "custom",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "plain",
    operator: "Is",
    source: "custom",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "plain",
    operator: "Contains",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "plain",
    operator: "Contains",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "plain",
    operator: "Contains",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "plain",
    operator: "Contains",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "plain",
    operator: "Contains",
    source: "custom",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "plain",
    operator: "Contains",
    source: "custom",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "search",
    operator: "Is",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "search",
    operator: "Is",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "search",
    operator: "Is",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "search",
    operator: "Is",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "search",
    operator: "Is",
    source: "custom",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "search",
    operator: "Is",
    source: "custom",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "search",
    operator: "Contains",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "search",
    operator: "Contains",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "search",
    operator: "Contains",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "search",
    operator: "Contains",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "search",
    operator: "Contains",
    source: "custom",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "search",
    operator: "Contains",
    source: "custom",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "list",
    operator: "Is",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "list",
    operator: "Is",
    source: "connected",
    results: "small",
    component: "list-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "list",
    operator: "Is",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "list",
    operator: "Is",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "list",
    operator: "Is",
    source: "custom",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "list",
    operator: "Is",
    source: "custom",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "list",
    operator: "Contains",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "list",
    operator: "Contains",
    source: "connected",
    results: "small",
    component: "list-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "list",
    operator: "Contains",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "list",
    operator: "Contains",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "list",
    operator: "Contains",
    source: "custom",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "list",
    operator: "Contains",
    source: "custom",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "plain",
    operator: "Is",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "plain",
    operator: "Is",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "plain",
    operator: "Is",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "plain",
    operator: "Is",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "plain",
    operator: "Is",
    source: "custom",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "plain",
    operator: "Is",
    source: "custom",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "plain",
    operator: "Contains",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "plain",
    operator: "Contains",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "plain",
    operator: "Contains",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "plain",
    operator: "Contains",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "plain",
    operator: "Contains",
    source: "custom",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "plain",
    operator: "Contains",
    source: "custom",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "search",
    operator: "Is",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "search",
    operator: "Is",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "search",
    operator: "Is",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "search",
    operator: "Is",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "search",
    operator: "Is",
    source: "custom",
    results: "large",
    component: "list-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "search",
    operator: "Is",
    source: "custom",
    results: "small",
    component: "list-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "search",
    operator: "Contains",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "search",
    operator: "Contains",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "search",
    operator: "Contains",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "search",
    operator: "Contains",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "search",
    operator: "Contains",
    source: "custom",
    results: "large",
    component: "list-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "search",
    operator: "Contains",
    source: "custom",
    results: "small",
    component: "list-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "list",
    operator: "Is",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "list",
    operator: "Is",
    source: "connected",
    results: "small",
    component: "list-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "list",
    operator: "Is",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "list",
    operator: "Is",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "list",
    operator: "Is",
    source: "custom",
    results: "large",
    component: "list-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "list",
    operator: "Is",
    source: "custom",
    results: "small",
    component: "list-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "list",
    operator: "Contains",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "list",
    operator: "Contains",
    source: "connected",
    results: "small",
    component: "list-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "list",
    operator: "Contains",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "list",
    operator: "Contains",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "list",
    operator: "Contains",
    source: "custom",
    results: "large",
    component: "list-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "list",
    operator: "Contains",
    source: "custom",
    results: "small",
    component: "list-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "plain",
    operator: "Is",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "plain",
    operator: "Is",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "plain",
    operator: "Is",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "plain",
    operator: "Is",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "plain",
    operator: "Is",
    source: "custom",
    results: "large",
    component: "list-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "plain",
    operator: "Is",
    source: "custom",
    results: "small",
    component: "list-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "plain",
    operator: "Contains",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "plain",
    operator: "Contains",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "plain",
    operator: "Contains",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "plain",
    operator: "Contains",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "plain",
    operator: "Contains",
    source: "custom",
    results: "large",
    component: "list-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "plain",
    operator: "Contains",
    source: "custom",
    results: "small",
    component: "list-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "search",
    operator: "Is",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "search",
    operator: "Is",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "search",
    operator: "Is",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "search",
    operator: "Is",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "search",
    operator: "Is",
    source: "custom",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "search",
    operator: "Is",
    source: "custom",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "search",
    operator: "Contains",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "search",
    operator: "Contains",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "search",
    operator: "Contains",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "search",
    operator: "Contains",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "search",
    operator: "Contains",
    source: "custom",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "search",
    operator: "Contains",
    source: "custom",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "list",
    operator: "Is",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "list",
    operator: "Is",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "list",
    operator: "Is",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "list",
    operator: "Is",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "list",
    operator: "Is",
    source: "custom",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "list",
    operator: "Is",
    source: "custom",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "list",
    operator: "Contains",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "list",
    operator: "Contains",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "list",
    operator: "Contains",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "list",
    operator: "Contains",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "list",
    operator: "Contains",
    source: "custom",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "list",
    operator: "Contains",
    source: "custom",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "plain",
    operator: "Is",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "plain",
    operator: "Is",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "plain",
    operator: "Is",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "plain",
    operator: "Is",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "plain",
    operator: "Is",
    source: "custom",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "plain",
    operator: "Is",
    source: "custom",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "plain",
    operator: "Contains",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "plain",
    operator: "Contains",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "plain",
    operator: "Contains",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "plain",
    operator: "Contains",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "plain",
    operator: "Contains",
    source: "custom",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "plain",
    operator: "Contains",
    source: "custom",
    results: "small",
    component: "token-field",
  },
];
