(ns metabase.mcp.v2.projections
  "Per-type concise/detailed response projections for v2 MCP read tools, plus the generated
   per-type `fields` dot-path catalog.

   A projection is a subset of the corresponding REST response — same property names, no
   renames. Each tool task registers its own type here; this namespace seeds a few
   representative types so the conventions layer is exercisable.

   The catalog is generated by walking the shape of a sample detailed response (rather than
   hand-listed), so it cannot drift from the projection: dot-paths up to three segments deep,
   item-relative inside arrays."
  (:require
   [clojure.string :as str]))

(set! *warn-on-reflection* true)

(defonce ^:private registry
  (atom {}))

;;; ------------------------------------------------ Catalog generation --------------------------------------------

(def ^:private max-catalog-depth 3)

(defn- sample-paths
  [prefix node]
  (cond
    (= (count prefix) max-catalog-depth)
    [(str/join "." prefix)]

    (map? node)
    (if (empty? node)
      (when (seq prefix) [(str/join "." prefix)])
      (mapcat (fn [[k v]] (sample-paths (conj prefix (name k)) v)) node))

    ;; Arrays are item-relative: the path addresses fields of the items, the array itself
    ;; contributes no segment.
    (sequential? node)
    (if-let [item (first (filter map? node))]
      (sample-paths prefix item)
      (when (seq prefix) [(str/join "." prefix)]))

    :else
    (when (seq prefix) [(str/join "." prefix)])))

(defn paths-from-sample
  "Return the vector of `fields` dot-paths derivable from `sample` (a built detailed response
   map): every leaf up to three segments deep, item-relative inside arrays."
  [sample]
  (vec (sort (distinct (sample-paths [] sample)))))

;;; ------------------------------------------------ Registry -------------------------------------------------------

(defn register-projection!
  "Register the projection entry for `type` (a keyword such as `:collection`). Overwrites any
   existing entry, so re-evaluating a tool namespace in the REPL is idempotent.

   `entry` keys:
   - `:concise` / `:detailed` — `(fn [row] response-map)`, REST property names only
   - `:sample` — a representative detailed row; the catalog is generated from
     `(:detailed entry)` applied to it
   - `:catalog` — explicit dot-path vector, only for types whose sample can't capture the
     shape (prefer `:sample`)"
  [type {:keys [concise detailed sample catalog] :as entry}]
  {:pre [(keyword? type) (fn? concise) (fn? detailed) (or sample catalog)]}
  (let [catalog (or catalog (paths-from-sample (detailed sample)))]
    (swap! registry assoc type (assoc entry :catalog catalog))
    type))

(defn project
  "Apply `type`'s `fmt` (`:concise` | `:detailed`) projection to `row`. Throws when no
   projection is registered for `type`."
  [type fmt row]
  (let [entry (get @registry type)]
    (when-not entry
      (throw (ex-info (str "No projection registered for type: " (name type))
                      {:status-code 500 :type type})))
    ((get entry fmt) row)))

(defn catalog
  "The `fields` dot-path catalog for `type`, or nil when the type is unregistered."
  [type]
  (get-in @registry [type :catalog]))

(defn all-catalogs
  "Map of registered type -> dot-path catalog, for publishing as an MCP resource."
  []
  (into (sorted-map) (map (fn [[type entry]] [type (:catalog entry)])) @registry))

;;; --------------------------------------------- Representative types ---------------------------------------------
;; Field selection ported from the v1 presenters (metabase.metabot.tools.resources), but keeping
;; the REST property names — v2 never renames (`db_id` stays `db_id`, no synthetic `uri`/`path`).

(def ^:private collection-concise-keys
  [:id :name :description :location :archived])

(def ^:private collection-detailed-keys
  (into collection-concise-keys
        [:authority_level :personal_owner_id :namespace :entity_id :slug :created_at]))

(register-projection!
 :collection
 {:concise  #(select-keys % collection-concise-keys)
  :detailed #(select-keys % collection-detailed-keys)
  :sample   (zipmap collection-detailed-keys (repeat "x"))})

(def ^:private table-concise-keys
  [:id :name :display_name :schema :db_id :description])

(def ^:private table-detailed-keys
  (into table-concise-keys
        [:entity_type :view_count :active :field_order :is_upload :visibility_type
         :initial_sync_status :created_at :updated_at]))

(register-projection!
 :table
 {:concise  #(select-keys % table-concise-keys)
  :detailed #(select-keys % table-detailed-keys)
  :sample   (zipmap table-detailed-keys (repeat "x"))})

(def ^:private question-concise-keys
  [:id :name :type :description :display :collection_id :database_id :table_id :archived])

(def ^:private question-detailed-keys
  (into question-concise-keys
        [:entity_id :dashboard_id :collection_position :creator_id :cache_ttl
         :created_at :updated_at :parameters]))

(register-projection!
 :question
 {:concise  #(select-keys % question-concise-keys)
  :detailed #(select-keys % question-detailed-keys)
  :sample   (-> (zipmap question-detailed-keys (repeat "x"))
                (assoc :parameters [{:id "p1" :name "Category" :type "category"}]))})
