DROP VIEW IF EXISTS "V_PA_SESSION_DATA";

CREATE OR REPLACE VIEW "V_PA_SESSION_DATA" AS
SELECT
  "ID",
  "SESSION_ID",
  "DATA_KEY",
  "STRING_VALUE",
  "NUMBER_VALUE",
  "DATE_VALUE",
  "DATA_TYPE",
  "CREATED_AT"
FROM "PRODUCT_ANALYTICS_SESSION_DATA";
