#!/usr/bin/env bash
#
# Generates frontend/src/types/cljs.d.ts from:
#   1. TS imports — which cljs/* modules are actually used
#   2. CLJS compiled output — what each module exports
#
# Usage: ./scripts/generate-cljs-types.sh [cljs_dev_dir]
#   cljs_dev_dir defaults to target/cljs_dev

set -euo pipefail

CLJS_DIR="${1:-target/cljs_dev}"
OUTPUT="frontend/src/types/cljs.d.ts"

if [ ! -d "$CLJS_DIR" ]; then
  echo "Error: $CLJS_DIR does not exist. Run the CLJS build first." >&2
  exit 1
fi

# Step 1: Find all cljs module names imported from TS/JS files
# Matches both:  from "cljs/..."  and  import("cljs/...")
modules=$(
  grep -rohE '(from |import\()"cljs/[^"]*"' frontend/src enterprise/frontend/src 2>/dev/null \
    | sed -E 's/(from |import\()"cljs\///; s/"//' \
    | sort -u
)

# Step 2: Generate the .d.ts
{
  cat <<'HEADER'
/**
 * Type declarations for ClojureScript modules compiled by shadow-cljs.
 *
 * AUTO-GENERATED by scripts/generate-cljs-types.sh — do not edit manually.
 *
 * These declarations let TypeScript validate import names without parsing
 * the large compiled JS files in target/cljs_dev/.
 */
HEADER

  for mod in $modules; do
    # Resolve the actual file — some imports omit .js
    file="$CLJS_DIR/$mod"
    if [ ! -f "$file" ]; then
      file="$CLJS_DIR/${mod}.js"
    fi

    if [ ! -f "$file" ]; then
      echo "// WARNING: could not find compiled file for cljs/$mod" >&2
      echo ""
      echo "declare module \"cljs/$mod\" {"
      echo "  const _: any;"
      echo "  export = _;"
      echo "}"
      echo ""
      continue
    fi

    # Extract export names from Object.defineProperty(module.exports, "name", ...)
    exports=$(
      grep -o 'Object\.defineProperty(module\.exports, "[^"]*"' "$file" \
        | sed 's/Object\.defineProperty(module\.exports, "//; s/"//' \
        | sort
    ) || true

    echo ""
    echo "declare module \"cljs/$mod\" {"

    if [ -z "$exports" ]; then
      echo "  const _: any;"
      echo "  export = _;"
    else
      for exp in $exports; do
        echo "  export const $exp: any;"
      done
    fi

    echo "}"
  done

  # Catch-all for any ClojureScript modules not explicitly declared above.
  # This prevents TypeScript errors for dynamic or rarely-used imports.
  cat <<'WILDCARD'

// Catch-all for ClojureScript modules not explicitly declared above.
declare module "cljs/metabase.*" {
  const value: any;
  export = value;
}
WILDCARD
} > "$OUTPUT"

echo "Generated $OUTPUT with $(echo "$modules" | wc -w | tr -d ' ') module declarations"
