/**
 * Metabase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.53.2-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiBookmarkOrderingPutRequestOrderingsInner from './ApiBookmarkOrderingPutRequestOrderingsInner';

/**
 * The ApiBookmarkOrderingPutRequest model module.
 * @module model/ApiBookmarkOrderingPutRequest
 * @version v1.53.2-SNAPSHOT
 */
class ApiBookmarkOrderingPutRequest {
    /**
     * Constructs a new <code>ApiBookmarkOrderingPutRequest</code>.
     * @alias module:model/ApiBookmarkOrderingPutRequest
     * @param orderings {Array.<module:model/ApiBookmarkOrderingPutRequestOrderingsInner>} 
     */
    constructor(orderings) { 
        
        ApiBookmarkOrderingPutRequest.initialize(this, orderings);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, orderings) { 
        obj['orderings'] = orderings;
    }

    /**
     * Constructs a <code>ApiBookmarkOrderingPutRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiBookmarkOrderingPutRequest} obj Optional instance to populate.
     * @return {module:model/ApiBookmarkOrderingPutRequest} The populated <code>ApiBookmarkOrderingPutRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiBookmarkOrderingPutRequest();

            if (data.hasOwnProperty('orderings')) {
                obj['orderings'] = ApiClient.convertToType(data['orderings'], [ApiBookmarkOrderingPutRequestOrderingsInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiBookmarkOrderingPutRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiBookmarkOrderingPutRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApiBookmarkOrderingPutRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['orderings']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['orderings'])) {
                throw new Error("Expected the field `orderings` to be an array in the JSON data but got " + data['orderings']);
            }
            // validate the optional field `orderings` (array)
            for (const item of data['orderings']) {
                ApiBookmarkOrderingPutRequestOrderingsInner.validateJSON(item);
            };
        }

        return true;
    }


}

ApiBookmarkOrderingPutRequest.RequiredProperties = ["orderings"];

/**
 * @member {Array.<module:model/ApiBookmarkOrderingPutRequestOrderingsInner>} orderings
 */
ApiBookmarkOrderingPutRequest.prototype['orderings'] = undefined;






export default ApiBookmarkOrderingPutRequest;

