/**
 * Metabase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.53.2-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApiChannelTestPostRequest model module.
 * @module model/ApiChannelTestPostRequest
 * @version v1.53.2-SNAPSHOT
 */
class ApiChannelTestPostRequest {
    /**
     * Constructs a new <code>ApiChannelTestPostRequest</code>.
     * @alias module:model/ApiChannelTestPostRequest
     * @param details {Object} 
     * @param type {Object} 
     */
    constructor(details, type) { 
        
        ApiChannelTestPostRequest.initialize(this, details, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, details, type) { 
        obj['details'] = details;
        obj['type'] = type;
    }

    /**
     * Constructs a <code>ApiChannelTestPostRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiChannelTestPostRequest} obj Optional instance to populate.
     * @return {module:model/ApiChannelTestPostRequest} The populated <code>ApiChannelTestPostRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiChannelTestPostRequest();

            if (data.hasOwnProperty('details')) {
                obj['details'] = ApiClient.convertToType(data['details'], Object);
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiChannelTestPostRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiChannelTestPostRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApiChannelTestPostRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

ApiChannelTestPostRequest.RequiredProperties = ["details", "type"];

/**
 * @member {Object} details
 */
ApiChannelTestPostRequest.prototype['details'] = undefined;

/**
 * @member {Object} type
 */
ApiChannelTestPostRequest.prototype['type'] = undefined;






export default ApiChannelTestPostRequest;

