/**
 * Metabase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.53.2-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiDashboardPivotDashboardIdDashcardDashcardIdCardCardIdQueryPostRequestParametersInner from './ApiDashboardPivotDashboardIdDashcardDashcardIdCardCardIdQueryPostRequestParametersInner';

/**
 * The ApiDashboardPivotDashboardIdDashcardDashcardIdCardCardIdQueryPostRequest model module.
 * @module model/ApiDashboardPivotDashboardIdDashcardDashcardIdCardCardIdQueryPostRequest
 * @version v1.53.2-SNAPSHOT
 */
class ApiDashboardPivotDashboardIdDashcardDashcardIdCardCardIdQueryPostRequest {
    /**
     * Constructs a new <code>ApiDashboardPivotDashboardIdDashcardDashcardIdCardCardIdQueryPostRequest</code>.
     * @alias module:model/ApiDashboardPivotDashboardIdDashcardDashcardIdCardCardIdQueryPostRequest
     */
    constructor() { 
        
        ApiDashboardPivotDashboardIdDashcardDashcardIdCardCardIdQueryPostRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ApiDashboardPivotDashboardIdDashcardDashcardIdCardCardIdQueryPostRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiDashboardPivotDashboardIdDashcardDashcardIdCardCardIdQueryPostRequest} obj Optional instance to populate.
     * @return {module:model/ApiDashboardPivotDashboardIdDashcardDashcardIdCardCardIdQueryPostRequest} The populated <code>ApiDashboardPivotDashboardIdDashcardDashcardIdCardCardIdQueryPostRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiDashboardPivotDashboardIdDashcardDashcardIdCardCardIdQueryPostRequest();

            if (data.hasOwnProperty('parameters')) {
                obj['parameters'] = ApiClient.convertToType(data['parameters'], [ApiDashboardPivotDashboardIdDashcardDashcardIdCardCardIdQueryPostRequestParametersInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiDashboardPivotDashboardIdDashcardDashcardIdCardCardIdQueryPostRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiDashboardPivotDashboardIdDashcardDashcardIdCardCardIdQueryPostRequest</code>.
     */
    static validateJSON(data) {
        if (data['parameters']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['parameters'])) {
                throw new Error("Expected the field `parameters` to be an array in the JSON data but got " + data['parameters']);
            }
            // validate the optional field `parameters` (array)
            for (const item of data['parameters']) {
                ApiDashboardPivotDashboardIdDashcardDashcardIdCardCardIdQueryPostRequestParametersInner.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/ApiDashboardPivotDashboardIdDashcardDashcardIdCardCardIdQueryPostRequestParametersInner>} parameters
 */
ApiDashboardPivotDashboardIdDashcardDashcardIdCardCardIdQueryPostRequest.prototype['parameters'] = undefined;






export default ApiDashboardPivotDashboardIdDashcardDashcardIdCardCardIdQueryPostRequest;

