/**
 * Metabase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.53.2-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApiEeSerializationImportPostRequestFile model module.
 * @module model/ApiEeSerializationImportPostRequestFile
 * @version v1.53.2-SNAPSHOT
 */
class ApiEeSerializationImportPostRequestFile {
    /**
     * Constructs a new <code>ApiEeSerializationImportPostRequestFile</code>.
     * .tgz with serialization data
     * @alias module:model/ApiEeSerializationImportPostRequestFile
     * @extends Object
     * @param contentType {String} 
     * @param filename {String} 
     * @param size {Number} 
     * @param tempfile {Object} 
     */
    constructor(contentType, filename, size, tempfile) { 
        
        ApiEeSerializationImportPostRequestFile.initialize(this, contentType, filename, size, tempfile);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, contentType, filename, size, tempfile) { 
        obj['content-type'] = contentType;
        obj['filename'] = filename;
        obj['size'] = size;
        obj['tempfile'] = tempfile;
    }

    /**
     * Constructs a <code>ApiEeSerializationImportPostRequestFile</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiEeSerializationImportPostRequestFile} obj Optional instance to populate.
     * @return {module:model/ApiEeSerializationImportPostRequestFile} The populated <code>ApiEeSerializationImportPostRequestFile</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiEeSerializationImportPostRequestFile();

            ApiClient.constructFromObject(data, obj, 'Object');
            

            if (data.hasOwnProperty('content-type')) {
                obj['content-type'] = ApiClient.convertToType(data['content-type'], 'String');
            }
            if (data.hasOwnProperty('filename')) {
                obj['filename'] = ApiClient.convertToType(data['filename'], 'String');
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
            if (data.hasOwnProperty('tempfile')) {
                obj['tempfile'] = ApiClient.convertToType(data['tempfile'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiEeSerializationImportPostRequestFile</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiEeSerializationImportPostRequestFile</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApiEeSerializationImportPostRequestFile.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['content-type'] && !(typeof data['content-type'] === 'string' || data['content-type'] instanceof String)) {
            throw new Error("Expected the field `content-type` to be a primitive type in the JSON string but got " + data['content-type']);
        }
        // ensure the json data is a string
        if (data['filename'] && !(typeof data['filename'] === 'string' || data['filename'] instanceof String)) {
            throw new Error("Expected the field `filename` to be a primitive type in the JSON string but got " + data['filename']);
        }

        return true;
    }


}

ApiEeSerializationImportPostRequestFile.RequiredProperties = ["content-type", "filename", "size", "tempfile"];

/**
 * @member {String} content-type
 */
ApiEeSerializationImportPostRequestFile.prototype['content-type'] = undefined;

/**
 * @member {String} filename
 */
ApiEeSerializationImportPostRequestFile.prototype['filename'] = undefined;

/**
 * @member {Number} size
 */
ApiEeSerializationImportPostRequestFile.prototype['size'] = undefined;

/**
 * @member {Object} tempfile
 */
ApiEeSerializationImportPostRequestFile.prototype['tempfile'] = undefined;






export default ApiEeSerializationImportPostRequestFile;

