/**
 * Metabase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.53.2-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApiPulseTestPostRequest model module.
 * @module model/ApiPulseTestPostRequest
 * @version v1.53.2-SNAPSHOT
 */
class ApiPulseTestPostRequest {
    /**
     * Constructs a new <code>ApiPulseTestPostRequest</code>.
     * @alias module:model/ApiPulseTestPostRequest
     * @param cards {Object} 
     * @param channels {Object} 
     * @param name {String} 
     */
    constructor(cards, channels, name) { 
        
        ApiPulseTestPostRequest.initialize(this, cards, channels, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, cards, channels, name) { 
        obj['cards'] = cards;
        obj['channels'] = channels;
        obj['name'] = name;
        obj['skip_if_empty'] = false;
    }

    /**
     * Constructs a <code>ApiPulseTestPostRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiPulseTestPostRequest} obj Optional instance to populate.
     * @return {module:model/ApiPulseTestPostRequest} The populated <code>ApiPulseTestPostRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiPulseTestPostRequest();

            if (data.hasOwnProperty('cards')) {
                obj['cards'] = ApiClient.convertToType(data['cards'], Object);
            }
            if (data.hasOwnProperty('channels')) {
                obj['channels'] = ApiClient.convertToType(data['channels'], Object);
            }
            if (data.hasOwnProperty('collection_id')) {
                obj['collection_id'] = ApiClient.convertToType(data['collection_id'], 'Number');
            }
            if (data.hasOwnProperty('collection_position')) {
                obj['collection_position'] = ApiClient.convertToType(data['collection_position'], 'Number');
            }
            if (data.hasOwnProperty('dashboard_id')) {
                obj['dashboard_id'] = ApiClient.convertToType(data['dashboard_id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('skip_if_empty')) {
                obj['skip_if_empty'] = ApiClient.convertToType(data['skip_if_empty'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiPulseTestPostRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiPulseTestPostRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApiPulseTestPostRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }

        return true;
    }


}

ApiPulseTestPostRequest.RequiredProperties = ["cards", "channels", "name"];

/**
 * @member {Object} cards
 */
ApiPulseTestPostRequest.prototype['cards'] = undefined;

/**
 * @member {Object} channels
 */
ApiPulseTestPostRequest.prototype['channels'] = undefined;

/**
 * value must be an integer greater than zero.
 * @member {Number} collection_id
 */
ApiPulseTestPostRequest.prototype['collection_id'] = undefined;

/**
 * value must be an integer greater than zero.
 * @member {Number} collection_position
 */
ApiPulseTestPostRequest.prototype['collection_position'] = undefined;

/**
 * value must be an integer greater than zero.
 * @member {Number} dashboard_id
 */
ApiPulseTestPostRequest.prototype['dashboard_id'] = undefined;

/**
 * @member {String} name
 */
ApiPulseTestPostRequest.prototype['name'] = undefined;

/**
 * @member {Boolean} skip_if_empty
 * @default false
 */
ApiPulseTestPostRequest.prototype['skip_if_empty'] = false;






export default ApiPulseTestPostRequest;

