/**
 * Metabase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.53.2-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApiPulseIdPutRequest model module.
 * @module model/ApiPulseIdPutRequest
 * @version v1.53.2-SNAPSHOT
 */
class ApiPulseIdPutRequest {
    /**
     * Constructs a new <code>ApiPulseIdPutRequest</code>.
     * @alias module:model/ApiPulseIdPutRequest
     */
    constructor() { 
        
        ApiPulseIdPutRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['archived'] = false;
        obj['skip_if_empty'] = false;
    }

    /**
     * Constructs a <code>ApiPulseIdPutRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiPulseIdPutRequest} obj Optional instance to populate.
     * @return {module:model/ApiPulseIdPutRequest} The populated <code>ApiPulseIdPutRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiPulseIdPutRequest();

            if (data.hasOwnProperty('archived')) {
                obj['archived'] = ApiClient.convertToType(data['archived'], 'Boolean');
            }
            if (data.hasOwnProperty('cards')) {
                obj['cards'] = ApiClient.convertToType(data['cards'], Object);
            }
            if (data.hasOwnProperty('channels')) {
                obj['channels'] = ApiClient.convertToType(data['channels'], Object);
            }
            if (data.hasOwnProperty('collection_id')) {
                obj['collection_id'] = ApiClient.convertToType(data['collection_id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('parameters')) {
                obj['parameters'] = ApiClient.convertToType(data['parameters'], [Object]);
            }
            if (data.hasOwnProperty('skip_if_empty')) {
                obj['skip_if_empty'] = ApiClient.convertToType(data['skip_if_empty'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiPulseIdPutRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiPulseIdPutRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['parameters'])) {
            throw new Error("Expected the field `parameters` to be an array in the JSON data but got " + data['parameters']);
        }

        return true;
    }


}



/**
 * @member {Boolean} archived
 * @default false
 */
ApiPulseIdPutRequest.prototype['archived'] = false;

/**
 * @member {Object} cards
 */
ApiPulseIdPutRequest.prototype['cards'] = undefined;

/**
 * @member {Object} channels
 */
ApiPulseIdPutRequest.prototype['channels'] = undefined;

/**
 * value must be an integer greater than zero.
 * @member {Number} collection_id
 */
ApiPulseIdPutRequest.prototype['collection_id'] = undefined;

/**
 * @member {String} name
 */
ApiPulseIdPutRequest.prototype['name'] = undefined;

/**
 * @member {Array.<Object>} parameters
 */
ApiPulseIdPutRequest.prototype['parameters'] = undefined;

/**
 * @member {Boolean} skip_if_empty
 * @default false
 */
ApiPulseIdPutRequest.prototype['skip_if_empty'] = false;






export default ApiPulseIdPutRequest;

