/**
 * Metabase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.53.2-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApiUserIdPasswordPutRequest model module.
 * @module model/ApiUserIdPasswordPutRequest
 * @version v1.53.2-SNAPSHOT
 */
class ApiUserIdPasswordPutRequest {
    /**
     * Constructs a new <code>ApiUserIdPasswordPutRequest</code>.
     * @alias module:model/ApiUserIdPasswordPutRequest
     * @param password {String} password is too common.
     */
    constructor(password) { 
        
        ApiUserIdPasswordPutRequest.initialize(this, password);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, password) { 
        obj['password'] = password;
    }

    /**
     * Constructs a <code>ApiUserIdPasswordPutRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiUserIdPasswordPutRequest} obj Optional instance to populate.
     * @return {module:model/ApiUserIdPasswordPutRequest} The populated <code>ApiUserIdPasswordPutRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiUserIdPasswordPutRequest();

            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiUserIdPasswordPutRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiUserIdPasswordPutRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApiUserIdPasswordPutRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['password'] && !(typeof data['password'] === 'string' || data['password'] instanceof String)) {
            throw new Error("Expected the field `password` to be a primitive type in the JSON string but got " + data['password']);
        }

        return true;
    }


}

ApiUserIdPasswordPutRequest.RequiredProperties = ["password"];

/**
 * password is too common.
 * @member {String} password
 */
ApiUserIdPasswordPutRequest.prototype['password'] = undefined;






export default ApiUserIdPasswordPutRequest;

