/**
 * Metabase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.53.2-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MetabaseApiCacheCacheStrategyEeSchedule model module.
 * @module model/MetabaseApiCacheCacheStrategyEeSchedule
 * @version v1.53.2-SNAPSHOT
 */
class MetabaseApiCacheCacheStrategyEeSchedule {
    /**
     * Constructs a new <code>MetabaseApiCacheCacheStrategyEeSchedule</code>.
     * @alias module:model/MetabaseApiCacheCacheStrategyEeSchedule
     * @extends Object
     * @param schedule {String} 
     * @param type {Object} 
     */
    constructor(schedule, type) { 
        
        MetabaseApiCacheCacheStrategyEeSchedule.initialize(this, schedule, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, schedule, type) { 
        obj['schedule'] = schedule;
        obj['type'] = type;
    }

    /**
     * Constructs a <code>MetabaseApiCacheCacheStrategyEeSchedule</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MetabaseApiCacheCacheStrategyEeSchedule} obj Optional instance to populate.
     * @return {module:model/MetabaseApiCacheCacheStrategyEeSchedule} The populated <code>MetabaseApiCacheCacheStrategyEeSchedule</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MetabaseApiCacheCacheStrategyEeSchedule();

            ApiClient.constructFromObject(data, obj, 'Object');
            

            if (data.hasOwnProperty('refresh_automatically')) {
                obj['refresh_automatically'] = ApiClient.convertToType(data['refresh_automatically'], 'Boolean');
            }
            if (data.hasOwnProperty('schedule')) {
                obj['schedule'] = ApiClient.convertToType(data['schedule'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MetabaseApiCacheCacheStrategyEeSchedule</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MetabaseApiCacheCacheStrategyEeSchedule</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of MetabaseApiCacheCacheStrategyEeSchedule.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['schedule'] && !(typeof data['schedule'] === 'string' || data['schedule'] instanceof String)) {
            throw new Error("Expected the field `schedule` to be a primitive type in the JSON string but got " + data['schedule']);
        }

        return true;
    }


}

MetabaseApiCacheCacheStrategyEeSchedule.RequiredProperties = ["schedule", "type"];

/**
 * @member {Boolean} refresh_automatically
 */
MetabaseApiCacheCacheStrategyEeSchedule.prototype['refresh_automatically'] = undefined;

/**
 * @member {String} schedule
 */
MetabaseApiCacheCacheStrategyEeSchedule.prototype['schedule'] = undefined;

/**
 * @member {Object} type
 */
MetabaseApiCacheCacheStrategyEeSchedule.prototype['type'] = undefined;






export default MetabaseApiCacheCacheStrategyEeSchedule;

