/**
 * Metabase API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.53.2-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class MetabaseTimelineApiTimelineInclude.
* @enum {}
* @readonly
*/
export default class MetabaseTimelineApiTimelineInclude {
    
        /**
         * value: "events"
         * @const
         */
        "events" = "events";

    

    /**
    * Returns a <code>MetabaseTimelineApiTimelineInclude</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/MetabaseTimelineApiTimelineInclude} The enum <code>MetabaseTimelineApiTimelineInclude</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

