SET DB_CLOSE_DELAY -1;

CREATE USER IF NOT EXISTS GUEST PASSWORD 'guest';

CREATE TABLE "FIELD_WITH_COMMENT" (
  "ID" SERIAL PRIMARY KEY,
  "WITH_COMMENT" TEXT,
  "NO_COMMENT" TEXT
);

COMMENT ON COLUMN "FIELD_WITH_COMMENT"."WITH_COMMENT" IS 'original comment';

GRANT ALL ON "FIELD_WITH_COMMENT" TO GUEST;

CREATE TABLE "TABLE_WITHOUT_COMMENT" (
  "ID" SERIAL PRIMARY KEY,
  foo TEXT
);

GRANT ALL ON "TABLE_WITHOUT_COMMENT" TO GUEST;

CREATE TABLE "TABLE_WITH_COMMENT" (
  "ID" SERIAL PRIMARY KEY,
  foo TEXT
);

COMMENT ON TABLE "TABLE_WITH_COMMENT" IS 'table comment';

GRANT ALL ON "TABLE_WITH_COMMENT" TO GUEST;

INSERT INTO "FIELD_WITH_COMMENT" ("WITH_COMMENT", "NO_COMMENT")
VALUES
('foo', 'bar');

INSERT INTO "TABLE_WITHOUT_COMMENT" (foo)
VALUES
('bar');

INSERT INTO "TABLE_WITH_COMMENT" (foo)
VALUES
('bar');
