export const DRAGGABLE_ID = {
  COLUMN: "COLUMN",
  WELL_ITEM: "WELL_ITEM",
};

export const DROPPABLE_ID = {
  CANVAS_MAIN: "CANVAS_MAIN",
  X_AXIS_WELL: "X_AXIS_WELL",
  Y_AXIS_WELL: "Y_AXIS_WELL",
};
