(ns metabase.app-db.snapshot-test-util.generate
  "Writes the checked-in snapshots that [[metabase.app-db.snapshot-test-util/load-snapshot!]] reads.

  Separate from that namespace, rather than the other half of it, because generating needs the migration-test harness
  in [[metabase.app-db.schema-migrations-test.impl]] -- which itself loads snapshots. Keeping the write side here
  leaves the dependency running one way."
  (:require
   [clojure.java.io :as io]
   [clojure.string :as str]
   [metabase.app-db.connection :as mdb.connection]
   [metabase.app-db.custom-migrations :as custom-migrations]
   [metabase.app-db.custom-migrations.util :as custom-migrations.util]
   [metabase.app-db.schema-migrations-test.impl :as impl]
   [metabase.app-db.snapshot-test-util :as snapshot]
   [metabase.app-db.snapshot-test-util.dump :as dump]
   [metabase.app-db.snapshot-test-util.h2 :as snapshot.h2]
   [metabase.app-db.snapshot-test-util.mysql :as snapshot.mysql]
   [metabase.app-db.snapshot-test-util.postgres :as snapshot.postgres]
   [metabase.app-db.snapshot-test-util.server :as server]
   [metabase.app-db.test-util :as mdb.test-util]
   [metabase.driver.sql-jdbc.connection :as sql-jdbc.conn]
   [metabase.util :as u]
   [metabase.util.log :as log]))

(set! *warn-on-reflection* true)

(def ^:private flavor->dumper
  "Which [[metabase.app-db.snapshot-test-util.dump/Dumper]] produces each dialect's snapshot. The MariaDB flavors are
  dumped the same way MySQL is, differing only in the flags the dumper carries."
  {:h2                       snapshot.h2/dumper
   :postgres                 snapshot.postgres/dumper
   :mysql                    (snapshot.mysql/dumper :mysql)
   :mariadb                  (snapshot.mysql/dumper :mariadb)
   :mariadb-legacy-timestamp (snapshot.mysql/dumper :mariadb-legacy-timestamp)})

(defn- file-content [version flavor statements]
  (str "-- Generated by metabase.app-db.snapshot-test-util.generate/generate!. Do not edit by hand.\n"
       (format "-- Empty %s application DB migrated through %s.\n" (name flavor)
               (snapshot/through-changeset-id version))
       snapshot/statement-separator "\n"
       (str/join (str ";\n" snapshot/statement-separator "\n") statements)
       ";\n"))

(defn- migrate-and-dump
  "Migrate the empty DB `server` is running -- or an in-memory H2 one, when `server` is nil -- through the snapshot
  boundary and dump it."
  [flavor version server]
  (let [db-type     (if server (:db-type server) :h2)
        through     (snapshot/through-changeset-id version)
        data-source (mdb.test-util/->ClojureJDBCSpecDataSource
                     (if server
                       (sql-jdbc.conn/connection-details->spec db-type (:details server))
                       {:subprotocol "h2", :classname "org.h2.Driver"
                        :subname (format "mem:app_db_snapshot_%05d;DB_CLOSE_DELAY=-1" (rand-int 100000))}))]
    (with-open [conn (.getConnection ^javax.sql.DataSource data-source)]
      ;; the image was chosen for a flavor, but only the running server can confirm it is that flavor -- MariaDB is
      ;; reached as `:mysql`, and which MariaDB flavor it is depends on how it handles timestamps
      (let [detected (snapshot/flavor conn db-type)]
        (when-not (= detected flavor)
          (throw (ex-info "The server started for this flavor reports a different one"
                          {:flavor flavor, :detected detected}))))
      (log/info (u/format-color 'blue "Migrating empty %s app db through %s..." flavor through))
      ;; the same bindings [[impl/do-with-temp-empty-app-db]] installs, plus the sample content every test app DB is
      ;; set up without: custom migrations read the app DB through the dynamic var, and must not hand work to Quartz
      ;; against a DB that is about to vanish
      (binding [mdb.connection/*application-db*                (mdb.connection/application-db db-type data-source)
                custom-migrations.util/*allow-temp-scheduling* false
                custom-migrations/*create-sample-content*      false]
        (impl/run-migrations-in-range! conn ["v00.00-000" through]))
      {:flavor  flavor
       :content (file-content version flavor
                              (dump/dump-statements (flavor->dumper flavor) server conn))})))

(defn dump-snapshot!
  "Migrate an empty app DB of `flavor` through [[metabase.app-db.snapshot-test-util/through-changeset-id]] and dump
  it, returning `{:flavor ..., :content ...}`: the dialect it was taken as, and the text its snapshot file should
  hold. Writes nothing, so a test can ask what regenerating would produce without touching what is checked in.

  Everything but `:h2` runs against a server this starts itself, from the image
  [[metabase.app-db.snapshot-test-util.server]] pins for the flavor, so all it needs is a working `docker` -- no
  `MB_<DB>_TEST_*` and no server already running. That is what makes the file it produces the same here and in CI."
  ([flavor]
   (dump-snapshot! flavor snapshot/snapshot-version))
  ([flavor version]
   (if (= flavor :h2)
     (migrate-and-dump flavor version nil)
     (server/do-with-server! flavor #(migrate-and-dump flavor version %)))))

(defn generate!
  "Regenerate the checked-in snapshot for `flavor` and return the file written.

  `flavor` is the dialect the file is for, one of [[metabase.app-db.snapshot-test-util.server/flavors]] -- there is a
  file per flavor, so regenerating the MariaDB one means passing `:mariadb`, not the `:mysql` it is reached as. See
  [[dump-snapshot!]] for what this needs."
  ([flavor]
   (generate! flavor snapshot/snapshot-version))
  ([flavor version]
   (let [{:keys [flavor content]} (dump-snapshot! flavor version)
         file                     (io/file "test_resources" (snapshot/resource-path version flavor "sql"))]
     (io/make-parents file)
     (spit file content)
     (log/info (u/format-color 'green "Wrote %s" (str file)))
     file)))
