(ns metabase-enterprise.worker.core
  (:require
   [metabase-enterprise.worker.api]
   [metabase-enterprise.worker.canceling]
   [metabase-enterprise.worker.models.worker-run]
   [metabase-enterprise.worker.models.worker-run-cancelation]
   [metabase-enterprise.worker.server]
   [metabase-enterprise.worker.sync]
   [metabase-enterprise.worker.tracking]
   [potemkin :as p]))

(p/import-vars
 [metabase-enterprise.worker.api
  cancel!
  execute-transform!
  get-status
  run-remote?]
 [metabase-enterprise.worker.canceling
  chan-end-run!
  chan-signal-cancel!
  chan-start-run!
  chan-start-timeout-vthread!]
 [metabase-enterprise.worker.models.worker-run
  cancel-old-canceling-runs!
  cancel-run!
  fail-started-run!
  inactive-runs
  latest-runs
  model->work-type
  paged-executions
  reducible-active-remote-runs
  running-execution-for-work-id
  start-run!
  succeed-started-run!
  timeout-old-runs!
  timeout-run!]
 [metabase-enterprise.worker.models.worker-run-cancelation
  mark-cancel-started-run!
  reducible-canceled-local-runs
  delete-cancelation!
  delete-old-canceling-runs!]
 [metabase-enterprise.worker.server
  start!
  stop!]
 [metabase-enterprise.worker.sync
  sync-single-run!
  sync-worker-run-from-worker])
