import { waitFor } from "@testing-library/react";
import { useEffect } from "react";

import { renderWithProviders } from "__support__/ui";
import { SdkThemeProvider } from "embedding-sdk-bundle/components/private/SdkThemeProvider";
import { DEFAULT_FONT } from "embedding-sdk-bundle/config";
import { ensureMetabaseProviderPropsStore } from "embedding-sdk-shared/lib/ensure-metabase-provider-props-store";
import { getMetabaseSdkCssVariables } from "metabase/styled-components/theme/css-variables";
import { useMantineTheme } from "metabase/ui";
import { METABASE_DARK_THEME, METABASE_LIGHT_THEME } from "metabase/ui/colors";

const EXAMPLE_COLOR = "background_page-primary-inverse";

const LIGHT_EXAMPLE_VALUE = METABASE_LIGHT_THEME.colors[EXAMPLE_COLOR];
const DARK_EXAMPLE_VALUE = METABASE_DARK_THEME.colors[EXAMPLE_COLOR];

const THEME_CASES = [
  // V1 themes
  {
    themeName: "V1 light theme",
    theme: {
      colors: {
        background: "#ffffff",
        "text-primary": "#111111",
      },
    },
    expectedColor: LIGHT_EXAMPLE_VALUE,
    unexpectedColor: DARK_EXAMPLE_VALUE,
  },
  {
    themeName: "V1 dark theme",
    theme: {
      colors: {
        background: "#111111",
        "text-primary": "#ffffff",
      },
    },
    expectedColor: DARK_EXAMPLE_VALUE,
    unexpectedColor: LIGHT_EXAMPLE_VALUE,
  },

  // V2 themes
  {
    themeName: "V2 dark theme",
    theme: {
      version: 2 as const,
      colors: {
        "background_page-primary": "#111111",
        "text-primary": "#ffffff",
      },
    },
    expectedColor: DARK_EXAMPLE_VALUE,
    unexpectedColor: LIGHT_EXAMPLE_VALUE,
  },
];

const SdkCssVariablesTester = ({
  onChange,
}: {
  onChange: (cssVariables: string) => void;
}) => {
  const theme = useMantineTheme();

  useEffect(() => {
    onChange(getMetabaseSdkCssVariables({ theme, font: DEFAULT_FONT }).styles);
  }, [onChange, theme]);

  return null;
};

const renderSdkThemeProvider = (
  theme: React.ComponentProps<typeof SdkThemeProvider>["theme"],
  onCssVariablesChange: (cssVariables: string) => void,
) =>
  renderWithProviders(
    <SdkThemeProvider theme={theme}>
      <div className="mb-wrapper">SDK content</div>
      <SdkCssVariablesTester onChange={onCssVariablesChange} />
    </SdkThemeProvider>,
  );

describe("SdkThemeProvider", () => {
  beforeEach(() => {
    ensureMetabaseProviderPropsStore().cleanup();
  });

  it.each(THEME_CASES)(
    "$themeName base color variables are color scheme dependent",
    async ({ theme, expectedColor, unexpectedColor }) => {
      const handleCssVariablesChange = jest.fn();

      renderSdkThemeProvider(theme, handleCssVariablesChange);

      await waitFor(() => {
        const cssVariableKey = `--mb-color-${EXAMPLE_COLOR}`;
        const cssVariables = handleCssVariablesChange.mock.lastCall?.[0] ?? "";

        // This CSS variable is generated by createColorVars from the selected base
        // Metabase theme. Their light and dark mode values differ, so we can verify which
        // color scheme `getMetabaseSdkCssVariables` chose from the resolved palette.
        expect(cssVariables).toContain(`${cssVariableKey}: ${expectedColor}`);

        expect(cssVariables).not.toContain(
          `${cssVariableKey}: ${unexpectedColor}`,
        );
      });
    },
  );
});
