import type { TestCase } from "./matrix-helpers";

export const matrix: TestCase[] = [
  {
    arity: "single",
    type: "search",
    adminType: "search",
    operator: "Is",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "search",
    operator: "Is",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "search",
    operator: "Is",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "search",
    operator: "Is",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "search",
    operator: "Is",
    source: "custom",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "search",
    operator: "Is",
    source: "custom",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "search",
    operator: "Contains",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "search",
    operator: "Contains",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "search",
    operator: "Contains",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "search",
    operator: "Contains",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "search",
    operator: "Contains",
    source: "custom",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "search",
    operator: "Contains",
    source: "custom",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "list",
    operator: "Is",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "list",
    operator: "Is",
    source: "connected",
    results: "small",
    component: "list-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "list",
    operator: "Is",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "list",
    operator: "Is",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "list",
    operator: "Is",
    source: "custom",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "list",
    operator: "Is",
    source: "custom",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "list",
    operator: "Contains",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "list",
    operator: "Contains",
    source: "connected",
    results: "small",
    component: "list-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "list",
    operator: "Contains",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "list",
    operator: "Contains",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "list",
    operator: "Contains",
    source: "custom",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "list",
    operator: "Contains",
    source: "custom",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "plain",
    operator: "Is",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "plain",
    operator: "Is",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "plain",
    operator: "Is",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "plain",
    operator: "Is",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "plain",
    operator: "Is",
    source: "custom",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "plain",
    operator: "Is",
    source: "custom",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "plain",
    operator: "Contains",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "plain",
    operator: "Contains",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "plain",
    operator: "Contains",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "plain",
    operator: "Contains",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "plain",
    operator: "Contains",
    source: "custom",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "search",
    adminType: "plain",
    operator: "Contains",
    source: "custom",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "search",
    operator: "Is",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "search",
    operator: "Is",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "search",
    operator: "Is",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "search",
    operator: "Is",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "search",
    operator: "Is",
    source: "custom",
    results: "large",
    component: "list-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "search",
    operator: "Is",
    source: "custom",
    results: "small",
    component: "list-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "search",
    operator: "Contains",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "search",
    operator: "Contains",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "search",
    operator: "Contains",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "search",
    operator: "Contains",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "search",
    operator: "Contains",
    source: "custom",
    results: "large",
    component: "list-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "search",
    operator: "Contains",
    source: "custom",
    results: "small",
    component: "list-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "list",
    operator: "Is",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "list",
    operator: "Is",
    source: "connected",
    results: "small",
    component: "list-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "list",
    operator: "Is",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "list",
    operator: "Is",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "list",
    operator: "Is",
    source: "custom",
    results: "large",
    component: "list-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "list",
    operator: "Is",
    source: "custom",
    results: "small",
    component: "list-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "list",
    operator: "Contains",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "list",
    operator: "Contains",
    source: "connected",
    results: "small",
    component: "list-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "list",
    operator: "Contains",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "list",
    operator: "Contains",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "list",
    operator: "Contains",
    source: "custom",
    results: "large",
    component: "list-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "list",
    operator: "Contains",
    source: "custom",
    results: "small",
    component: "list-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "plain",
    operator: "Is",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "plain",
    operator: "Is",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "plain",
    operator: "Is",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "plain",
    operator: "Is",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "plain",
    operator: "Is",
    source: "custom",
    results: "large",
    component: "list-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "plain",
    operator: "Is",
    source: "custom",
    results: "small",
    component: "list-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "plain",
    operator: "Contains",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "plain",
    operator: "Contains",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "plain",
    operator: "Contains",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "plain",
    operator: "Contains",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "plain",
    operator: "Contains",
    source: "custom",
    results: "large",
    component: "list-field",
  },
  {
    arity: "single",
    type: "dropdown",
    adminType: "plain",
    operator: "Contains",
    source: "custom",
    results: "small",
    component: "list-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "search",
    operator: "Is",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "search",
    operator: "Is",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "search",
    operator: "Is",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "search",
    operator: "Is",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "search",
    operator: "Is",
    source: "custom",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "search",
    operator: "Is",
    source: "custom",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "search",
    operator: "Contains",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "search",
    operator: "Contains",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "search",
    operator: "Contains",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "search",
    operator: "Contains",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "search",
    operator: "Contains",
    source: "custom",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "search",
    operator: "Contains",
    source: "custom",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "list",
    operator: "Is",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "list",
    operator: "Is",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "list",
    operator: "Is",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "list",
    operator: "Is",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "list",
    operator: "Is",
    source: "custom",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "list",
    operator: "Is",
    source: "custom",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "list",
    operator: "Contains",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "list",
    operator: "Contains",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "list",
    operator: "Contains",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "list",
    operator: "Contains",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "list",
    operator: "Contains",
    source: "custom",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "list",
    operator: "Contains",
    source: "custom",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "plain",
    operator: "Is",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "plain",
    operator: "Is",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "plain",
    operator: "Is",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "plain",
    operator: "Is",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "plain",
    operator: "Is",
    source: "custom",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "plain",
    operator: "Is",
    source: "custom",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "plain",
    operator: "Contains",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "plain",
    operator: "Contains",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "plain",
    operator: "Contains",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "plain",
    operator: "Contains",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "plain",
    operator: "Contains",
    source: "custom",
    results: "large",
    component: "token-field",
  },
  {
    arity: "single",
    type: "plain",
    adminType: "plain",
    operator: "Contains",
    source: "custom",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "search",
    operator: "Is",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "search",
    operator: "Is",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "search",
    operator: "Is",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "search",
    operator: "Is",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "search",
    operator: "Is",
    source: "custom",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "search",
    operator: "Is",
    source: "custom",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "search",
    operator: "Contains",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "search",
    operator: "Contains",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "search",
    operator: "Contains",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "search",
    operator: "Contains",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "search",
    operator: "Contains",
    source: "custom",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "search",
    operator: "Contains",
    source: "custom",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "list",
    operator: "Is",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "list",
    operator: "Is",
    source: "connected",
    results: "small",
    component: "list-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "list",
    operator: "Is",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "list",
    operator: "Is",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "list",
    operator: "Is",
    source: "custom",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "list",
    operator: "Is",
    source: "custom",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "list",
    operator: "Contains",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "list",
    operator: "Contains",
    source: "connected",
    results: "small",
    component: "list-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "list",
    operator: "Contains",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "list",
    operator: "Contains",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "list",
    operator: "Contains",
    source: "custom",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "list",
    operator: "Contains",
    source: "custom",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "plain",
    operator: "Is",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "plain",
    operator: "Is",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "plain",
    operator: "Is",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "plain",
    operator: "Is",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "plain",
    operator: "Is",
    source: "custom",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "plain",
    operator: "Is",
    source: "custom",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "plain",
    operator: "Contains",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "plain",
    operator: "Contains",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "plain",
    operator: "Contains",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "plain",
    operator: "Contains",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "plain",
    operator: "Contains",
    source: "custom",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "search",
    adminType: "plain",
    operator: "Contains",
    source: "custom",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "search",
    operator: "Is",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "search",
    operator: "Is",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "search",
    operator: "Is",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "search",
    operator: "Is",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "search",
    operator: "Is",
    source: "custom",
    results: "large",
    component: "list-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "search",
    operator: "Is",
    source: "custom",
    results: "small",
    component: "list-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "search",
    operator: "Contains",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "search",
    operator: "Contains",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "search",
    operator: "Contains",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "search",
    operator: "Contains",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "search",
    operator: "Contains",
    source: "custom",
    results: "large",
    component: "list-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "search",
    operator: "Contains",
    source: "custom",
    results: "small",
    component: "list-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "list",
    operator: "Is",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "list",
    operator: "Is",
    source: "connected",
    results: "small",
    component: "list-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "list",
    operator: "Is",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "list",
    operator: "Is",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "list",
    operator: "Is",
    source: "custom",
    results: "large",
    component: "list-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "list",
    operator: "Is",
    source: "custom",
    results: "small",
    component: "list-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "list",
    operator: "Contains",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "list",
    operator: "Contains",
    source: "connected",
    results: "small",
    component: "list-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "list",
    operator: "Contains",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "list",
    operator: "Contains",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "list",
    operator: "Contains",
    source: "custom",
    results: "large",
    component: "list-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "list",
    operator: "Contains",
    source: "custom",
    results: "small",
    component: "list-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "plain",
    operator: "Is",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "plain",
    operator: "Is",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "plain",
    operator: "Is",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "plain",
    operator: "Is",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "plain",
    operator: "Is",
    source: "custom",
    results: "large",
    component: "list-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "plain",
    operator: "Is",
    source: "custom",
    results: "small",
    component: "list-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "plain",
    operator: "Contains",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "plain",
    operator: "Contains",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "plain",
    operator: "Contains",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "plain",
    operator: "Contains",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "plain",
    operator: "Contains",
    source: "custom",
    results: "large",
    component: "list-field",
  },
  {
    arity: "multi",
    type: "dropdown",
    adminType: "plain",
    operator: "Contains",
    source: "custom",
    results: "small",
    component: "list-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "search",
    operator: "Is",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "search",
    operator: "Is",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "search",
    operator: "Is",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "search",
    operator: "Is",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "search",
    operator: "Is",
    source: "custom",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "search",
    operator: "Is",
    source: "custom",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "search",
    operator: "Contains",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "search",
    operator: "Contains",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "search",
    operator: "Contains",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "search",
    operator: "Contains",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "search",
    operator: "Contains",
    source: "custom",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "search",
    operator: "Contains",
    source: "custom",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "list",
    operator: "Is",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "list",
    operator: "Is",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "list",
    operator: "Is",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "list",
    operator: "Is",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "list",
    operator: "Is",
    source: "custom",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "list",
    operator: "Is",
    source: "custom",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "list",
    operator: "Contains",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "list",
    operator: "Contains",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "list",
    operator: "Contains",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "list",
    operator: "Contains",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "list",
    operator: "Contains",
    source: "custom",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "list",
    operator: "Contains",
    source: "custom",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "plain",
    operator: "Is",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "plain",
    operator: "Is",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "plain",
    operator: "Is",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "plain",
    operator: "Is",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "plain",
    operator: "Is",
    source: "custom",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "plain",
    operator: "Is",
    source: "custom",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "plain",
    operator: "Contains",
    source: "connected",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "plain",
    operator: "Contains",
    source: "connected",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "plain",
    operator: "Contains",
    source: "card",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "plain",
    operator: "Contains",
    source: "card",
    results: "small",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "plain",
    operator: "Contains",
    source: "custom",
    results: "large",
    component: "token-field",
  },
  {
    arity: "multi",
    type: "plain",
    adminType: "plain",
    operator: "Contains",
    source: "custom",
    results: "small",
    component: "token-field",
  },
];
