#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn precommit

# Run the linter
./bin/quick_lint.bb

# Run the whitespace linter
./bin/whitespace_lint.sh

# Run the formatter
./bin/cljfmt.sh

./hooks/pre-commit.nocommit