#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn precommit

# Run the linter
./bin/quick_lint.bb

# Run the whitespace linter
./bin/whitespace_lint_staged.sh

# Run the formatter
./bin/cljfmt_staged.sh

./hooks/pre-commit.nocommit