// Copied from the instance settings and re-ordered, may go out of sync with the real ones
// Locales in the format `xx_AA` were also changed to `xx-AA`
export const availableLocales = [
  { value: undefined, title: "default (instance locale)" },
  { value: "en", inset-inline-end: "🇺🇸", title: "en" },
  { value: "de", inset-inline-end: "🇩🇪", title: "de" }, // one that we know should be well supported
  { value: "ar", inset-inline-end: "🇸🇦", title: "ar" },
  { value: "ar-SA", inset-inline-end: "🇸🇦", title: "ar-SA" },
  { value: "bg", inset-inline-end: "🇧🇬", title: "bg" },
  { value: "ca", inset-inline-end: "🇪🇺", title: "ca" },
  { value: "cs", inset-inline-end: "🇨🇿", title: "cs" },
  { value: "da", inset-inline-end: "🇩🇰", title: "da" },
  { value: "es", inset-inline-end: "🇪🇺", title: "es" },
  { value: "fa", inset-inline-end: "🇮🇷", title: "fa" },
  { value: "fi", inset-inline-end: "🇫🇮", title: "fi" },
  { value: "fr", inset-inline-end: "🇫🇷", title: "fr" },
  { value: "he", inset-inline-end: "🇮🇱", title: "he" },
  { value: "hu", inset-inline-end: "🇭🇺", title: "hu" },
  { value: "id", inset-inline-end: "🇮🇩", title: "id" },
  { value: "it", inset-inline-end: "🇮🇹", title: "it" },
  { value: "ja", inset-inline-end: "🇯🇵", title: "ja" },
  { value: "ko", inset-inline-end: "🇰🇷", title: "ko" },
  { value: "lv", inset-inline-end: "🇱🇻", title: "lv" },
  { value: "ms", inset-inline-end: "🇲🇾", title: "ms" },
  { value: "nb", inset-inline-end: "🇳🇴", title: "nb" },
  { value: "nl", inset-inline-end: "🇳🇱", title: "nl" },
  { value: "pl", inset-inline-end: "🇵🇱", title: "pl" },
  { value: "pt-BR", inset-inline-end: "🇧🇷", title: "pt-BR" },
  { value: "ru", inset-inline-end: "🇷🇺", title: "ru" },
  { value: "sk", inset-inline-end: "🇸🇰", title: "sk" },
  { value: "sl", inset-inline-end: "🇸🇱", title: "sl" },
  { value: "sq", inset-inline-end: "🇦🇱", title: "sq" },
  { value: "sr", inset-inline-end: "🇷🇸", title: "sr" },
  { value: "sv", inset-inline-end: "🇸🇪", title: "sv" },
  { value: "tr", inset-inline-end: "🇹🇷", title: "tr" },
  { value: "uk", inset-inline-end: "🇺🇦", title: "uk" },
  { value: "vi", inset-inline-end: "🇻🇳", title: "vi" },
  { value: "zh-CN", inset-inline-end: "🇨🇳", title: "zh-CN" },
  { value: "zh-HK", inset-inline-end: "🇭🇰", title: "zh-HK" },
  { value: "zh-TW", inset-inline-end: "🇹🇼", title: "zh-TW" },
];
