#!/usr/bin/env node
/**
 * Builds the continuous-dispatch queue: every unported Cypress scenario spec,
 * classified by size and gating tags, sorted for dispatch (big specs first so
 * they never become tail latency; container-gated specs flagged).
 *
 * Usage: node scripts/build-queue.mjs   (from e2e-playwright/)
 * Reads  PORTED.txt (one source-spec path per line, # comments ok)
 * Writes QUEUE.md (human) — the orchestrator dispatches from the top.
 */
import { execSync } from "child_process";
import fs from "fs";
import path from "path";

const ROOT = path.resolve(import.meta.dirname, "../..");
const SCENARIOS = path.join(ROOT, "e2e/test/scenarios");

const ported = new Set(
  fs
    .readFileSync(path.resolve(import.meta.dirname, "../PORTED.txt"), "utf8")
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith("#")),
);

const files = execSync(
  `find ${SCENARIOS} -name "*.cy.spec.*" -type f | sort`,
  { encoding: "utf8" },
)
  .trim()
  .split("\n");

const rows = [];
for (const file of files) {
  const rel = path.relative(SCENARIOS, file);
  if (ported.has(rel)) continue;
  const content = fs.readFileSync(file, "utf8");
  const lines = content.split("\n").length;
  // Tags are per-DESCRIBE, but a whole-file keyword scan cannot see that. A
  // spec where only one of three describes is @external looks identical to one
  // where all three are, and an agent that gates the file then silently skips
  // the ungated tests — ported, green, and not executing. That cost 9 of 11
  // tests on dashboard-filters-source before the gate-off control caught it
  // (FINDINGS #121). So for describe-level tags, report the coverage as n/N.
  // Count only TOP-LEVEL describes (column 0). @cypress/grep propagates suite
  // tags DOWNWARD, so a nested describe inherits its parent's tags — counting
  // nested ones as siblings produced false "1/6"/"3/6" figures that sent two
  // agents in the wrong direction (FINDINGS #129 neighbours). A tag on the sole
  // top-level describe means the whole file is gated.
  const describeCount = (content.match(/^describe(?:\.\w+)?\(/gm) || []).length;
  const taggedDescribes = (tag) =>
    (content.match(new RegExp(`\\{[^}]*tags:[^}]*${tag}`, "g")) || []).length;

  const tags = [];
  const scoped = (tag, label) => {
    if (!new RegExp(tag).test(content)) return;
    const n = taggedDescribes(tag);
    // n === 0 means the tag appears somewhere other than a describe's tags
    // option (a comment, a test-level tag, a helper name) — still worth
    // flagging, but explicitly not a describe-level gate.
    tags.push(
      n > 0 && describeCount > 0 && n < describeCount
        ? `${label}(${n}/${describeCount} describes)`
        : label,
    );
  };

  scoped("@external", "external");
  scoped("@mongo", "mongo");
  scoped("@OSS", "oss");
  if (/@skip/.test(content)) tags.push("has-skips");
  if (/snowplow/i.test(content)) tags.push("snowplow");
  if (/setupSMTP|getInbox|maildev/i.test(content)) tags.push("email");
  if (/webhook/i.test(content)) tags.push("webhook");
  if (/activateToken/.test(content)) tags.push("token");
  rows.push({ rel, lines, tags });
}

// A port that was finished but never committed is invisible to PORTED.txt, so
// the queue happily re-offers it and an agent redoes work (or overwrites work
// that git cannot recover, because it was never tracked). This happened twice
// on 2026-07-20. Ports name their source in the file header, so cross-check the
// queue against what is actually on disk and shout about any overlap.
const portedOnDisk = new Set();
const TESTS = path.resolve(import.meta.dirname, "../tests");
for (const f of fs.readdirSync(TESTS)) {
  if (!f.endsWith(".spec.ts")) continue;
  const head = fs.readFileSync(path.join(TESTS, f), "utf8").slice(0, 4000);
  for (const m of head.matchAll(
    /e2e\/test(?:-component)?\/scenarios\/([A-Za-z0-9_./-]+\.cy\.spec\.[jt]s)/g,
  )) {
    portedOnDisk.add(m[1]);
  }
}

const alreadyPorted = rows.filter((r) => portedOnDisk.has(r.rel));
if (alreadyPorted.length > 0) {
  console.error(
    `\n⚠️  ${alreadyPorted.length} queued spec(s) ALREADY have a port on disk but are` +
      ` missing from PORTED.txt.\n   Either an agent is writing them right now, or a` +
      ` finished port was never committed.\n   Do NOT dispatch these. Once the port is` +
      ` done, commit it and add it to PORTED.txt:\n` +
      alreadyPorted.map((r) => `     ${r.rel}`).join("\n") +
      "\n",
  );
}

rows.sort((a, b) => b.lines - a.lines);

const out = [
  "# Dispatch queue (generated by scripts/build-queue.mjs)",
  "",
  `${rows.length} specs remaining, ${rows.reduce((s, r) => s + r.lines, 0)} lines total.`,
  "Dispatch from the top (largest first — they must never be tail latency).",
  "",
  "> ⚠️ **The gates column is a HINT, not a specification.** It is a keyword scan.",
  "> It cannot see a tag on an individual `it` (which reads here as if the whole",
  "> file were gated), and it cannot tell a container dependency from a spec that",
  "> merely mentions the word. Tags have been found wrong in six ways — missing,",
  "> stale, over-broad, red-herring, dead-setup, and systematically absent (~20 of",
  "> ~50 `*-writable` specs carry no `@external` at all, FINDINGS #123).",
  ">",
  "> **Read the spec's `beforeEach` to see what it actually restores, and treat the",
  "> gate-OFF control as the only trustworthy signal** — a green run with the gate",
  "> off is either real coverage or silent skipping, and only the executed-vs-",
  "> skipped counts distinguish them.",
  "",
  "| lines | spec | gates |",
  "|---|---|---|",
  ...rows.map((r) => `| ${r.lines} | ${r.rel} | ${r.tags.join(", ")} |`),
  "",
];
fs.writeFileSync(path.resolve(import.meta.dirname, "../QUEUE.md"), out.join("\n"));
console.log(`${rows.length} specs queued (${rows.reduce((s, r) => s + r.lines, 0)} lines). Top 5:`);
for (const r of rows.slice(0, 5)) console.log(`  ${r.lines}  ${r.rel}  [${r.tags}]`);
