// -*- mode: javascript; -*-
//
// ************************************************************
// * WARNING: DO NOT EDIT VERSION.JS DIRECTLY!               *
// * VERSION.JS IS AUTOMATICALLY GENERATED BY A PERL SCRIPT. *
// * INSTEAD, EDIT VERSION.JS.TEMPLATE.                      *
// ************************************************************

'use strict';

!function() {
    this.METABASE_VERSION = "[UNDEFINED]"; // this is a placeholder; run ./build_uberjare generate_version_info to add an appropriate value
}();
