(ns metabase-enterprise.metabot-v3.agent.tools-test
  (:require
   [clojure.test :refer :all]
   [metabase-enterprise.metabot-v3.agent.tools :as agent-tools]))

(deftest all-tools-test
  (testing "all-tools registry contains expected tools"
    (is (map? agent-tools/all-tools))
    (is (contains? agent-tools/all-tools "search"))
    (is (contains? agent-tools/all-tools "query_metric"))
    (is (contains? agent-tools/all-tools "query_model"))
    (is (contains? agent-tools/all-tools "get_field_values"))
    (is (contains? agent-tools/all-tools "get_entity_details"))
    (is (contains? agent-tools/all-tools "get_metric_details"))
    (is (contains? agent-tools/all-tools "get_field_stats"))
    (is (contains? agent-tools/all-tools "show_results_to_user"))
    (is (contains? agent-tools/all-tools "find_outliers"))
    (is (contains? agent-tools/all-tools "generate_insights"))
    (is (contains? agent-tools/all-tools "create_dashboard_subscription"))
    (is (contains? agent-tools/all-tools "get_transform_details"))
    (is (contains? agent-tools/all-tools "invite_user"))
    ;; New tools from AI service parity
    (is (contains? agent-tools/all-tools "todo_write"))
    (is (contains? agent-tools/all-tools "todo_read"))
    (is (contains? agent-tools/all-tools "navigate_user"))
    (is (contains? agent-tools/all-tools "list_snippets"))
    (is (contains? agent-tools/all-tools "get_snippet_details"))
    (is (contains? agent-tools/all-tools "ask_for_sql_clarification"))
    (is (contains? agent-tools/all-tools "write_transform_sql"))
    (is (contains? agent-tools/all-tools "write_transform_python"))
    (is (contains? agent-tools/all-tools "create_autogenerated_dashboard")))

  (testing "all tool values are vars"
    (doseq [[tool-name tool-var] agent-tools/all-tools]
      (is (var? tool-var) (str "Tool " tool-name " should be a var"))))

  (testing "all tool vars have metadata"
    (doseq [[tool-name tool-var] agent-tools/all-tools]
      (is (some? (meta tool-var)) (str "Tool " tool-name " should have metadata"))
      (is (some? (:name (meta tool-var))) (str "Tool " tool-name " should have :name in metadata")))))

(deftest filter-by-capabilities-test
  (testing "returns tools with no capability requirements when capabilities empty"
    (let [tool-names ["search" "query_metric"]
          capabilities #{}
          result (agent-tools/filter-by-capabilities tool-names capabilities)]
      ;; search and query_metric have no capability requirements
      (is (= tool-names result))))

  (testing "filters out tools that require missing capabilities"
    (let [tool-names ["search" "navigate_user" "create_autogenerated_dashboard"]
          capabilities #{}
          result (agent-tools/filter-by-capabilities tool-names capabilities)]
      ;; search has no requirements, navigate_user requires :frontend-navigate-user-v1
      ;; create_autogenerated_dashboard requires :automagic-dashboards
      (is (= ["search"] result))))

  (testing "includes tools when capabilities are provided"
    (let [tool-names ["search" "navigate_user" "create_chart"]
          capabilities #{:frontend-navigate-user-v1}
          result (agent-tools/filter-by-capabilities tool-names capabilities)]
      ;; search has no requirements, navigate_user and create_chart need :frontend-navigate-user-v1
      (is (= ["search" "navigate_user" "create_chart"] result))))

  (testing "filters transform tools by capabilities"
    (let [tool-names ["write_transform_sql" "write_transform_python" "search"]
          ;; write_transform_sql needs :feature-transforms and :permission-write-transforms
          ;; write_transform_python also needs :feature-transforms-python
          capabilities #{:feature-transforms :permission-write-transforms}
          result (agent-tools/filter-by-capabilities tool-names capabilities)]
      ;; Only search and write_transform_sql should be included
      (is (= ["write_transform_sql" "search"] result))))

  (testing "includes write_transform_python when all capabilities present"
    (let [tool-names ["write_transform_python" "search"]
          capabilities #{:feature-transforms :feature-transforms-python :permission-write-transforms}
          result (agent-tools/filter-by-capabilities tool-names capabilities)]
      (is (= ["write_transform_python" "search"] result))))

  (testing "filters snippet tools by capabilities"
    (let [tool-names ["list_snippets" "get_snippet_details" "search"]
          capabilities #{}
          result (agent-tools/filter-by-capabilities tool-names capabilities)]
      ;; Snippet tools require :feature-snippets
      (is (= ["search"] result))))

  (testing "includes snippet tools when capability present"
    (let [tool-names ["list_snippets" "get_snippet_details" "search"]
          capabilities #{:feature-snippets}
          result (agent-tools/filter-by-capabilities tool-names capabilities)]
      (is (= ["list_snippets" "get_snippet_details" "search"] result)))))

(deftest get-tools-for-profile-test
  (testing "returns tools for embedding profile"
    (let [tools (agent-tools/get-tools-for-profile :embedding #{})]
      (is (map? tools))
      (is (contains? tools "search"))
      (is (contains? tools "query_metric"))
      (is (contains? tools "query_model"))
      (is (contains? tools "get_field_values"))
      (is (contains? tools "show_results_to_user"))))

  (testing "returns tools for internal profile"
    (let [tools (agent-tools/get-tools-for-profile :internal #{})]
      (is (map? tools))
      ;; Should have more tools than embedding
      (is (> (count tools) 5))
      (is (contains? tools "search"))
      (is (contains? tools "find_outliers"))
      (is (contains? tools "generate_insights"))
      (is (contains? tools "invite_user"))))

  (testing "returns tools for transforms-codegen profile"
    (let [tools (agent-tools/get-tools-for-profile :transforms-codegen #{})]
      (is (map? tools))
      (is (contains? tools "search"))
      (is (contains? tools "get_transform_details"))
      (is (contains? tools "get_entity_details"))
      (is (contains? tools "get_field_stats"))
      ;; New tools for transforms profile
      (is (contains? tools "todo_write"))
      (is (contains? tools "todo_read"))))

  (testing "returns tools for sql-only profile"
    (let [tools (agent-tools/get-tools-for-profile :sql-only #{})]
      (is (map? tools))
      (is (contains? tools "search"))
      (is (contains? tools "create_sql_query"))
      (is (contains? tools "ask_for_sql_clarification"))))

  (testing "returns tools for nlq-only profile"
    (let [tools (agent-tools/get-tools-for-profile :nlq-only #{})]
      (is (map? tools))
      (is (contains? tools "search"))
      (is (contains? tools "query_metric"))
      (is (contains? tools "query_model"))))

  (testing "returns empty map for unknown profile"
    (let [tools (agent-tools/get-tools-for-profile :unknown-profile #{})]
      (is (map? tools))
      (is (empty? tools))))

  (testing "returned tools have correct structure"
    (let [tools (agent-tools/get-tools-for-profile :embedding #{})]
      (doseq [[tool-name tool-var] tools]
        (is (var? tool-var))
        (is (string? tool-name))))))

(deftest search-tool-test
  (testing "search-tool exists and is a function"
    (let [tool-var (agent-tools/all-tools "search")
          tool-meta (meta tool-var)]
      (is (some? tool-meta))
      (is (some? (:name tool-meta)))))

  (testing "search-tool is callable"
    ;; This is a structural test - actual tool execution requires DB setup
    (let [tool-fn @(agent-tools/all-tools "search")]
      ;; Just verify the function exists and is callable
      (is (fn? tool-fn)))))

(deftest tool-wrapper-structure-test
  (testing "all tool wrappers are defined"
    ;; Verify that our tool wrappers exist - currently 22 tools
    (is (>= (count agent-tools/all-tools) 13))
    (is (every? fn? (map deref (vals agent-tools/all-tools)))))

  (testing "tool wrappers map to kebab-case handlers"
    ;; This verifies the pattern: LLM sends snake_case -> wrapper -> kebab-case handler
    ;; Structural verification only - actual calls require integration tests
    (is (>= (count agent-tools/all-tools) 13))))

;;; wrap-tools-with-state tests

(deftest state-dependent-tools-test
  (testing "state-dependent-tools set contains expected tools"
    (is (contains? @#'agent-tools/state-dependent-tools "show_results_to_user"))
    (is (contains? @#'agent-tools/state-dependent-tools "create_chart"))
    (is (contains? @#'agent-tools/state-dependent-tools "edit_chart"))
    (is (contains? @#'agent-tools/state-dependent-tools "edit_sql_query"))
    (is (contains? @#'agent-tools/state-dependent-tools "replace_sql_query"))
    ;; New state-dependent tools
    (is (contains? @#'agent-tools/state-dependent-tools "todo_write"))
    (is (contains? @#'agent-tools/state-dependent-tools "todo_read"))
    (is (contains? @#'agent-tools/state-dependent-tools "navigate_user"))
    (is (contains? @#'agent-tools/state-dependent-tools "write_transform_sql"))
    (is (contains? @#'agent-tools/state-dependent-tools "write_transform_python"))
    (is (contains? @#'agent-tools/state-dependent-tools "create_autogenerated_dashboard"))))

(deftest wrap-tools-with-state-test
  (testing "wraps state-dependent tools with state injection"
    (let [memory-atom (atom {:state {:queries {"q1" {:database 1}}
                                     :charts {"c1" {:query-id "q1"}}}})
          base-tools {"show_results_to_user" #'agent-tools/show-results-to-user-tool
                      "search" #'agent-tools/search-tool}
          wrapped-tools (agent-tools/wrap-tools-with-state base-tools memory-atom)]
      ;; State-dependent tool should be wrapped as a map
      (is (map? (get wrapped-tools "show_results_to_user")))
      (is (contains? (get wrapped-tools "show_results_to_user") :fn))
      (is (contains? (get wrapped-tools "show_results_to_user") :doc))
      (is (contains? (get wrapped-tools "show_results_to_user") :schema))
      (is (contains? (get wrapped-tools "show_results_to_user") :system-instructions))
      ;; Non-state-dependent tool should remain as var
      (is (var? (get wrapped-tools "search")))))

  (testing "wrapped tools preserve original metadata"
    (let [memory-atom (atom {:state {:queries {} :charts {}}})
          base-tools {"create_chart" #'agent-tools/create-chart-tool}
          wrapped-tools (agent-tools/wrap-tools-with-state base-tools memory-atom)
          wrapped-tool (get wrapped-tools "create_chart")
          original-meta (meta #'agent-tools/create-chart-tool)]
      (is (= (:doc original-meta) (:doc wrapped-tool)))
      (is (= (:schema original-meta) (:schema wrapped-tool)))))

  (def ^{:doc "Test tool"
         :schema [:=> [:cat [:map]] :any]
         :system-instructions "Follow the rules."}
    test-stateful-tool
    (fn [_] nil))

  (deftest wrap-tools-with-state-preserves-system-instructions-test
    (testing "preserves system instructions for wrapped tools"
      (let [memory-atom (atom {:state {:queries {} :charts {}}})
            base-tools {"show_results_to_user" #'test-stateful-tool}
            wrapped-tools (agent-tools/wrap-tools-with-state base-tools memory-atom)]
        (is (= "Follow the rules."
               (get-in wrapped-tools ["show_results_to_user" :system-instructions]))))))

  (testing "wrapped function receives augmented args with state"
    (let [received-args (atom nil)
          ;; Create a mock tool function that captures its args
          mock-fn (fn [args] (reset! received-args args) {:output "ok"})
          memory-atom (atom {:state {:queries {"test-query" {:db 1}}
                                     :charts {"test-chart" {:type :bar}}}})
          ;; Manually wrap it using the same logic as wrap-tools-with-state
          wrapped-fn (fn [args]
                       (let [memory @memory-atom
                             state (:state memory)]
                         (mock-fn (assoc args
                                         :queries_state (get state :queries {})
                                         :charts_state (get state :charts {})))))]
      ;; Call the wrapped function
      (wrapped-fn {:query_id "test-query" :chart_type "bar"})
      ;; Verify the function received augmented args
      (is (some? @received-args))
      (is (= {"test-query" {:db 1}} (:queries_state @received-args)))
      (is (= {"test-chart" {:type :bar}} (:charts_state @received-args)))
      (is (= "test-query" (:query_id @received-args)))))

  (testing "non-state-dependent tools are not modified"
    (let [memory-atom (atom {:state {:queries {"q1" {:db 1}} :charts {}}})
          base-tools {"search" #'agent-tools/search-tool
                      "query_model" #'agent-tools/query-model-tool}
          wrapped-tools (agent-tools/wrap-tools-with-state base-tools memory-atom)]
      ;; These should remain as vars, not wrapped maps
      (is (var? (get wrapped-tools "search")))
      (is (var? (get wrapped-tools "query_model"))))))

(deftest tool-schemas-accept-state-keys-test
  (testing "create_chart schema accepts both queries_state and charts_state"
    (let [tool-var #'agent-tools/create-chart-tool
          {:keys [schema]} (meta tool-var)
          [_:=> [_:cat params] _out] schema]
      ;; The schema should allow charts_state even though create_chart doesn't use it
      ;; This is because wrap-tools-with-state injects both state keys
      (is (some #(= :charts_state (first %)) (rest params)))))

  (testing "edit_chart schema accepts both queries_state and charts_state"
    (let [tool-var #'agent-tools/edit-chart-tool
          {:keys [schema]} (meta tool-var)
          [_:=> [_:cat params] _out] schema]
      ;; The schema should allow queries_state even though edit_chart doesn't use it
      (is (some #(= :queries_state (first %)) (rest params)))))

  (testing "show_results_to_user schema accepts both queries_state and charts_state"
    (let [tool-var #'agent-tools/show-results-to-user-tool
          {:keys [schema]} (meta tool-var)
          [_:=> [_:cat params] _out] schema]
      ;; The schema should allow charts_state even though show_results_to_user doesn't use it
      (is (some #(= :charts_state (first %)) (rest params)))))

  (testing "edit_sql_query schema accepts queries_state and charts_state"
    (let [tool-var #'agent-tools/edit-sql-query-tool
          {:keys [schema]} (meta tool-var)
          [_:=> [_:cat params] _out] schema]
      (is (some #(= :queries_state (first %)) (rest params)))
      (is (some #(= :charts_state (first %)) (rest params)))))

  (testing "replace_sql_query schema accepts queries_state and charts_state"
    (let [tool-var #'agent-tools/replace-sql-query-tool
          {:keys [schema]} (meta tool-var)
          [_:=> [_:cat params] _out] schema]
      (is (some #(= :queries_state (first %)) (rest params)))
      (is (some #(= :charts_state (first %)) (rest params))))))
