import type { ReactNode } from "react";
import { Link } from "react-router";
import { t } from "ttag";

import { DateTime } from "metabase/common/components/DateTime";
import CS from "metabase/css/core/index.css";
import * as Urls from "metabase/lib/urls";
import { getUserName } from "metabase/lib/user";
import { Anchor, Box, Card, FixedSizeIcon, Group, Stack } from "metabase/ui";
import type { DependencyNode } from "metabase-types/api";

import {
  getNodeCreatedAt,
  getNodeCreatedBy,
  getNodeDescription,
  getNodeLastEditedAt,
  getNodeLastEditedBy,
  getNodeTransform,
} from "../../../../utils";
import S from "../ListSidebar.module.css";

type SidebarInfoSectionProps = {
  node: DependencyNode;
};

export function SidebarInfoSection({ node }: SidebarInfoSectionProps) {
  const description = getNodeDescription(node);
  const createdBy = getNodeCreatedBy(node);
  const createdAt = getNodeCreatedAt(node);
  const editedBy = getNodeLastEditedBy(node);
  const editedAt = getNodeLastEditedAt(node);
  const transform = getNodeTransform(node);

  if (
    description == null &&
    (createdAt == null || createdBy == null) &&
    (editedAt == null || editedBy == null) &&
    transform == null
  ) {
    return null;
  }

  return (
    <Card p={0} shadow="none" withBorder role="region" aria-label={t`Info`}>
      {description != null && (
        <InfoSection label={t`Description`}>
          {description.length > 0 ? (
            <Box className={CS.textWrap}>{description}</Box>
          ) : (
            <Box c="text-secondary">{t`No description`}</Box>
          )}
        </InfoSection>
      )}
      {createdBy != null && createdAt != null && (
        <InfoSection label={t`Created by`} date={createdAt}>
          <Box className={CS.textWrap}>{getUserName(createdBy)}</Box>
        </InfoSection>
      )}
      {editedBy != null && editedAt != null && (
        <InfoSection label={t`Last edited by`} date={editedAt}>
          <Box className={CS.textWrap}>{getUserName(editedBy)}</Box>
        </InfoSection>
      )}
      {transform != null && (
        <InfoSection label={t`Generated by`}>
          <Anchor
            component={Link}
            className={CS.textWrap}
            to={Urls.transform(transform.id)}
            target="_blank"
          >
            <Group gap="sm" wrap="nowrap">
              <FixedSizeIcon name="transform" />
              {transform.name}
            </Group>
          </Anchor>
        </InfoSection>
      )}
    </Card>
  );
}

type InfoSectionProps = {
  label: string;
  date?: string;
  children?: ReactNode;
};

function InfoSection({ label, date, children }: InfoSectionProps) {
  return (
    <Stack className={S.section} p="md" gap="xs">
      <Box className={CS.textWrap} c="text-secondary" fz="sm" lh="h5">
        {label}
      </Box>
      <Group lh="h4" justify="space-between" wrap="nowrap">
        {children}
        {date != null && (
          <Box c="text-secondary">
            <DateTime className={CS.textNoWrap} value={date} unit="day" />
          </Box>
        )}
      </Group>
    </Stack>
  );
}
