name: Block Master Branch PRs
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-source-branch:
    runs-on: ${{ vars.DEFAULT_RUNNER_KEY }}
    steps:
      - name: Block master branch PRs
        if: github.head_ref == 'master'
        run: |
          echo "PRs from `master` branches are not allowed, please use a new branch name for your PR."
          exit 1
