name: Block Master Branch PRs
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-source-branch:
    if: github.head_ref == 'master'
    runs-on: ${{ vars.SLIM_RUNNER_KEY }}
    timeout-minutes: 5
    steps:
      - name: Block master branch PRs
        run: |
          echo "PRs from \`master\` branches are not allowed, please use a new branch name for your PR."
          exit 1
