name: Check doc links

on:
  pull_request:
  workflow_dispatch:

jobs:
  link-checker:
    name: Check documentation links
    runs-on: ${{ vars.DEFAULT_RUNNER_KEY }}
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          sparse-checkout: |
            docs
            .lychee

      - name: Cache lychee
        uses: actions/cache@v3
        with:
          path: ~/.cache/lychee
          key: lychee-${{ runner.os }}-${{ hashFiles('.lychee/config.toml') }}

      - name: Run link checker
        id: link-check
        uses: lycheeverse/lychee-action@f613c4a64e50d792e0b31ec34bbcbba12263c6a6 # v2.3.0
        with:
          fail: true
          args: docs --config ./.lychee/config.toml --offline
          format: markdown
