name: Embedding SDK Labels Reminder

on:
  pull_request:
    types: [auto_merge_enabled, review_requested, labeled, unlabeled, synchronize]
    branches:
      - "master"
  merge_group:

jobs:
  should-run:
    uses: ./.github/workflows/util.should-run.yml
    with:
      any-of: frontend_embedding_sdk_package_sources

  embedding-sdk-package-no-release-notes-reminder:
    needs: [ should-run ]
    if: |
      !cancelled() &&
      (needs.should-run.outputs.changed == 'true')
    name: Embedding SDK package release-notes/no-release-notes label reminder
    runs-on: ${{ vars.DEFAULT_RUNNER_KEY }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
      - uses: jesusvasquez333/verify-pr-label-action@657d111bbbe13e22bbd55870f1813c699bde1401 # v1.4.0
        id: verify-release-notes-labels
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          valid-labels: 'release-notes, no-release-notes'
          disable-reviews: true
      - name: Comment on PR if label should be added
        if: ${{ always() }}
        uses: ./.github/actions/notify-pull-request
        with:
          remove-previous-comment: true
          add-new-comment: ${{ steps.verify-release-notes-labels.outcome == 'failure' }}
          message: "⚠️ Changes were made to the <b>Embedding SDK Package</b>. Review this PR and apply one of the following labels.<br><br>- <code>release-notes</code> — select if this PR must be included in the main Metabase changelog release notes.<br>- <code>no-release-notes</code> — select if this PR should not be included in the main Metabase changelog release notes."
          include-log: true
