name: Frontend Unit Test Stress Test Flake Fix

on:
  workflow_dispatch:
    inputs:
      spec:
        description: "Relative path of the target spec"
        type: string
        required: true
      burn_in:
        description: "Number of times to run the test (e.g. 20)"
        type: string
        required: true
      grep:
        description: "Grep and filter tests to run in isolation"
        type: string
        required: false

jobs:
  workflow-summary:
    name: Stress test inputs
    runs-on: ${{ vars.SLIM_RUNNER_KEY }}
    timeout-minutes: 5
    steps:
      - name: Generate workflow summary
        env:
          BRANCH: ${{ github.ref_name }}
          SPEC: ${{ inputs.spec }}
          BURN_IN: ${{ inputs.burn_in }}
          GREP: ${{ inputs.grep }}
          SENDER: ${{ github.event.sender.login }}
        run: |
          {
            echo '**Inputs:**'
            echo ''
            echo "- \`branch\`: $BRANCH"
            echo "- \`spec\`: $SPEC"
            echo "- \`burn_in\`: $BURN_IN"
            echo "- \`grep\`: \"$GREP\""
            echo ''
            echo "triggered by: @$SENDER"
          } >> "$GITHUB_STEP_SUMMARY"

  frontend-unit-test-stress-test-flake-fix:
    runs-on: ${{ vars.DEFAULT_RUNNER_KEY }}
    timeout-minutes: 60
    name: Stress test frontend unit test flake fix
    steps:
      - uses: actions/checkout@v6
      - name: Prepare front-end environment
        uses: ./.github/actions/prepare-frontend
      - name: Prepare back-end environment
        uses: ./.github/actions/prepare-backend
      - name: Build cljs
        run: bun run build:cljs
      - name: Stress-test ${{ github.event.inputs.spec }} ${{ github.event.inputs.burn_in }} times
        run: |
          for ((i=1; i<=BURN_IN; i++)); do
            if ! bun run jest --runInBand --ci --silent --no-cache \
              --testPathPatterns "${SPEC}" \
              --testNamePattern "${GREP}"; then
              echo "Failed after $i attempts" && break;
            fi
          done

        env:
          BURN_IN: ${{ github.event.inputs.burn_in }}
          SPEC: ${{ github.event.inputs.spec }}
          GREP: ${{ github.event.inputs.grep }}
