name: Loki Visual Regression Testing

on:
  workflow_call:
    inputs:
      skip:
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}-loki
  cancel-in-progress: true

jobs:
  visual-test:
    if: ${{ !inputs.skip }}
    runs-on: ${{ vars.DEFAULT_RUNNER_KEY }}
    timeout-minutes: 30
    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 2376:2376
        env:
          DOCKER_TLS_CERTDIR: /certs
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /tmp/docker-certs:/certs/client

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Prepare frontend environment
        uses: ./.github/actions/prepare-frontend

      - name: Prepare back-end environment
        uses: ./.github/actions/prepare-backend

      - name: Compile CLJS
        run: NODE_ENV=development bun run build-pure:cljs

      - name: Run Loki Visual Tests
        run: bun run test-visual:loki:ci

      - name: Generate Visual Report on Failure
        if: failure()
        run: bun run test-visual:loki-report

      - name: Upload Artifact
        id: artifact-upload-step
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: loki-report
          include-hidden-files: true
          path: .loki/
          if-no-files-found: ignore
