name: Update Release Log
run-name: Update Release Log ${{ inputs.version || github.ref_name }}

on:
  push:
    branches:
      - release-x.*
    tags:
      - v*
  workflow_dispatch:
    inputs:
      version:
        description: "Major Metabase version (e.g. 45, 52, 68)"
        type: number
        required: true
  workflow_call:
    inputs:
      version:
        description: "Major Metabase version (e.g. 45, 52, 68)"
        type: number # needs to be a number to pass variables
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  update-release-log:
    runs-on: ${{ vars.DEFAULT_RUNNER_KEY }}
    timeout-minutes: 5
    # don't run this workflow for forks
    if: ${{ github.event_name != 'push' || github.repository == 'metabase/metabase' }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@d979d5b3a71173a29b74b5b88418bfda9437d885 # v6.1.1
        with:
          role-to-assume: ${{ secrets.CI_RELEASE_IAM_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}
      - uses: actions/checkout@v6
        with:
          ref: master # this only works on master
          fetch-depth: 0 # we want all branches and tags
      - name: Prepare release scripts
        uses: ./.github/actions/prepare-release-scripts
      - name: Install tsx
        run: npm i -g tsx
      - name: Get version number
        id: get-version
        uses: actions/github-script@v9
        env:
          VERSION_INPUT: ${{ inputs.version }}
        with:
          script: | # js
            const { getMajorVersionFromRef } = require('${{ github.workspace }}/release/dist/index.cjs');

            console.log({ context });

            const version = process.env.VERSION_INPUT || getMajorVersionFromRef(context.payload.ref);

            console.log({ version });
            core.exportVariable('VERSION', version);
            core.setOutput('version', version);

      - name: generate release Log
        if: ${{ steps.get-version.outputs.version != '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cd release && tsx ./src/release-log-run.ts "$VERSION" > "v$VERSION.html"
      - name: upload release log to the web
        if: ${{ steps.get-version.outputs.version != '' }}
        run: |
          aws s3 cp \
          "release/v$VERSION.html" \
          "s3://${{ vars.AWS_S3_STATIC_BUCKET }}/release-log/v$VERSION.html"

      - name: Create cloudfront invalidation
        if: ${{ steps.get-version.outputs.version != '' }}
        run: |
          aws cloudfront create-invalidation \
          --distribution-id ${{ vars.AWS_CLOUDFRONT_STATIC_ID }} \
          --paths "/release-log/v$VERSION.html"
