name: Update Release Log
run-name: Update Release Log ${{ inputs.version || github.ref_name }}

on:
  push:
    branches:
      - release-x.*
    tags:
      - v*
      - latest-*
  workflow_dispatch:
    inputs:
      version:
        description: 'Major Metabase version (e.g. 45, 52, 68)'
        type: number
        required: true
  workflow_call:
    inputs:
      version:
        description: 'Major Metabase version (e.g. 45, 52, 68)'
        type: number # needs to be a number to pass variables
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  update-release-log:
    runs-on: ${{ vars.DEFAULT_RUNNER_KEY }}
    timeout-minutes: 5
    # don't run this workflow for forks
    if: ${{ github.event_name != 'push' || github.repository == 'metabase/metabase' }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4
        with:
          role-to-assume: ${{ secrets.CI_RELEASE_IAM_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}
      - uses: actions/checkout@v4
        with:
          ref: master # this only works on master
          fetch-depth: 0 # we want all branches and tags
      - name: Prepare release scripts
        uses: ./.github/actions/prepare-release-scripts
      - name: Install tsx
        run: npm i -g tsx
      - name: Get version number
        uses: actions/github-script@v7
        with:
          script: | # js
            const {
              getMajorVersionFromRef,
              getMajorVersion,
            } = require('${{ github.workspace }}/release/dist/index.cjs');

            console.log({ context });

            // if the version is explicitly set, use that
            if (context.payload?.inputs?.version) {
              core.exportVariable('VERSION', context.payload.inputs.version);
              return;
            }

            // otherwise, get the version from the release branch name
            const ref = context.payload.ref;
            const majorVersion = getMajorVersionFromRef(ref);

            console.log({ ref, majorVersion });
            core.exportVariable('VERSION', majorVersion);

      - name: generate release Log
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cd release && tsx ./src/release-log-run.ts $VERSION > v$VERSION.html
      - name: upload release log to the web
        run: |
          aws s3 cp \
          release/v$VERSION.html \
          s3://${{ vars.AWS_S3_STATIC_BUCKET }}/release-log/v$VERSION.html

      - name: Create cloudfront invalidation
        run: |
          aws cloudfront create-invalidation \
          --distribution-id ${{ vars.AWS_CLOUDFRONT_STATIC_ID }} \
          --paths "/release-log/v$VERSION.html"
