(ns metabase-enterprise.metabot-analytics.api
  "`/api/ee/metabot-analytics/` endpoints for AI/Metabot usage analytics.
  These only work if you have a premium token with the `:audit-app` feature.

  Handlers stay thin: auth + param coercion + delegation. The HoneySQL and
  response assembly live in `metabase-enterprise.metabot-analytics.conversations`."
  (:require
   [metabase-enterprise.metabot-analytics.conversations :as analytics.conversations]
   [metabase-enterprise.metabot-analytics.queries :as analytics.queries]
   [metabase.api.common :as api]
   [metabase.api.macros :as api.macros]
   [metabase.api.routes.common :refer [+auth]]
   [metabase.request.core :as request]
   [metabase.util.malli.schema :as ms]))

(set! *warn-on-reflection* true)

;;; -------------------------------------------------- Schemas --------------------------------------------------

(def ^:private ConversationSummary
  "Schema for a conversation summary in list responses."
  [:map
   [:conversation_id         ms/UUIDString]
   [:created_at              ms/TemporalInstant]
   [:user_id                 ms/PositiveInt]
   [:summary                 [:maybe :string]]
   [:message_count           ms/IntGreaterThanOrEqualToZero]
   [:user_message_count      ms/IntGreaterThanOrEqualToZero]
   [:assistant_message_count ms/IntGreaterThanOrEqualToZero]
   [:total_tokens            ms/IntGreaterThanOrEqualToZero]
   [:last_message_at         [:maybe ms/TemporalInstant]]
   [:model                   [:maybe :string]]
   [:user                    [:maybe :map]]])

(def ^:private MessageDetail
  "Schema for a message in conversation detail responses."
  [:map
   [:message_id   ms/PositiveInt]
   [:created_at   ms/TemporalInstant]
   [:role         [:enum "user" "assistant"]]
   [:model        [:maybe :string]]
   [:total_tokens [:maybe ms/IntGreaterThanOrEqualToZero]]
   [:data         [:sequential :map]]])

(def ^:private GeneratedQuery
  "Schema for a single query generated by the bot during a conversation.
   One row per successful query-construction tool call. Errored calls are
   filtered out at the extractor."
  [:map
   [:tool        (into [:enum] (sort analytics.queries/query-generation-tool-names))]
   [:call_id     [:maybe :string]]
   [:message_id  ms/PositiveInt]
   [:query_id    [:maybe :string]]
   [:query_type  [:enum "sql" "notebook"]]
   [:sql         [:maybe :string]]
   [:mbql        [:maybe :map]]
   [:database_id [:maybe ms/PositiveInt]]
   [:tables      [:sequential :string]]])

(def ^:private ConversationDetail
  "Schema for full conversation detail response."
  [:map
   [:conversation_id ms/UUIDString]
   [:created_at      ms/TemporalInstant]
   [:user_id         ms/PositiveInt]
   [:summary         [:maybe :string]]
   [:state           [:maybe :map]]
   [:user            [:maybe :map]]
   [:messages        [:sequential MessageDetail]]
   [:chat_messages   [:sequential :map]]
   [:queries         [:sequential GeneratedQuery]]])

(def ^:private ListConversationsParams
  "Query-param schema for `GET /conversations`. `limit` and `offset` are handled by the
   offset-paging middleware and are read via `metabase.request.core`."
  [:map
   [:user-id  {:optional true} [:maybe ms/PositiveInt]]
   [:sort-by  {:optional true} [:maybe [:enum "created_at" "message_count" "total_tokens"]]]
   [:sort-dir {:optional true} [:maybe [:enum "asc" "desc"]]]])

(def ^:private ListConversationsResponse
  "Response schema for `GET /conversations`."
  [:map
   [:data   [:sequential ConversationSummary]]
   [:total  ms/IntGreaterThanOrEqualToZero]
   [:limit  ms/IntGreaterThanOrEqualToZero]
   [:offset ms/IntGreaterThanOrEqualToZero]])

(def ^:private ConversationIdParams
  "Route-param schema for endpoints addressing a single conversation by id."
  [:map [:id ms/UUIDString]])

;;; -------------------------------------------------- Endpoints --------------------------------------------------

(api.macros/defendpoint :get "/conversations" :- ListConversationsResponse
  "Return paginated list of AI conversations with summary statistics."
  [_route-params
   {:keys [user-id sort-by sort-dir]} :- ListConversationsParams]
  (api/check-superuser)
  (analytics.conversations/list-conversations
   {:user-id  user-id
    :sort-by  (keyword (or sort-by "created_at"))
    :sort-dir (if (= sort-dir "asc") :asc :desc)
    :limit    (or (request/limit) 50)
    :offset   (or (request/offset) 0)}))

(api.macros/defendpoint :get "/conversations/:id"
  :- ConversationDetail
  "Return full details for a specific conversation including all messages."
  [{:keys [id]} :- ConversationIdParams]
  (api/check-superuser)
  (analytics.conversations/fetch-conversation-detail id))

;;; -------------------------------------------------- Routes --------------------------------------------------

(def ^{:arglists '([request respond raise])} routes
  "Routes for `/api/ee/metabot-analytics/`."
  (+auth (api.macros/ns-handler *ns*)))
